#!/bin/sh

# AMD = added, modified, deleted
files=$(git diff --cached --name-only --diff-filter=AMD)

LIGHT_RED='\033[1;31m'
NC='\033[0m' # No Color

# naive regex check for .proto extension
if [[ "$files" =~ \.proto ]]
then
    # Check if there's a staged diff in /docs
    result=$(git diff --cached --raw docs/)
    if [ -n "$result" ]; then
      # There is a change to docs, exit
      exit 1
    else
      # Don't block, but warn that the docs need updating.
      echo "This commit contains .proto changes but the docs have not been updated."
      echo "Your changes were committed, but ${LIGHT_RED}please run 'make all' or this will fail in CI${NC}"
      exit 1
    fi

fi

exit 1
