// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: openfga/v1/authzmodel.proto

package openfgav1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConditionParamTypeRef_TypeName int32

const (
	ConditionParamTypeRef_TYPE_NAME_UNSPECIFIED ConditionParamTypeRef_TypeName = 0
	ConditionParamTypeRef_TYPE_NAME_ANY         ConditionParamTypeRef_TypeName = 1
	ConditionParamTypeRef_TYPE_NAME_BOOL        ConditionParamTypeRef_TypeName = 2
	ConditionParamTypeRef_TYPE_NAME_STRING      ConditionParamTypeRef_TypeName = 3
	ConditionParamTypeRef_TYPE_NAME_INT         ConditionParamTypeRef_TypeName = 4
	ConditionParamTypeRef_TYPE_NAME_UINT        ConditionParamTypeRef_TypeName = 5
	ConditionParamTypeRef_TYPE_NAME_DOUBLE      ConditionParamTypeRef_TypeName = 6
	ConditionParamTypeRef_TYPE_NAME_DURATION    ConditionParamTypeRef_TypeName = 7
	ConditionParamTypeRef_TYPE_NAME_TIMESTAMP   ConditionParamTypeRef_TypeName = 8
	ConditionParamTypeRef_TYPE_NAME_MAP         ConditionParamTypeRef_TypeName = 9
	ConditionParamTypeRef_TYPE_NAME_LIST        ConditionParamTypeRef_TypeName = 10
	ConditionParamTypeRef_TYPE_NAME_IPADDRESS   ConditionParamTypeRef_TypeName = 11
)

// Enum value maps for ConditionParamTypeRef_TypeName.
var (
	ConditionParamTypeRef_TypeName_name = map[int32]string{
		0:  "TYPE_NAME_UNSPECIFIED",
		1:  "TYPE_NAME_ANY",
		2:  "TYPE_NAME_BOOL",
		3:  "TYPE_NAME_STRING",
		4:  "TYPE_NAME_INT",
		5:  "TYPE_NAME_UINT",
		6:  "TYPE_NAME_DOUBLE",
		7:  "TYPE_NAME_DURATION",
		8:  "TYPE_NAME_TIMESTAMP",
		9:  "TYPE_NAME_MAP",
		10: "TYPE_NAME_LIST",
		11: "TYPE_NAME_IPADDRESS",
	}
	ConditionParamTypeRef_TypeName_value = map[string]int32{
		"TYPE_NAME_UNSPECIFIED": 0,
		"TYPE_NAME_ANY":         1,
		"TYPE_NAME_BOOL":        2,
		"TYPE_NAME_STRING":      3,
		"TYPE_NAME_INT":         4,
		"TYPE_NAME_UINT":        5,
		"TYPE_NAME_DOUBLE":      6,
		"TYPE_NAME_DURATION":    7,
		"TYPE_NAME_TIMESTAMP":   8,
		"TYPE_NAME_MAP":         9,
		"TYPE_NAME_LIST":        10,
		"TYPE_NAME_IPADDRESS":   11,
	}
)

func (x ConditionParamTypeRef_TypeName) Enum() *ConditionParamTypeRef_TypeName {
	p := new(ConditionParamTypeRef_TypeName)
	*p = x
	return p
}

func (x ConditionParamTypeRef_TypeName) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConditionParamTypeRef_TypeName) Descriptor() protoreflect.EnumDescriptor {
	return file_openfga_v1_authzmodel_proto_enumTypes[0].Descriptor()
}

func (ConditionParamTypeRef_TypeName) Type() protoreflect.EnumType {
	return &file_openfga_v1_authzmodel_proto_enumTypes[0]
}

func (x ConditionParamTypeRef_TypeName) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConditionParamTypeRef_TypeName.Descriptor instead.
func (ConditionParamTypeRef_TypeName) EnumDescriptor() ([]byte, []int) {
	return file_openfga_v1_authzmodel_proto_rawDescGZIP(), []int{18, 0}
}

type AuthorizationModel struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SchemaVersion   string                 `protobuf:"bytes,2,opt,name=schema_version,proto3" json:"schema_version,omitempty"`
	TypeDefinitions []*TypeDefinition      `protobuf:"bytes,3,rep,name=type_definitions,proto3" json:"type_definitions,omitempty"`
	Conditions      map[string]*Condition  `protobuf:"bytes,4,rep,name=conditions,proto3" json:"conditions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AuthorizationModel) Reset() {
	*x = AuthorizationModel{}
	mi := &file_openfga_v1_authzmodel_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizationModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizationModel) ProtoMessage() {}

func (x *AuthorizationModel) ProtoReflect() protoreflect.Message {
	mi := &file_openfga_v1_authzmodel_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizationModel.ProtoReflect.Descriptor instead.
func (*AuthorizationModel) Descriptor() ([]byte, []int) {
	return file_openfga_v1_authzmodel_proto_rawDescGZIP(), []int{0}
}

func (x *AuthorizationModel) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AuthorizationModel) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

func (x *AuthorizationModel) GetTypeDefinitions() []*TypeDefinition {
	if x != nil {
		return x.TypeDefinitions
	}
	return nil
}

func (x *AuthorizationModel) GetConditions() map[string]*Condition {
	if x != nil {
		return x.Conditions
	}
	return nil
}

type TypeDefinition struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Type      string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Relations map[string]*Userset    `protobuf:"bytes,2,rep,name=relations,proto3" json:"relations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// A map whose keys are the name of the relation and whose value is the Metadata for that relation.
	// It also holds information around the module name and source file if this model was constructed
	// from a modular model.
	Metadata      *Metadata `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TypeDefinition) Reset() {
	*x = TypeDefinition{}
	mi := &file_openfga_v1_authzmodel_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TypeDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TypeDefinition) ProtoMessage() {}

func (x *TypeDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_openfga_v1_authzmodel_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TypeDefinition.ProtoReflect.Descriptor instead.
func (*TypeDefinition) Descriptor() ([]byte, []int) {
	return file_openfga_v1_authzmodel_proto_rawDescGZIP(), []int{1}
}

func (x *TypeDefinition) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *TypeDefinition) GetRelations() map[string]*Userset {
	if x != nil {
		return x.Relations
	}
	return nil
}

func (x *TypeDefinition) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type Relation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Rewrite       *Userset               `protobuf:"bytes,2,opt,name=rewrite,proto3" json:"rewrite,omitempty"`
	TypeInfo      *RelationTypeInfo      `protobuf:"bytes,3,opt,name=type_info,json=typeInfo,proto3" json:"type_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Relation) Reset() {
	*x = Relation{}
	mi := &file_openfga_v1_authzmodel_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Relation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Relation) ProtoMessage() {}

func (x *Relation) ProtoReflect() protoreflect.Message {
	mi := &file_openfga_v1_authzmodel_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Relation.ProtoReflect.Descriptor instead.
func (*Relation) Descriptor() ([]byte, []int) {
	return file_openfga_v1_authzmodel_proto_rawDescGZIP(), []int{2}
}

func (x *Relation) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Relation) GetRewrite() *Userset {
	if x != nil {
		return x.Rewrite
	}
	return nil
}

func (x *Relation) GetTypeInfo() *RelationTypeInfo {
	if x != nil {
		return x.TypeInfo
	}
	return nil
}

type RelationTypeInfo struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	DirectlyRelatedUserTypes []*RelationReference   `protobuf:"bytes,1,rep,name=directly_related_user_types,proto3" json:"directly_related_user_types,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *RelationTypeInfo) Reset() {
	*x = RelationTypeInfo{}
	mi := &file_openfga_v1_authzmodel_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelationTypeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelationTypeInfo) ProtoMessage() {}

func (x *RelationTypeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_openfga_v1_authzmodel_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelationTypeInfo.ProtoReflect.Descriptor instead.
func (*RelationTypeInfo) Descriptor() ([]byte, []int) {
	return file_openfga_v1_authzmodel_proto_rawDescGZIP(), []int{3}
}

func (x *RelationTypeInfo) GetDirectlyRelatedUserTypes() []*RelationReference {
	if x != nil {
		return x.DirectlyRelatedUserTypes
	}
	return nil
}

type Metadata struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Relations     map[string]*RelationMetadata `protobuf:"bytes,1,rep,name=relations,proto3" json:"relations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Module        string                       `protobuf:"bytes,2,opt,name=module,proto3" json:"module,omitempty"`
	SourceInfo    *SourceInfo                  `protobuf:"bytes,3,opt,name=source_info,proto3" json:"source_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metadata) Reset() {
	*x = Metadata{}
	mi := &file_openfga_v1_authzmodel_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadata) ProtoMessage() {}

func (x *Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_openfga_v1_authzmodel_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metadata.ProtoReflect.Descriptor instead.
func (*Metadata) Descriptor() ([]byte, []int) {
	return file_openfga_v1_authzmodel_proto_rawDescGZIP(), []int{4}
}

func (x *Metadata) GetRelations() map[string]*RelationMetadata {
	if x != nil {
		return x.Relations
	}
	return nil
}

func (x *Metadata) GetModule() string {
	if x != nil {
		return x.Module
	}
	return ""
}

func (x *Metadata) GetSourceInfo() *SourceInfo {
	if x != nil {
		return x.SourceInfo
	}
	return nil
}

type SourceInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	File          string                 `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SourceInfo) Reset() {
	*x = SourceInfo{}
	mi := &file_openfga_v1_authzmodel_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SourceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourceInfo) ProtoMessage() {}

func (x *SourceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_openfga_v1_authzmodel_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourceInfo.ProtoReflect.Descriptor instead.
func (*SourceInfo) Descriptor() ([]byte, []int) {
	return file_openfga_v1_authzmodel_proto_rawDescGZIP(), []int{5}
}

func (x *SourceInfo) GetFile() string {
	if x != nil {
		return x.File
	}
	return ""
}

type RelationMetadata struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	DirectlyRelatedUserTypes []*RelationReference   `protobuf:"bytes,1,rep,name=directly_related_user_types,proto3" json:"directly_related_user_types,omitempty"`
	Module                   string                 `protobuf:"bytes,2,opt,name=module,proto3" json:"module,omitempty"`
	SourceInfo               *SourceInfo            `protobuf:"bytes,3,opt,name=source_info,proto3" json:"source_info,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *RelationMetadata) Reset() {
	*x = RelationMetadata{}
	mi := &file_openfga_v1_authzmodel_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelationMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelationMetadata) ProtoMessage() {}

func (x *RelationMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_openfga_v1_authzmodel_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelationMetadata.ProtoReflect.Descriptor instead.
func (*RelationMetadata) Descriptor() ([]byte, []int) {
	return file_openfga_v1_authzmodel_proto_rawDescGZIP(), []int{6}
}

func (x *RelationMetadata) GetDirectlyRelatedUserTypes() []*RelationReference {
	if x != nil {
		return x.DirectlyRelatedUserTypes
	}
	return nil
}

func (x *RelationMetadata) GetModule() string {
	if x != nil {
		return x.Module
	}
	return ""
}

func (x *RelationMetadata) GetSourceInfo() *SourceInfo {
	if x != nil {
		return x.SourceInfo
	}
	return nil
}

// RelationReference represents a relation of a particular object type (e.g. 'document#viewer').
type RelationReference struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Type  string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// Types that are valid to be assigned to RelationOrWildcard:
	//
	//	*RelationReference_Relation
	//	*RelationReference_Wildcard
	RelationOrWildcard isRelationReference_RelationOrWildcard `protobuf_oneof:"relation_or_wildcard"`
	// The name of a condition that is enforced over the allowed relation.
	Condition     string `protobuf:"bytes,4,opt,name=condition,proto3" json:"condition,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelationReference) Reset() {
	*x = RelationReference{}
	mi := &file_openfga_v1_authzmodel_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelationReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelationReference) ProtoMessage() {}

func (x *RelationReference) ProtoReflect() protoreflect.Message {
	mi := &file_openfga_v1_authzmodel_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelationReference.ProtoReflect.Descriptor instead.
func (*RelationReference) Descriptor() ([]byte, []int) {
	return file_openfga_v1_authzmodel_proto_rawDescGZIP(), []int{7}
}

func (x *RelationReference) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *RelationReference) GetRelationOrWildcard() isRelationReference_RelationOrWildcard {
	if x != nil {
		return x.RelationOrWildcard
	}
	return nil
}

func (x *RelationReference) GetRelation() string {
	if x != nil {
		if x, ok := x.RelationOrWildcard.(*RelationReference_Relation); ok {
			return x.Relation
		}
	}
	return ""
}

func (x *RelationReference) GetWildcard() *Wildcard {
	if x != nil {
		if x, ok := x.RelationOrWildcard.(*RelationReference_Wildcard); ok {
			return x.Wildcard
		}
	}
	return nil
}

func (x *RelationReference) GetCondition() string {
	if x != nil {
		return x.Condition
	}
	return ""
}

type isRelationReference_RelationOrWildcard interface {
	isRelationReference_RelationOrWildcard()
}

type RelationReference_Relation struct {
	Relation string `protobuf:"bytes,2,opt,name=relation,proto3,oneof"`
}

type RelationReference_Wildcard struct {
	Wildcard *Wildcard `protobuf:"bytes,3,opt,name=wildcard,proto3,oneof"`
}

func (*RelationReference_Relation) isRelationReference_RelationOrWildcard() {}

func (*RelationReference_Wildcard) isRelationReference_RelationOrWildcard() {}

type Wildcard struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Wildcard) Reset() {
	*x = Wildcard{}
	mi := &file_openfga_v1_authzmodel_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Wildcard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Wildcard) ProtoMessage() {}

func (x *Wildcard) ProtoReflect() protoreflect.Message {
	mi := &file_openfga_v1_authzmodel_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Wildcard.ProtoReflect.Descriptor instead.
func (*Wildcard) Descriptor() ([]byte, []int) {
	return file_openfga_v1_authzmodel_proto_rawDescGZIP(), []int{8}
}

type Usersets struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Child         []*Userset             `protobuf:"bytes,1,rep,name=child,proto3" json:"child,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Usersets) Reset() {
	*x = Usersets{}
	mi := &file_openfga_v1_authzmodel_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Usersets) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Usersets) ProtoMessage() {}

func (x *Usersets) ProtoReflect() protoreflect.Message {
	mi := &file_openfga_v1_authzmodel_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Usersets.ProtoReflect.Descriptor instead.
func (*Usersets) Descriptor() ([]byte, []int) {
	return file_openfga_v1_authzmodel_proto_rawDescGZIP(), []int{9}
}

func (x *Usersets) GetChild() []*Userset {
	if x != nil {
		return x.Child
	}
	return nil
}

type Difference struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *Userset               `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Subtract      *Userset               `protobuf:"bytes,2,opt,name=subtract,proto3" json:"subtract,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Difference) Reset() {
	*x = Difference{}
	mi := &file_openfga_v1_authzmodel_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Difference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Difference) ProtoMessage() {}

func (x *Difference) ProtoReflect() protoreflect.Message {
	mi := &file_openfga_v1_authzmodel_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Difference.ProtoReflect.Descriptor instead.
func (*Difference) Descriptor() ([]byte, []int) {
	return file_openfga_v1_authzmodel_proto_rawDescGZIP(), []int{10}
}

func (x *Difference) GetBase() *Userset {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *Difference) GetSubtract() *Userset {
	if x != nil {
		return x.Subtract
	}
	return nil
}

type Userset struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Userset:
	//
	//	*Userset_This
	//	*Userset_ComputedUserset
	//	*Userset_TupleToUserset
	//	*Userset_Union
	//	*Userset_Intersection
	//	*Userset_Difference
	Userset       isUserset_Userset `protobuf_oneof:"userset"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Userset) Reset() {
	*x = Userset{}
	mi := &file_openfga_v1_authzmodel_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Userset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Userset) ProtoMessage() {}

func (x *Userset) ProtoReflect() protoreflect.Message {
	mi := &file_openfga_v1_authzmodel_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Userset.ProtoReflect.Descriptor instead.
func (*Userset) Descriptor() ([]byte, []int) {
	return file_openfga_v1_authzmodel_proto_rawDescGZIP(), []int{11}
}

func (x *Userset) GetUserset() isUserset_Userset {
	if x != nil {
		return x.Userset
	}
	return nil
}

func (x *Userset) GetThis() *DirectUserset {
	if x != nil {
		if x, ok := x.Userset.(*Userset_This); ok {
			return x.This
		}
	}
	return nil
}

func (x *Userset) GetComputedUserset() *ObjectRelation {
	if x != nil {
		if x, ok := x.Userset.(*Userset_ComputedUserset); ok {
			return x.ComputedUserset
		}
	}
	return nil
}

func (x *Userset) GetTupleToUserset() *TupleToUserset {
	if x != nil {
		if x, ok := x.Userset.(*Userset_TupleToUserset); ok {
			return x.TupleToUserset
		}
	}
	return nil
}

func (x *Userset) GetUnion() *Usersets {
	if x != nil {
		if x, ok := x.Userset.(*Userset_Union); ok {
			return x.Union
		}
	}
	return nil
}

func (x *Userset) GetIntersection() *Usersets {
	if x != nil {
		if x, ok := x.Userset.(*Userset_Intersection); ok {
			return x.Intersection
		}
	}
	return nil
}

func (x *Userset) GetDifference() *Difference {
	if x != nil {
		if x, ok := x.Userset.(*Userset_Difference); ok {
			return x.Difference
		}
	}
	return nil
}

type isUserset_Userset interface {
	isUserset_Userset()
}

type Userset_This struct {
	This *DirectUserset `protobuf:"bytes,1,opt,name=this,proto3,oneof"`
}

type Userset_ComputedUserset struct {
	ComputedUserset *ObjectRelation `protobuf:"bytes,2,opt,name=computed_userset,json=computedUserset,proto3,oneof"`
}

type Userset_TupleToUserset struct {
	TupleToUserset *TupleToUserset `protobuf:"bytes,3,opt,name=tuple_to_userset,json=tupleToUserset,proto3,oneof"`
}

type Userset_Union struct {
	Union *Usersets `protobuf:"bytes,4,opt,name=union,proto3,oneof"`
}

type Userset_Intersection struct {
	Intersection *Usersets `protobuf:"bytes,5,opt,name=intersection,proto3,oneof"`
}

type Userset_Difference struct {
	Difference *Difference `protobuf:"bytes,6,opt,name=difference,proto3,oneof"`
}

func (*Userset_This) isUserset_Userset() {}

func (*Userset_ComputedUserset) isUserset_Userset() {}

func (*Userset_TupleToUserset) isUserset_Userset() {}

func (*Userset_Union) isUserset_Userset() {}

func (*Userset_Intersection) isUserset_Userset() {}

func (*Userset_Difference) isUserset_Userset() {}

// A DirectUserset is a sentinel message for referencing
// the direct members specified by an object/relation mapping.
type DirectUserset struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DirectUserset) Reset() {
	*x = DirectUserset{}
	mi := &file_openfga_v1_authzmodel_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DirectUserset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DirectUserset) ProtoMessage() {}

func (x *DirectUserset) ProtoReflect() protoreflect.Message {
	mi := &file_openfga_v1_authzmodel_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DirectUserset.ProtoReflect.Descriptor instead.
func (*DirectUserset) Descriptor() ([]byte, []int) {
	return file_openfga_v1_authzmodel_proto_rawDescGZIP(), []int{12}
}

type ObjectRelation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Object        string                 `protobuf:"bytes,1,opt,name=object,proto3" json:"object,omitempty"`
	Relation      string                 `protobuf:"bytes,2,opt,name=relation,proto3" json:"relation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObjectRelation) Reset() {
	*x = ObjectRelation{}
	mi := &file_openfga_v1_authzmodel_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObjectRelation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectRelation) ProtoMessage() {}

func (x *ObjectRelation) ProtoReflect() protoreflect.Message {
	mi := &file_openfga_v1_authzmodel_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectRelation.ProtoReflect.Descriptor instead.
func (*ObjectRelation) Descriptor() ([]byte, []int) {
	return file_openfga_v1_authzmodel_proto_rawDescGZIP(), []int{13}
}

func (x *ObjectRelation) GetObject() string {
	if x != nil {
		return x.Object
	}
	return ""
}

func (x *ObjectRelation) GetRelation() string {
	if x != nil {
		return x.Relation
	}
	return ""
}

type ComputedUserset struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Relation      string                 `protobuf:"bytes,1,opt,name=relation,proto3" json:"relation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ComputedUserset) Reset() {
	*x = ComputedUserset{}
	mi := &file_openfga_v1_authzmodel_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComputedUserset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComputedUserset) ProtoMessage() {}

func (x *ComputedUserset) ProtoReflect() protoreflect.Message {
	mi := &file_openfga_v1_authzmodel_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComputedUserset.ProtoReflect.Descriptor instead.
func (*ComputedUserset) Descriptor() ([]byte, []int) {
	return file_openfga_v1_authzmodel_proto_rawDescGZIP(), []int{14}
}

func (x *ComputedUserset) GetRelation() string {
	if x != nil {
		return x.Relation
	}
	return ""
}

type TupleToUserset struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The target object/relation
	Tupleset        *ObjectRelation `protobuf:"bytes,1,opt,name=tupleset,proto3" json:"tupleset,omitempty"`
	ComputedUserset *ObjectRelation `protobuf:"bytes,2,opt,name=computed_userset,json=computedUserset,proto3" json:"computed_userset,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TupleToUserset) Reset() {
	*x = TupleToUserset{}
	mi := &file_openfga_v1_authzmodel_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TupleToUserset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TupleToUserset) ProtoMessage() {}

func (x *TupleToUserset) ProtoReflect() protoreflect.Message {
	mi := &file_openfga_v1_authzmodel_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TupleToUserset.ProtoReflect.Descriptor instead.
func (*TupleToUserset) Descriptor() ([]byte, []int) {
	return file_openfga_v1_authzmodel_proto_rawDescGZIP(), []int{15}
}

func (x *TupleToUserset) GetTupleset() *ObjectRelation {
	if x != nil {
		return x.Tupleset
	}
	return nil
}

func (x *TupleToUserset) GetComputedUserset() *ObjectRelation {
	if x != nil {
		return x.ComputedUserset
	}
	return nil
}

type Condition struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A unique name for the condition
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// A Google CEL expression, expressed as a string.
	Expression string `protobuf:"bytes,2,opt,name=expression,proto3" json:"expression,omitempty"`
	// A map of parameter names to the parameter's defined type reference.
	Parameters    map[string]*ConditionParamTypeRef `protobuf:"bytes,3,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Metadata      *ConditionMetadata                `protobuf:"bytes,4,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Condition) Reset() {
	*x = Condition{}
	mi := &file_openfga_v1_authzmodel_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Condition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Condition) ProtoMessage() {}

func (x *Condition) ProtoReflect() protoreflect.Message {
	mi := &file_openfga_v1_authzmodel_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Condition.ProtoReflect.Descriptor instead.
func (*Condition) Descriptor() ([]byte, []int) {
	return file_openfga_v1_authzmodel_proto_rawDescGZIP(), []int{16}
}

func (x *Condition) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Condition) GetExpression() string {
	if x != nil {
		return x.Expression
	}
	return ""
}

func (x *Condition) GetParameters() map[string]*ConditionParamTypeRef {
	if x != nil {
		return x.Parameters
	}
	return nil
}

func (x *Condition) GetMetadata() *ConditionMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type ConditionMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Module        string                 `protobuf:"bytes,1,opt,name=module,proto3" json:"module,omitempty"`
	SourceInfo    *SourceInfo            `protobuf:"bytes,2,opt,name=source_info,proto3" json:"source_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConditionMetadata) Reset() {
	*x = ConditionMetadata{}
	mi := &file_openfga_v1_authzmodel_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConditionMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConditionMetadata) ProtoMessage() {}

func (x *ConditionMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_openfga_v1_authzmodel_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConditionMetadata.ProtoReflect.Descriptor instead.
func (*ConditionMetadata) Descriptor() ([]byte, []int) {
	return file_openfga_v1_authzmodel_proto_rawDescGZIP(), []int{17}
}

func (x *ConditionMetadata) GetModule() string {
	if x != nil {
		return x.Module
	}
	return ""
}

func (x *ConditionMetadata) GetSourceInfo() *SourceInfo {
	if x != nil {
		return x.SourceInfo
	}
	return nil
}

type ConditionParamTypeRef struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	TypeName      ConditionParamTypeRef_TypeName `protobuf:"varint,1,opt,name=type_name,proto3,enum=openfga.v1.ConditionParamTypeRef_TypeName" json:"type_name,omitempty"`
	GenericTypes  []*ConditionParamTypeRef       `protobuf:"bytes,2,rep,name=generic_types,proto3" json:"generic_types,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConditionParamTypeRef) Reset() {
	*x = ConditionParamTypeRef{}
	mi := &file_openfga_v1_authzmodel_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConditionParamTypeRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConditionParamTypeRef) ProtoMessage() {}

func (x *ConditionParamTypeRef) ProtoReflect() protoreflect.Message {
	mi := &file_openfga_v1_authzmodel_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConditionParamTypeRef.ProtoReflect.Descriptor instead.
func (*ConditionParamTypeRef) Descriptor() ([]byte, []int) {
	return file_openfga_v1_authzmodel_proto_rawDescGZIP(), []int{18}
}

func (x *ConditionParamTypeRef) GetTypeName() ConditionParamTypeRef_TypeName {
	if x != nil {
		return x.TypeName
	}
	return ConditionParamTypeRef_TYPE_NAME_UNSPECIFIED
}

func (x *ConditionParamTypeRef) GetGenericTypes() []*ConditionParamTypeRef {
	if x != nil {
		return x.GenericTypes
	}
	return nil
}

var File_openfga_v1_authzmodel_proto protoreflect.FileDescriptor

const file_openfga_v1_authzmodel_proto_rawDesc = "" +
	"\n" +
	"\x1bopenfga/v1/authzmodel.proto\x12\n" +
	"openfga.v1\x1a\x1fgoogle/api/field_behavior.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\x1a\x17validate/validate.proto\"\x94\x06\n" +
	"\x12AuthorizationModel\x12_\n" +
	"\x02id\x18\x01 \x01(\tBO\x92A\x1eJ\x1c\"01G5JAVJ41T49E9TT3SKVS7X1J\"\xe0A\x02\xfaB(r&2!^[ABCDEFGHJKMNPQRSTVWXYZ0-9]{26}$\xd0\x01\x00R\x02id\x12B\n" +
	"\x0eschema_version\x18\x02 \x01(\tB\x1a\xe0A\x02\xfaB\x14r\x122\r^[1-9].[1-9]$\xd0\x01\x00R\x0eschema_version\x12\x8f\x03\n" +
	"\x10type_definitions\x18\x03 \x03(\v2\x1a.openfga.v1.TypeDefinitionB\xc6\x02\x92A\xbf\x02J\xbc\x02[{\"type\": \"user\"}, {\"type\":\"document\",\"relations\":{\"reader\":{\"union\":{\"child\":[{\"this\":{}},{\"computedUserset\":{\"object\":\"\",\"relation\":\"writer\"}}]}},\"writer\":{\"this\":{}}},\"metadata\":{\"relations\":{\"reader\":{\"directly_related_user_types\":[{\"type\":\"user\"}]},\"writer\":{\"directly_related_user_types\":[{\"type\":\"user\"}]}}}}]\xe0A\x02R\x10type_definitions\x12q\n" +
	"\n" +
	"conditions\x18\x04 \x03(\v2..openfga.v1.AuthorizationModel.ConditionsEntryB!\xfaB\x1e\x9a\x01\x1b\x10\x19\"\x17r\x152\x10^[^:#@\\s]{1,50}$\xd0\x01\x00R\n" +
	"conditions\x1aT\n" +
	"\x0fConditionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12+\n" +
	"\x05value\x18\x02 \x01(\v2\x15.openfga.v1.ConditionR\x05value:\x028\x01\"\xbd\x03\n" +
	"\x0eTypeDefinition\x12A\n" +
	"\x04type\x18\x01 \x01(\tB-\x92A\fJ\n" +
	"\"document\"\xe0A\x02\xfaB\x18r\x162\x11^[^:#@\\s]{1,254}$\xd0\x01\x00R\x04type\x12\xe2\x01\n" +
	"\trelations\x18\x02 \x03(\v2).openfga.v1.TypeDefinition.RelationsEntryB\x98\x01\x92AyJw{\"reader\":{\"union\":{\"child\":[{\"this\":{}},{\"computedUserset\":{\"object\":\"\",\"relation\":\"writer\"}}]}},\"writer\":{\"this\":{}}}\xfaB\x19\x9a\x01\x16\"\x14r\x122\x10^[^:#@\\s]{1,50}$R\trelations\x120\n" +
	"\bmetadata\x18\x03 \x01(\v2\x14.openfga.v1.MetadataR\bmetadata\x1aQ\n" +
	"\x0eRelationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12)\n" +
	"\x05value\x18\x02 \x01(\v2\x13.openfga.v1.UsersetR\x05value:\x028\x01\"\xb1\x01\n" +
	"\bRelation\x12.\n" +
	"\x04name\x18\x01 \x01(\tB\x1a\xfaB\x17r\x152\x10^[^:#@\\s]{1,50}$\xd0\x01\x00R\x04name\x12:\n" +
	"\arewrite\x18\x02 \x01(\v2\x13.openfga.v1.UsersetB\v\xe0A\x02\xfaB\x05\x8a\x01\x02\x10\x01R\arewrite\x129\n" +
	"\ttype_info\x18\x03 \x01(\v2\x1c.openfga.v1.RelationTypeInfoR\btypeInfo\"s\n" +
	"\x10RelationTypeInfo\x12_\n" +
	"\x1bdirectly_related_user_types\x18\x01 \x03(\v2\x1d.openfga.v1.RelationReferenceR\x1bdirectly_related_user_types\"\x97\x02\n" +
	"\bMetadata\x12A\n" +
	"\trelations\x18\x01 \x03(\v2#.openfga.v1.Metadata.RelationsEntryR\trelations\x122\n" +
	"\x06module\x18\x02 \x01(\tB\x1a\xfaB\x17r\x152\x10^[^:#@\\s]{1,50}$\xd0\x01\x01R\x06module\x128\n" +
	"\vsource_info\x18\x03 \x01(\v2\x16.openfga.v1.SourceInfoR\vsource_info\x1aZ\n" +
	"\x0eRelationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x122\n" +
	"\x05value\x18\x02 \x01(\v2\x1c.openfga.v1.RelationMetadataR\x05value:\x028\x01\"J\n" +
	"\n" +
	"SourceInfo\x12<\n" +
	"\x04file\x18\x01 \x01(\tB(\xfaB%r#2\x1e^[a-zA-Z0-9_\\-\\/]{1,100}\\.fga$\xd0\x01\x01R\x04file\"\xe1\x01\n" +
	"\x10RelationMetadata\x12_\n" +
	"\x1bdirectly_related_user_types\x18\x01 \x03(\v2\x1d.openfga.v1.RelationReferenceR\x1bdirectly_related_user_types\x122\n" +
	"\x06module\x18\x02 \x01(\tB\x1a\xfaB\x17r\x152\x10^[^:#@\\s]{1,50}$\xd0\x01\x01R\x06module\x128\n" +
	"\vsource_info\x18\x03 \x01(\v2\x16.openfga.v1.SourceInfoR\vsource_info\"\xa0\x02\n" +
	"\x11RelationReference\x12>\n" +
	"\x04type\x18\x01 \x01(\tB*\x92A\tJ\a\"group\"\xe0A\x02\xfaB\x18r\x162\x11^[^:#@\\s]{1,254}$\xd0\x01\x00R\x04type\x12E\n" +
	"\brelation\x18\x02 \x01(\tB'\x92A\n" +
	"J\b\"member\"\xfaB\x17r\x152\x10^[^:#@\\s]{1,50}$\xd0\x01\x01H\x00R\brelation\x122\n" +
	"\bwildcard\x18\x03 \x01(\v2\x14.openfga.v1.WildcardH\x00R\bwildcard\x128\n" +
	"\tcondition\x18\x04 \x01(\tB\x1a\xfaB\x17r\x152\x10^[^:#@\\s]{1,50}$\xd0\x01\x01R\tconditionB\x16\n" +
	"\x14relation_or_wildcard\"\n" +
	"\n" +
	"\bWildcard\":\n" +
	"\bUsersets\x12.\n" +
	"\x05child\x18\x01 \x03(\v2\x13.openfga.v1.UsersetB\x03\xe0A\x02R\x05child\"\x80\x01\n" +
	"\n" +
	"Difference\x124\n" +
	"\x04base\x18\x01 \x01(\v2\x13.openfga.v1.UsersetB\v\xe0A\x02\xfaB\x05\x8a\x01\x02\x10\x01R\x04base\x12<\n" +
	"\bsubtract\x18\x02 \x01(\v2\x13.openfga.v1.UsersetB\v\xe0A\x02\xfaB\x05\x8a\x01\x02\x10\x01R\bsubtract\"\xfa\x02\n" +
	"\aUserset\x12/\n" +
	"\x04this\x18\x01 \x01(\v2\x19.openfga.v1.DirectUsersetH\x00R\x04this\x12G\n" +
	"\x10computed_userset\x18\x02 \x01(\v2\x1a.openfga.v1.ObjectRelationH\x00R\x0fcomputedUserset\x12F\n" +
	"\x10tuple_to_userset\x18\x03 \x01(\v2\x1a.openfga.v1.TupleToUsersetH\x00R\x0etupleToUserset\x12,\n" +
	"\x05union\x18\x04 \x01(\v2\x14.openfga.v1.UsersetsH\x00R\x05union\x12:\n" +
	"\fintersection\x18\x05 \x01(\v2\x14.openfga.v1.UsersetsH\x00R\fintersection\x128\n" +
	"\n" +
	"difference\x18\x06 \x01(\v2\x16.openfga.v1.DifferenceH\x00R\n" +
	"differenceB\t\n" +
	"\auserset\"\x0f\n" +
	"\rDirectUserset\"W\n" +
	"\x0eObjectRelation\x12 \n" +
	"\x06object\x18\x01 \x01(\tB\b\xfaB\x05r\x03(\x80\x02R\x06object\x12#\n" +
	"\brelation\x18\x02 \x01(\tB\a\xfaB\x04r\x02(2R\brelation\"<\n" +
	"\x0fComputedUserset\x12)\n" +
	"\brelation\x18\x01 \x01(\tB\r\xe0A\x02\xfaB\ar\x05(2\xd0\x01\x00R\brelation\"\xa9\x01\n" +
	"\x0eTupleToUserset\x12C\n" +
	"\btupleset\x18\x01 \x01(\v2\x1a.openfga.v1.ObjectRelationB\v\xe0A\x02\xfaB\x05\x8a\x01\x02\x10\x01R\btupleset\x12R\n" +
	"\x10computed_userset\x18\x02 \x01(\v2\x1a.openfga.v1.ObjectRelationB\v\xe0A\x02\xfaB\x05\x8a\x01\x02\x10\x01R\x0fcomputedUserset\"\xf2\x02\n" +
	"\tCondition\x121\n" +
	"\x04name\x18\x01 \x01(\tB\x1d\xe0A\x02\xfaB\x17r\x152\x10^[^:#@\\s]{1,50}$\xd0\x01\x00R\x04name\x12.\n" +
	"\n" +
	"expression\x18\x02 \x01(\tB\x0e\xe0A\x02\xfaB\br\x06(\x80\x04\xd0\x01\x00R\n" +
	"expression\x12e\n" +
	"\n" +
	"parameters\x18\x03 \x03(\v2%.openfga.v1.Condition.ParametersEntryB\x1e\xfaB\x1b\x9a\x01\x18\x10\x19\"\x14r\x122\x10^[^:#@\\s]{1,50}$R\n" +
	"parameters\x129\n" +
	"\bmetadata\x18\x04 \x01(\v2\x1d.openfga.v1.ConditionMetadataR\bmetadata\x1a`\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x127\n" +
	"\x05value\x18\x02 \x01(\v2!.openfga.v1.ConditionParamTypeRefR\x05value:\x028\x01\"\x81\x01\n" +
	"\x11ConditionMetadata\x122\n" +
	"\x06module\x18\x01 \x01(\tB\x1a\xfaB\x17r\x152\x10^[^:#@\\s]{1,50}$\xd0\x01\x01R\x06module\x128\n" +
	"\vsource_info\x18\x02 \x01(\v2\x16.openfga.v1.SourceInfoR\vsource_info\"\xd4\x03\n" +
	"\x15ConditionParamTypeRef\x12U\n" +
	"\ttype_name\x18\x01 \x01(\x0e2*.openfga.v1.ConditionParamTypeRef.TypeNameB\v\xe0A\x02\xfaB\x05\x82\x01\x02\x10\x01R\ttype_name\x12Q\n" +
	"\rgeneric_types\x18\x02 \x03(\v2!.openfga.v1.ConditionParamTypeRefB\b\xfaB\x05\x92\x01\x02\x10\x05R\rgeneric_types\"\x90\x02\n" +
	"\bTypeName\x12\x19\n" +
	"\x15TYPE_NAME_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rTYPE_NAME_ANY\x10\x01\x12\x12\n" +
	"\x0eTYPE_NAME_BOOL\x10\x02\x12\x14\n" +
	"\x10TYPE_NAME_STRING\x10\x03\x12\x11\n" +
	"\rTYPE_NAME_INT\x10\x04\x12\x12\n" +
	"\x0eTYPE_NAME_UINT\x10\x05\x12\x14\n" +
	"\x10TYPE_NAME_DOUBLE\x10\x06\x12\x16\n" +
	"\x12TYPE_NAME_DURATION\x10\a\x12\x17\n" +
	"\x13TYPE_NAME_TIMESTAMP\x10\b\x12\x11\n" +
	"\rTYPE_NAME_MAP\x10\t\x12\x12\n" +
	"\x0eTYPE_NAME_LIST\x10\n" +
	"\x12\x17\n" +
	"\x13TYPE_NAME_IPADDRESS\x10\vB\x9d\x01\n" +
	"\x0ecom.openfga.v1B\x0fAuthzmodelProtoP\x01Z1github.com/openfga/api/proto/openfga/v1;openfgav1\xa2\x02\x03OXX\xaa\x02\n" +
	"Openfga.V1\xca\x02\n" +
	"Openfga\\V1\xe2\x02\x16Openfga\\V1\\GPBMetadata\xea\x02\vOpenfga::V1b\x06proto3"

var (
	file_openfga_v1_authzmodel_proto_rawDescOnce sync.Once
	file_openfga_v1_authzmodel_proto_rawDescData []byte
)

func file_openfga_v1_authzmodel_proto_rawDescGZIP() []byte {
	file_openfga_v1_authzmodel_proto_rawDescOnce.Do(func() {
		file_openfga_v1_authzmodel_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_openfga_v1_authzmodel_proto_rawDesc), len(file_openfga_v1_authzmodel_proto_rawDesc)))
	})
	return file_openfga_v1_authzmodel_proto_rawDescData
}

var file_openfga_v1_authzmodel_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_openfga_v1_authzmodel_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_openfga_v1_authzmodel_proto_goTypes = []any{
	(ConditionParamTypeRef_TypeName)(0), // 0: openfga.v1.ConditionParamTypeRef.TypeName
	(*AuthorizationModel)(nil),          // 1: openfga.v1.AuthorizationModel
	(*TypeDefinition)(nil),              // 2: openfga.v1.TypeDefinition
	(*Relation)(nil),                    // 3: openfga.v1.Relation
	(*RelationTypeInfo)(nil),            // 4: openfga.v1.RelationTypeInfo
	(*Metadata)(nil),                    // 5: openfga.v1.Metadata
	(*SourceInfo)(nil),                  // 6: openfga.v1.SourceInfo
	(*RelationMetadata)(nil),            // 7: openfga.v1.RelationMetadata
	(*RelationReference)(nil),           // 8: openfga.v1.RelationReference
	(*Wildcard)(nil),                    // 9: openfga.v1.Wildcard
	(*Usersets)(nil),                    // 10: openfga.v1.Usersets
	(*Difference)(nil),                  // 11: openfga.v1.Difference
	(*Userset)(nil),                     // 12: openfga.v1.Userset
	(*DirectUserset)(nil),               // 13: openfga.v1.DirectUserset
	(*ObjectRelation)(nil),              // 14: openfga.v1.ObjectRelation
	(*ComputedUserset)(nil),             // 15: openfga.v1.ComputedUserset
	(*TupleToUserset)(nil),              // 16: openfga.v1.TupleToUserset
	(*Condition)(nil),                   // 17: openfga.v1.Condition
	(*ConditionMetadata)(nil),           // 18: openfga.v1.ConditionMetadata
	(*ConditionParamTypeRef)(nil),       // 19: openfga.v1.ConditionParamTypeRef
	nil,                                 // 20: openfga.v1.AuthorizationModel.ConditionsEntry
	nil,                                 // 21: openfga.v1.TypeDefinition.RelationsEntry
	nil,                                 // 22: openfga.v1.Metadata.RelationsEntry
	nil,                                 // 23: openfga.v1.Condition.ParametersEntry
}
var file_openfga_v1_authzmodel_proto_depIdxs = []int32{
	2,  // 0: openfga.v1.AuthorizationModel.type_definitions:type_name -> openfga.v1.TypeDefinition
	20, // 1: openfga.v1.AuthorizationModel.conditions:type_name -> openfga.v1.AuthorizationModel.ConditionsEntry
	21, // 2: openfga.v1.TypeDefinition.relations:type_name -> openfga.v1.TypeDefinition.RelationsEntry
	5,  // 3: openfga.v1.TypeDefinition.metadata:type_name -> openfga.v1.Metadata
	12, // 4: openfga.v1.Relation.rewrite:type_name -> openfga.v1.Userset
	4,  // 5: openfga.v1.Relation.type_info:type_name -> openfga.v1.RelationTypeInfo
	8,  // 6: openfga.v1.RelationTypeInfo.directly_related_user_types:type_name -> openfga.v1.RelationReference
	22, // 7: openfga.v1.Metadata.relations:type_name -> openfga.v1.Metadata.RelationsEntry
	6,  // 8: openfga.v1.Metadata.source_info:type_name -> openfga.v1.SourceInfo
	8,  // 9: openfga.v1.RelationMetadata.directly_related_user_types:type_name -> openfga.v1.RelationReference
	6,  // 10: openfga.v1.RelationMetadata.source_info:type_name -> openfga.v1.SourceInfo
	9,  // 11: openfga.v1.RelationReference.wildcard:type_name -> openfga.v1.Wildcard
	12, // 12: openfga.v1.Usersets.child:type_name -> openfga.v1.Userset
	12, // 13: openfga.v1.Difference.base:type_name -> openfga.v1.Userset
	12, // 14: openfga.v1.Difference.subtract:type_name -> openfga.v1.Userset
	13, // 15: openfga.v1.Userset.this:type_name -> openfga.v1.DirectUserset
	14, // 16: openfga.v1.Userset.computed_userset:type_name -> openfga.v1.ObjectRelation
	16, // 17: openfga.v1.Userset.tuple_to_userset:type_name -> openfga.v1.TupleToUserset
	10, // 18: openfga.v1.Userset.union:type_name -> openfga.v1.Usersets
	10, // 19: openfga.v1.Userset.intersection:type_name -> openfga.v1.Usersets
	11, // 20: openfga.v1.Userset.difference:type_name -> openfga.v1.Difference
	14, // 21: openfga.v1.TupleToUserset.tupleset:type_name -> openfga.v1.ObjectRelation
	14, // 22: openfga.v1.TupleToUserset.computed_userset:type_name -> openfga.v1.ObjectRelation
	23, // 23: openfga.v1.Condition.parameters:type_name -> openfga.v1.Condition.ParametersEntry
	18, // 24: openfga.v1.Condition.metadata:type_name -> openfga.v1.ConditionMetadata
	6,  // 25: openfga.v1.ConditionMetadata.source_info:type_name -> openfga.v1.SourceInfo
	0,  // 26: openfga.v1.ConditionParamTypeRef.type_name:type_name -> openfga.v1.ConditionParamTypeRef.TypeName
	19, // 27: openfga.v1.ConditionParamTypeRef.generic_types:type_name -> openfga.v1.ConditionParamTypeRef
	17, // 28: openfga.v1.AuthorizationModel.ConditionsEntry.value:type_name -> openfga.v1.Condition
	12, // 29: openfga.v1.TypeDefinition.RelationsEntry.value:type_name -> openfga.v1.Userset
	7,  // 30: openfga.v1.Metadata.RelationsEntry.value:type_name -> openfga.v1.RelationMetadata
	19, // 31: openfga.v1.Condition.ParametersEntry.value:type_name -> openfga.v1.ConditionParamTypeRef
	32, // [32:32] is the sub-list for method output_type
	32, // [32:32] is the sub-list for method input_type
	32, // [32:32] is the sub-list for extension type_name
	32, // [32:32] is the sub-list for extension extendee
	0,  // [0:32] is the sub-list for field type_name
}

func init() { file_openfga_v1_authzmodel_proto_init() }
func file_openfga_v1_authzmodel_proto_init() {
	if File_openfga_v1_authzmodel_proto != nil {
		return
	}
	file_openfga_v1_authzmodel_proto_msgTypes[7].OneofWrappers = []any{
		(*RelationReference_Relation)(nil),
		(*RelationReference_Wildcard)(nil),
	}
	file_openfga_v1_authzmodel_proto_msgTypes[11].OneofWrappers = []any{
		(*Userset_This)(nil),
		(*Userset_ComputedUserset)(nil),
		(*Userset_TupleToUserset)(nil),
		(*Userset_Union)(nil),
		(*Userset_Intersection)(nil),
		(*Userset_Difference)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_openfga_v1_authzmodel_proto_rawDesc), len(file_openfga_v1_authzmodel_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_openfga_v1_authzmodel_proto_goTypes,
		DependencyIndexes: file_openfga_v1_authzmodel_proto_depIdxs,
		EnumInfos:         file_openfga_v1_authzmodel_proto_enumTypes,
		MessageInfos:      file_openfga_v1_authzmodel_proto_msgTypes,
	}.Build()
	File_openfga_v1_authzmodel_proto = out.File
	file_openfga_v1_authzmodel_proto_goTypes = nil
	file_openfga_v1_authzmodel_proto_depIdxs = nil
}
