// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: openfga/v1/errors_ignore.proto

package openfgav1

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthErrorCode int32

const (
	AuthErrorCode_no_auth_error                    AuthErrorCode = 0
	AuthErrorCode_auth_failed_invalid_subject      AuthErrorCode = 1001
	AuthErrorCode_auth_failed_invalid_audience     AuthErrorCode = 1002
	AuthErrorCode_auth_failed_invalid_issuer       AuthErrorCode = 1003
	AuthErrorCode_invalid_claims                   AuthErrorCode = 1004
	AuthErrorCode_auth_failed_invalid_bearer_token AuthErrorCode = 1005
	AuthErrorCode_bearer_token_missing             AuthErrorCode = 1010
	AuthErrorCode_unauthenticated                  AuthErrorCode = 1500
	AuthErrorCode_forbidden                        AuthErrorCode = 1600
)

// Enum value maps for AuthErrorCode.
var (
	AuthErrorCode_name = map[int32]string{
		0:    "no_auth_error",
		1001: "auth_failed_invalid_subject",
		1002: "auth_failed_invalid_audience",
		1003: "auth_failed_invalid_issuer",
		1004: "invalid_claims",
		1005: "auth_failed_invalid_bearer_token",
		1010: "bearer_token_missing",
		1500: "unauthenticated",
		1600: "forbidden",
	}
	AuthErrorCode_value = map[string]int32{
		"no_auth_error":                    0,
		"auth_failed_invalid_subject":      1001,
		"auth_failed_invalid_audience":     1002,
		"auth_failed_invalid_issuer":       1003,
		"invalid_claims":                   1004,
		"auth_failed_invalid_bearer_token": 1005,
		"bearer_token_missing":             1010,
		"unauthenticated":                  1500,
		"forbidden":                        1600,
	}
)

func (x AuthErrorCode) Enum() *AuthErrorCode {
	p := new(AuthErrorCode)
	*p = x
	return p
}

func (x AuthErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AuthErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_openfga_v1_errors_ignore_proto_enumTypes[0].Descriptor()
}

func (AuthErrorCode) Type() protoreflect.EnumType {
	return &file_openfga_v1_errors_ignore_proto_enumTypes[0]
}

func (x AuthErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AuthErrorCode.Descriptor instead.
func (AuthErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_openfga_v1_errors_ignore_proto_rawDescGZIP(), []int{0}
}

type ErrorCode int32

const (
	ErrorCode_no_error                                         ErrorCode = 0
	ErrorCode_validation_error                                 ErrorCode = 2000
	ErrorCode_authorization_model_not_found                    ErrorCode = 2001
	ErrorCode_authorization_model_resolution_too_complex       ErrorCode = 2002
	ErrorCode_invalid_write_input                              ErrorCode = 2003
	ErrorCode_cannot_allow_duplicate_tuples_in_one_request     ErrorCode = 2004
	ErrorCode_cannot_allow_duplicate_types_in_one_request      ErrorCode = 2005
	ErrorCode_cannot_allow_multiple_references_to_one_relation ErrorCode = 2006
	ErrorCode_invalid_continuation_token                       ErrorCode = 2007
	ErrorCode_invalid_tuple_set                                ErrorCode = 2008
	ErrorCode_invalid_check_input                              ErrorCode = 2009
	ErrorCode_invalid_expand_input                             ErrorCode = 2010
	ErrorCode_unsupported_user_set                             ErrorCode = 2011
	ErrorCode_invalid_object_format                            ErrorCode = 2012
	ErrorCode_write_failed_due_to_invalid_input                ErrorCode = 2017
	ErrorCode_authorization_model_assertions_not_found         ErrorCode = 2018
	ErrorCode_latest_authorization_model_not_found             ErrorCode = 2020
	ErrorCode_type_not_found                                   ErrorCode = 2021
	ErrorCode_relation_not_found                               ErrorCode = 2022
	ErrorCode_empty_relation_definition                        ErrorCode = 2023
	ErrorCode_invalid_user                                     ErrorCode = 2025
	ErrorCode_invalid_tuple                                    ErrorCode = 2027
	ErrorCode_unknown_relation                                 ErrorCode = 2028
	ErrorCode_store_id_invalid_length                          ErrorCode = 2030
	ErrorCode_assertions_too_many_items                        ErrorCode = 2033
	ErrorCode_id_too_long                                      ErrorCode = 2034
	ErrorCode_authorization_model_id_too_long                  ErrorCode = 2036
	ErrorCode_tuple_key_value_not_specified                    ErrorCode = 2037
	ErrorCode_tuple_keys_too_many_or_too_few_items             ErrorCode = 2038
	ErrorCode_page_size_invalid                                ErrorCode = 2039
	ErrorCode_param_missing_value                              ErrorCode = 2040
	ErrorCode_difference_base_missing_value                    ErrorCode = 2041
	ErrorCode_subtract_base_missing_value                      ErrorCode = 2042
	ErrorCode_object_too_long                                  ErrorCode = 2043
	ErrorCode_relation_too_long                                ErrorCode = 2044
	ErrorCode_type_definitions_too_few_items                   ErrorCode = 2045
	ErrorCode_type_invalid_length                              ErrorCode = 2046
	ErrorCode_type_invalid_pattern                             ErrorCode = 2047
	ErrorCode_relations_too_few_items                          ErrorCode = 2048
	ErrorCode_relations_too_long                               ErrorCode = 2049
	ErrorCode_relations_invalid_pattern                        ErrorCode = 2050
	ErrorCode_object_invalid_pattern                           ErrorCode = 2051
	ErrorCode_query_string_type_continuation_token_mismatch    ErrorCode = 2052
	ErrorCode_exceeded_entity_limit                            ErrorCode = 2053
	ErrorCode_invalid_contextual_tuple                         ErrorCode = 2054
	ErrorCode_duplicate_contextual_tuple                       ErrorCode = 2055
	ErrorCode_invalid_authorization_model                      ErrorCode = 2056
	ErrorCode_unsupported_schema_version                       ErrorCode = 2057
	ErrorCode_cancelled                                        ErrorCode = 2058
	ErrorCode_invalid_start_time                               ErrorCode = 2059
)

// Enum value maps for ErrorCode.
var (
	ErrorCode_name = map[int32]string{
		0:    "no_error",
		2000: "validation_error",
		2001: "authorization_model_not_found",
		2002: "authorization_model_resolution_too_complex",
		2003: "invalid_write_input",
		2004: "cannot_allow_duplicate_tuples_in_one_request",
		2005: "cannot_allow_duplicate_types_in_one_request",
		2006: "cannot_allow_multiple_references_to_one_relation",
		2007: "invalid_continuation_token",
		2008: "invalid_tuple_set",
		2009: "invalid_check_input",
		2010: "invalid_expand_input",
		2011: "unsupported_user_set",
		2012: "invalid_object_format",
		2017: "write_failed_due_to_invalid_input",
		2018: "authorization_model_assertions_not_found",
		2020: "latest_authorization_model_not_found",
		2021: "type_not_found",
		2022: "relation_not_found",
		2023: "empty_relation_definition",
		2025: "invalid_user",
		2027: "invalid_tuple",
		2028: "unknown_relation",
		2030: "store_id_invalid_length",
		2033: "assertions_too_many_items",
		2034: "id_too_long",
		2036: "authorization_model_id_too_long",
		2037: "tuple_key_value_not_specified",
		2038: "tuple_keys_too_many_or_too_few_items",
		2039: "page_size_invalid",
		2040: "param_missing_value",
		2041: "difference_base_missing_value",
		2042: "subtract_base_missing_value",
		2043: "object_too_long",
		2044: "relation_too_long",
		2045: "type_definitions_too_few_items",
		2046: "type_invalid_length",
		2047: "type_invalid_pattern",
		2048: "relations_too_few_items",
		2049: "relations_too_long",
		2050: "relations_invalid_pattern",
		2051: "object_invalid_pattern",
		2052: "query_string_type_continuation_token_mismatch",
		2053: "exceeded_entity_limit",
		2054: "invalid_contextual_tuple",
		2055: "duplicate_contextual_tuple",
		2056: "invalid_authorization_model",
		2057: "unsupported_schema_version",
		2058: "cancelled",
		2059: "invalid_start_time",
	}
	ErrorCode_value = map[string]int32{
		"no_error":                                         0,
		"validation_error":                                 2000,
		"authorization_model_not_found":                    2001,
		"authorization_model_resolution_too_complex":       2002,
		"invalid_write_input":                              2003,
		"cannot_allow_duplicate_tuples_in_one_request":     2004,
		"cannot_allow_duplicate_types_in_one_request":      2005,
		"cannot_allow_multiple_references_to_one_relation": 2006,
		"invalid_continuation_token":                       2007,
		"invalid_tuple_set":                                2008,
		"invalid_check_input":                              2009,
		"invalid_expand_input":                             2010,
		"unsupported_user_set":                             2011,
		"invalid_object_format":                            2012,
		"write_failed_due_to_invalid_input":                2017,
		"authorization_model_assertions_not_found":         2018,
		"latest_authorization_model_not_found":             2020,
		"type_not_found":                                   2021,
		"relation_not_found":                               2022,
		"empty_relation_definition":                        2023,
		"invalid_user":                                     2025,
		"invalid_tuple":                                    2027,
		"unknown_relation":                                 2028,
		"store_id_invalid_length":                          2030,
		"assertions_too_many_items":                        2033,
		"id_too_long":                                      2034,
		"authorization_model_id_too_long":                  2036,
		"tuple_key_value_not_specified":                    2037,
		"tuple_keys_too_many_or_too_few_items":             2038,
		"page_size_invalid":                                2039,
		"param_missing_value":                              2040,
		"difference_base_missing_value":                    2041,
		"subtract_base_missing_value":                      2042,
		"object_too_long":                                  2043,
		"relation_too_long":                                2044,
		"type_definitions_too_few_items":                   2045,
		"type_invalid_length":                              2046,
		"type_invalid_pattern":                             2047,
		"relations_too_few_items":                          2048,
		"relations_too_long":                               2049,
		"relations_invalid_pattern":                        2050,
		"object_invalid_pattern":                           2051,
		"query_string_type_continuation_token_mismatch":    2052,
		"exceeded_entity_limit":                            2053,
		"invalid_contextual_tuple":                         2054,
		"duplicate_contextual_tuple":                       2055,
		"invalid_authorization_model":                      2056,
		"unsupported_schema_version":                       2057,
		"cancelled":                                        2058,
		"invalid_start_time":                               2059,
	}
)

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}

func (x ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_openfga_v1_errors_ignore_proto_enumTypes[1].Descriptor()
}

func (ErrorCode) Type() protoreflect.EnumType {
	return &file_openfga_v1_errors_ignore_proto_enumTypes[1]
}

func (x ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCode.Descriptor instead.
func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_openfga_v1_errors_ignore_proto_rawDescGZIP(), []int{1}
}

type UnprocessableContentErrorCode int32

const (
	UnprocessableContentErrorCode_no_throttled_error_code UnprocessableContentErrorCode = 0
	UnprocessableContentErrorCode_throttled_timeout_error UnprocessableContentErrorCode = 3500
)

// Enum value maps for UnprocessableContentErrorCode.
var (
	UnprocessableContentErrorCode_name = map[int32]string{
		0:    "no_throttled_error_code",
		3500: "throttled_timeout_error",
	}
	UnprocessableContentErrorCode_value = map[string]int32{
		"no_throttled_error_code": 0,
		"throttled_timeout_error": 3500,
	}
)

func (x UnprocessableContentErrorCode) Enum() *UnprocessableContentErrorCode {
	p := new(UnprocessableContentErrorCode)
	*p = x
	return p
}

func (x UnprocessableContentErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UnprocessableContentErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_openfga_v1_errors_ignore_proto_enumTypes[2].Descriptor()
}

func (UnprocessableContentErrorCode) Type() protoreflect.EnumType {
	return &file_openfga_v1_errors_ignore_proto_enumTypes[2]
}

func (x UnprocessableContentErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UnprocessableContentErrorCode.Descriptor instead.
func (UnprocessableContentErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_openfga_v1_errors_ignore_proto_rawDescGZIP(), []int{2}
}

type InternalErrorCode int32

const (
	InternalErrorCode_no_internal_error   InternalErrorCode = 0
	InternalErrorCode_internal_error      InternalErrorCode = 4000
	InternalErrorCode_deadline_exceeded   InternalErrorCode = 4004
	InternalErrorCode_already_exists      InternalErrorCode = 4005
	InternalErrorCode_resource_exhausted  InternalErrorCode = 4006
	InternalErrorCode_failed_precondition InternalErrorCode = 4007
	InternalErrorCode_aborted             InternalErrorCode = 4008
	InternalErrorCode_out_of_range        InternalErrorCode = 4009
	InternalErrorCode_unavailable         InternalErrorCode = 4010
	InternalErrorCode_data_loss           InternalErrorCode = 4011
)

// Enum value maps for InternalErrorCode.
var (
	InternalErrorCode_name = map[int32]string{
		0:    "no_internal_error",
		4000: "internal_error",
		4004: "deadline_exceeded",
		4005: "already_exists",
		4006: "resource_exhausted",
		4007: "failed_precondition",
		4008: "aborted",
		4009: "out_of_range",
		4010: "unavailable",
		4011: "data_loss",
	}
	InternalErrorCode_value = map[string]int32{
		"no_internal_error":   0,
		"internal_error":      4000,
		"deadline_exceeded":   4004,
		"already_exists":      4005,
		"resource_exhausted":  4006,
		"failed_precondition": 4007,
		"aborted":             4008,
		"out_of_range":        4009,
		"unavailable":         4010,
		"data_loss":           4011,
	}
)

func (x InternalErrorCode) Enum() *InternalErrorCode {
	p := new(InternalErrorCode)
	*p = x
	return p
}

func (x InternalErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InternalErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_openfga_v1_errors_ignore_proto_enumTypes[3].Descriptor()
}

func (InternalErrorCode) Type() protoreflect.EnumType {
	return &file_openfga_v1_errors_ignore_proto_enumTypes[3]
}

func (x InternalErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InternalErrorCode.Descriptor instead.
func (InternalErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_openfga_v1_errors_ignore_proto_rawDescGZIP(), []int{3}
}

type NotFoundErrorCode int32

const (
	NotFoundErrorCode_no_not_found_error NotFoundErrorCode = 0
	NotFoundErrorCode_undefined_endpoint NotFoundErrorCode = 5000
	NotFoundErrorCode_store_id_not_found NotFoundErrorCode = 5002
	NotFoundErrorCode_unimplemented      NotFoundErrorCode = 5004
)

// Enum value maps for NotFoundErrorCode.
var (
	NotFoundErrorCode_name = map[int32]string{
		0:    "no_not_found_error",
		5000: "undefined_endpoint",
		5002: "store_id_not_found",
		5004: "unimplemented",
	}
	NotFoundErrorCode_value = map[string]int32{
		"no_not_found_error": 0,
		"undefined_endpoint": 5000,
		"store_id_not_found": 5002,
		"unimplemented":      5004,
	}
)

func (x NotFoundErrorCode) Enum() *NotFoundErrorCode {
	p := new(NotFoundErrorCode)
	*p = x
	return p
}

func (x NotFoundErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NotFoundErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_openfga_v1_errors_ignore_proto_enumTypes[4].Descriptor()
}

func (NotFoundErrorCode) Type() protoreflect.EnumType {
	return &file_openfga_v1_errors_ignore_proto_enumTypes[4]
}

func (x NotFoundErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NotFoundErrorCode.Descriptor instead.
func (NotFoundErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_openfga_v1_errors_ignore_proto_rawDescGZIP(), []int{4}
}

type ValidationErrorMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          ErrorCode              `protobuf:"varint,1,opt,name=code,proto3,enum=openfga.v1.ErrorCode" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidationErrorMessageResponse) Reset() {
	*x = ValidationErrorMessageResponse{}
	mi := &file_openfga_v1_errors_ignore_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidationErrorMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidationErrorMessageResponse) ProtoMessage() {}

func (x *ValidationErrorMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_openfga_v1_errors_ignore_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidationErrorMessageResponse.ProtoReflect.Descriptor instead.
func (*ValidationErrorMessageResponse) Descriptor() ([]byte, []int) {
	return file_openfga_v1_errors_ignore_proto_rawDescGZIP(), []int{0}
}

func (x *ValidationErrorMessageResponse) GetCode() ErrorCode {
	if x != nil {
		return x.Code
	}
	return ErrorCode_no_error
}

func (x *ValidationErrorMessageResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UnauthenticatedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          ErrorCode              `protobuf:"varint,1,opt,name=code,proto3,enum=openfga.v1.ErrorCode" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnauthenticatedResponse) Reset() {
	*x = UnauthenticatedResponse{}
	mi := &file_openfga_v1_errors_ignore_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnauthenticatedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnauthenticatedResponse) ProtoMessage() {}

func (x *UnauthenticatedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_openfga_v1_errors_ignore_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnauthenticatedResponse.ProtoReflect.Descriptor instead.
func (*UnauthenticatedResponse) Descriptor() ([]byte, []int) {
	return file_openfga_v1_errors_ignore_proto_rawDescGZIP(), []int{1}
}

func (x *UnauthenticatedResponse) GetCode() ErrorCode {
	if x != nil {
		return x.Code
	}
	return ErrorCode_no_error
}

func (x *UnauthenticatedResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UnprocessableContentMessageResponse struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	Code          UnprocessableContentErrorCode `protobuf:"varint,1,opt,name=code,proto3,enum=openfga.v1.UnprocessableContentErrorCode" json:"code,omitempty"`
	Message       string                        `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnprocessableContentMessageResponse) Reset() {
	*x = UnprocessableContentMessageResponse{}
	mi := &file_openfga_v1_errors_ignore_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnprocessableContentMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnprocessableContentMessageResponse) ProtoMessage() {}

func (x *UnprocessableContentMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_openfga_v1_errors_ignore_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnprocessableContentMessageResponse.ProtoReflect.Descriptor instead.
func (*UnprocessableContentMessageResponse) Descriptor() ([]byte, []int) {
	return file_openfga_v1_errors_ignore_proto_rawDescGZIP(), []int{2}
}

func (x *UnprocessableContentMessageResponse) GetCode() UnprocessableContentErrorCode {
	if x != nil {
		return x.Code
	}
	return UnprocessableContentErrorCode_no_throttled_error_code
}

func (x *UnprocessableContentMessageResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type InternalErrorMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          InternalErrorCode      `protobuf:"varint,1,opt,name=code,proto3,enum=openfga.v1.InternalErrorCode" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InternalErrorMessageResponse) Reset() {
	*x = InternalErrorMessageResponse{}
	mi := &file_openfga_v1_errors_ignore_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InternalErrorMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InternalErrorMessageResponse) ProtoMessage() {}

func (x *InternalErrorMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_openfga_v1_errors_ignore_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InternalErrorMessageResponse.ProtoReflect.Descriptor instead.
func (*InternalErrorMessageResponse) Descriptor() ([]byte, []int) {
	return file_openfga_v1_errors_ignore_proto_rawDescGZIP(), []int{3}
}

func (x *InternalErrorMessageResponse) GetCode() InternalErrorCode {
	if x != nil {
		return x.Code
	}
	return InternalErrorCode_no_internal_error
}

func (x *InternalErrorMessageResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type PathUnknownErrorMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          NotFoundErrorCode      `protobuf:"varint,1,opt,name=code,proto3,enum=openfga.v1.NotFoundErrorCode" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PathUnknownErrorMessageResponse) Reset() {
	*x = PathUnknownErrorMessageResponse{}
	mi := &file_openfga_v1_errors_ignore_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PathUnknownErrorMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PathUnknownErrorMessageResponse) ProtoMessage() {}

func (x *PathUnknownErrorMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_openfga_v1_errors_ignore_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PathUnknownErrorMessageResponse.ProtoReflect.Descriptor instead.
func (*PathUnknownErrorMessageResponse) Descriptor() ([]byte, []int) {
	return file_openfga_v1_errors_ignore_proto_rawDescGZIP(), []int{4}
}

func (x *PathUnknownErrorMessageResponse) GetCode() NotFoundErrorCode {
	if x != nil {
		return x.Code
	}
	return NotFoundErrorCode_no_not_found_error
}

func (x *PathUnknownErrorMessageResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type AbortedMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AbortedMessageResponse) Reset() {
	*x = AbortedMessageResponse{}
	mi := &file_openfga_v1_errors_ignore_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AbortedMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbortedMessageResponse) ProtoMessage() {}

func (x *AbortedMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_openfga_v1_errors_ignore_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbortedMessageResponse.ProtoReflect.Descriptor instead.
func (*AbortedMessageResponse) Descriptor() ([]byte, []int) {
	return file_openfga_v1_errors_ignore_proto_rawDescGZIP(), []int{5}
}

func (x *AbortedMessageResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *AbortedMessageResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ErrorMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorMessageRequest) Reset() {
	*x = ErrorMessageRequest{}
	mi := &file_openfga_v1_errors_ignore_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorMessageRequest) ProtoMessage() {}

func (x *ErrorMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_openfga_v1_errors_ignore_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorMessageRequest.ProtoReflect.Descriptor instead.
func (*ErrorMessageRequest) Descriptor() ([]byte, []int) {
	return file_openfga_v1_errors_ignore_proto_rawDescGZIP(), []int{6}
}

type ForbiddenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          AuthErrorCode          `protobuf:"varint,1,opt,name=code,proto3,enum=openfga.v1.AuthErrorCode" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForbiddenResponse) Reset() {
	*x = ForbiddenResponse{}
	mi := &file_openfga_v1_errors_ignore_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForbiddenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForbiddenResponse) ProtoMessage() {}

func (x *ForbiddenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_openfga_v1_errors_ignore_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForbiddenResponse.ProtoReflect.Descriptor instead.
func (*ForbiddenResponse) Descriptor() ([]byte, []int) {
	return file_openfga_v1_errors_ignore_proto_rawDescGZIP(), []int{7}
}

func (x *ForbiddenResponse) GetCode() AuthErrorCode {
	if x != nil {
		return x.Code
	}
	return AuthErrorCode_no_auth_error
}

func (x *ForbiddenResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_openfga_v1_errors_ignore_proto protoreflect.FileDescriptor

const file_openfga_v1_errors_ignore_proto_rawDesc = "" +
	"\n" +
	"\x1eopenfga/v1/errors_ignore.proto\x12\n" +
	"openfga.v1\x1a.protoc-gen-openapiv2/options/annotations.proto\"\xad\x01\n" +
	"\x1eValidationErrorMessageResponse\x12)\n" +
	"\x04code\x18\x01 \x01(\x0e2\x15.openfga.v1.ErrorCodeR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage:F\x92AC2A{\"code\":\"validation_error\", \"message\":\"Generic validation error\"}\"\x9c\x01\n" +
	"\x17UnauthenticatedResponse\x12)\n" +
	"\x04code\x18\x01 \x01(\x0e2\x15.openfga.v1.ErrorCodeR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage:<\x92A927{\"code\":\"unauthenticated\", \"message\":\"unauthenticated\"}\"\xe1\x01\n" +
	"#UnprocessableContentMessageResponse\x12=\n" +
	"\x04code\x18\x01 \x01(\x0e2).openfga.v1.UnprocessableContentErrorCodeR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage:a\x92A^2\\{\"code\":\"throttled_timeout_error\", \"message\":\"timeout due to throttling on complex request\"}\"\xae\x01\n" +
	"\x1cInternalErrorMessageResponse\x121\n" +
	"\x04code\x18\x01 \x01(\x0e2\x1d.openfga.v1.InternalErrorCodeR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage:A\x92A>2<{\"code\":\"internal_error\", \"message\":\"Internal Server Error\"}\"\xb4\x01\n" +
	"\x1fPathUnknownErrorMessageResponse\x121\n" +
	"\x04code\x18\x01 \x01(\x0e2\x1d.openfga.v1.NotFoundErrorCodeR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage:D\x92AA2?{\"code\":\"undefined_endpoint\", \"message\":\"Endpoint not enabled\"}\"|\n" +
	"\x16AbortedMessageResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage:4\x92A12/{\"code\":\"10\", \"message\":\"transaction conflict\"}\"\x15\n" +
	"\x13ErrorMessageRequest\"\xba\x01\n" +
	"\x11ForbiddenResponse\x12-\n" +
	"\x04code\x18\x01 \x01(\x0e2\x19.openfga.v1.AuthErrorCodeR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage:\\\x92AY2W{\"code\":\"forbidden\", \"message\":\"the principal is not authorized to perform the action\"}*\x85\x02\n" +
	"\rAuthErrorCode\x12\x11\n" +
	"\rno_auth_error\x10\x00\x12 \n" +
	"\x1bauth_failed_invalid_subject\x10\xe9\a\x12!\n" +
	"\x1cauth_failed_invalid_audience\x10\xea\a\x12\x1f\n" +
	"\x1aauth_failed_invalid_issuer\x10\xeb\a\x12\x13\n" +
	"\x0einvalid_claims\x10\xec\a\x12%\n" +
	" auth_failed_invalid_bearer_token\x10\xed\a\x12\x19\n" +
	"\x14bearer_token_missing\x10\xf2\a\x12\x14\n" +
	"\x0funauthenticated\x10\xdc\v\x12\x0e\n" +
	"\tforbidden\x10\xc0\f*\xa3\f\n" +
	"\tErrorCode\x12\f\n" +
	"\bno_error\x10\x00\x12\x15\n" +
	"\x10validation_error\x10\xd0\x0f\x12\"\n" +
	"\x1dauthorization_model_not_found\x10\xd1\x0f\x12/\n" +
	"*authorization_model_resolution_too_complex\x10\xd2\x0f\x12\x18\n" +
	"\x13invalid_write_input\x10\xd3\x0f\x121\n" +
	",cannot_allow_duplicate_tuples_in_one_request\x10\xd4\x0f\x120\n" +
	"+cannot_allow_duplicate_types_in_one_request\x10\xd5\x0f\x125\n" +
	"0cannot_allow_multiple_references_to_one_relation\x10\xd6\x0f\x12\x1f\n" +
	"\x1ainvalid_continuation_token\x10\xd7\x0f\x12\x16\n" +
	"\x11invalid_tuple_set\x10\xd8\x0f\x12\x18\n" +
	"\x13invalid_check_input\x10\xd9\x0f\x12\x19\n" +
	"\x14invalid_expand_input\x10\xda\x0f\x12\x19\n" +
	"\x14unsupported_user_set\x10\xdb\x0f\x12\x1a\n" +
	"\x15invalid_object_format\x10\xdc\x0f\x12&\n" +
	"!write_failed_due_to_invalid_input\x10\xe1\x0f\x12-\n" +
	"(authorization_model_assertions_not_found\x10\xe2\x0f\x12)\n" +
	"$latest_authorization_model_not_found\x10\xe4\x0f\x12\x13\n" +
	"\x0etype_not_found\x10\xe5\x0f\x12\x17\n" +
	"\x12relation_not_found\x10\xe6\x0f\x12\x1e\n" +
	"\x19empty_relation_definition\x10\xe7\x0f\x12\x11\n" +
	"\finvalid_user\x10\xe9\x0f\x12\x12\n" +
	"\rinvalid_tuple\x10\xeb\x0f\x12\x15\n" +
	"\x10unknown_relation\x10\xec\x0f\x12\x1c\n" +
	"\x17store_id_invalid_length\x10\xee\x0f\x12\x1e\n" +
	"\x19assertions_too_many_items\x10\xf1\x0f\x12\x10\n" +
	"\vid_too_long\x10\xf2\x0f\x12$\n" +
	"\x1fauthorization_model_id_too_long\x10\xf4\x0f\x12\"\n" +
	"\x1dtuple_key_value_not_specified\x10\xf5\x0f\x12)\n" +
	"$tuple_keys_too_many_or_too_few_items\x10\xf6\x0f\x12\x16\n" +
	"\x11page_size_invalid\x10\xf7\x0f\x12\x18\n" +
	"\x13param_missing_value\x10\xf8\x0f\x12\"\n" +
	"\x1ddifference_base_missing_value\x10\xf9\x0f\x12 \n" +
	"\x1bsubtract_base_missing_value\x10\xfa\x0f\x12\x14\n" +
	"\x0fobject_too_long\x10\xfb\x0f\x12\x16\n" +
	"\x11relation_too_long\x10\xfc\x0f\x12#\n" +
	"\x1etype_definitions_too_few_items\x10\xfd\x0f\x12\x18\n" +
	"\x13type_invalid_length\x10\xfe\x0f\x12\x19\n" +
	"\x14type_invalid_pattern\x10\xff\x0f\x12\x1c\n" +
	"\x17relations_too_few_items\x10\x80\x10\x12\x17\n" +
	"\x12relations_too_long\x10\x81\x10\x12\x1e\n" +
	"\x19relations_invalid_pattern\x10\x82\x10\x12\x1b\n" +
	"\x16object_invalid_pattern\x10\x83\x10\x122\n" +
	"-query_string_type_continuation_token_mismatch\x10\x84\x10\x12\x1a\n" +
	"\x15exceeded_entity_limit\x10\x85\x10\x12\x1d\n" +
	"\x18invalid_contextual_tuple\x10\x86\x10\x12\x1f\n" +
	"\x1aduplicate_contextual_tuple\x10\x87\x10\x12 \n" +
	"\x1binvalid_authorization_model\x10\x88\x10\x12\x1f\n" +
	"\x1aunsupported_schema_version\x10\x89\x10\x12\x0e\n" +
	"\tcancelled\x10\x8a\x10\x12\x17\n" +
	"\x12invalid_start_time\x10\x8b\x10*Z\n" +
	"\x1dUnprocessableContentErrorCode\x12\x1b\n" +
	"\x17no_throttled_error_code\x10\x00\x12\x1c\n" +
	"\x17throttled_timeout_error\x10\xac\x1b*\xe2\x01\n" +
	"\x11InternalErrorCode\x12\x15\n" +
	"\x11no_internal_error\x10\x00\x12\x13\n" +
	"\x0einternal_error\x10\xa0\x1f\x12\x16\n" +
	"\x11deadline_exceeded\x10\xa4\x1f\x12\x13\n" +
	"\x0ealready_exists\x10\xa5\x1f\x12\x17\n" +
	"\x12resource_exhausted\x10\xa6\x1f\x12\x18\n" +
	"\x13failed_precondition\x10\xa7\x1f\x12\f\n" +
	"\aaborted\x10\xa8\x1f\x12\x11\n" +
	"\fout_of_range\x10\xa9\x1f\x12\x10\n" +
	"\vunavailable\x10\xaa\x1f\x12\x0e\n" +
	"\tdata_loss\x10\xab\x1f*q\n" +
	"\x11NotFoundErrorCode\x12\x16\n" +
	"\x12no_not_found_error\x10\x00\x12\x17\n" +
	"\x12undefined_endpoint\x10\x88'\x12\x17\n" +
	"\x12store_id_not_found\x10\x8a'\x12\x12\n" +
	"\runimplemented\x10\x8c'B\x9f\x01\n" +
	"\x0ecom.openfga.v1B\x11ErrorsIgnoreProtoP\x01Z1github.com/openfga/api/proto/openfga/v1;openfgav1\xa2\x02\x03OXX\xaa\x02\n" +
	"Openfga.V1\xca\x02\n" +
	"Openfga\\V1\xe2\x02\x16Openfga\\V1\\GPBMetadata\xea\x02\vOpenfga::V1b\x06proto3"

var (
	file_openfga_v1_errors_ignore_proto_rawDescOnce sync.Once
	file_openfga_v1_errors_ignore_proto_rawDescData []byte
)

func file_openfga_v1_errors_ignore_proto_rawDescGZIP() []byte {
	file_openfga_v1_errors_ignore_proto_rawDescOnce.Do(func() {
		file_openfga_v1_errors_ignore_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_openfga_v1_errors_ignore_proto_rawDesc), len(file_openfga_v1_errors_ignore_proto_rawDesc)))
	})
	return file_openfga_v1_errors_ignore_proto_rawDescData
}

var file_openfga_v1_errors_ignore_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_openfga_v1_errors_ignore_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_openfga_v1_errors_ignore_proto_goTypes = []any{
	(AuthErrorCode)(0),                          // 0: openfga.v1.AuthErrorCode
	(ErrorCode)(0),                              // 1: openfga.v1.ErrorCode
	(UnprocessableContentErrorCode)(0),          // 2: openfga.v1.UnprocessableContentErrorCode
	(InternalErrorCode)(0),                      // 3: openfga.v1.InternalErrorCode
	(NotFoundErrorCode)(0),                      // 4: openfga.v1.NotFoundErrorCode
	(*ValidationErrorMessageResponse)(nil),      // 5: openfga.v1.ValidationErrorMessageResponse
	(*UnauthenticatedResponse)(nil),             // 6: openfga.v1.UnauthenticatedResponse
	(*UnprocessableContentMessageResponse)(nil), // 7: openfga.v1.UnprocessableContentMessageResponse
	(*InternalErrorMessageResponse)(nil),        // 8: openfga.v1.InternalErrorMessageResponse
	(*PathUnknownErrorMessageResponse)(nil),     // 9: openfga.v1.PathUnknownErrorMessageResponse
	(*AbortedMessageResponse)(nil),              // 10: openfga.v1.AbortedMessageResponse
	(*ErrorMessageRequest)(nil),                 // 11: openfga.v1.ErrorMessageRequest
	(*ForbiddenResponse)(nil),                   // 12: openfga.v1.ForbiddenResponse
}
var file_openfga_v1_errors_ignore_proto_depIdxs = []int32{
	1, // 0: openfga.v1.ValidationErrorMessageResponse.code:type_name -> openfga.v1.ErrorCode
	1, // 1: openfga.v1.UnauthenticatedResponse.code:type_name -> openfga.v1.ErrorCode
	2, // 2: openfga.v1.UnprocessableContentMessageResponse.code:type_name -> openfga.v1.UnprocessableContentErrorCode
	3, // 3: openfga.v1.InternalErrorMessageResponse.code:type_name -> openfga.v1.InternalErrorCode
	4, // 4: openfga.v1.PathUnknownErrorMessageResponse.code:type_name -> openfga.v1.NotFoundErrorCode
	0, // 5: openfga.v1.ForbiddenResponse.code:type_name -> openfga.v1.AuthErrorCode
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_openfga_v1_errors_ignore_proto_init() }
func file_openfga_v1_errors_ignore_proto_init() {
	if File_openfga_v1_errors_ignore_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_openfga_v1_errors_ignore_proto_rawDesc), len(file_openfga_v1_errors_ignore_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_openfga_v1_errors_ignore_proto_goTypes,
		DependencyIndexes: file_openfga_v1_errors_ignore_proto_depIdxs,
		EnumInfos:         file_openfga_v1_errors_ignore_proto_enumTypes,
		MessageInfos:      file_openfga_v1_errors_ignore_proto_msgTypes,
	}.Build()
	File_openfga_v1_errors_ignore_proto = out.File
	file_openfga_v1_errors_ignore_proto_goTypes = nil
	file_openfga_v1_errors_ignore_proto_depIdxs = nil
}
