// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: openfga/v1/openfga_service_consistency.proto

package openfgav1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Controls the consistency preferences when calling the query APIs.
type ConsistencyPreference int32

const (
	// Default if not set. Behavior will be the same as MINIMIZE_LATENCY.
	ConsistencyPreference_UNSPECIFIED ConsistencyPreference = 0
	// Minimize latency at the potential expense of lower consistency.
	ConsistencyPreference_MINIMIZE_LATENCY ConsistencyPreference = 100
	// Prefer higher consistency, at the potential expense of increased latency.
	ConsistencyPreference_HIGHER_CONSISTENCY ConsistencyPreference = 200
)

// Enum value maps for ConsistencyPreference.
var (
	ConsistencyPreference_name = map[int32]string{
		0:   "UNSPECIFIED",
		100: "MINIMIZE_LATENCY",
		200: "HIGHER_CONSISTENCY",
	}
	ConsistencyPreference_value = map[string]int32{
		"UNSPECIFIED":        0,
		"MINIMIZE_LATENCY":   100,
		"HIGHER_CONSISTENCY": 200,
	}
)

func (x ConsistencyPreference) Enum() *ConsistencyPreference {
	p := new(ConsistencyPreference)
	*p = x
	return p
}

func (x ConsistencyPreference) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConsistencyPreference) Descriptor() protoreflect.EnumDescriptor {
	return file_openfga_v1_openfga_service_consistency_proto_enumTypes[0].Descriptor()
}

func (ConsistencyPreference) Type() protoreflect.EnumType {
	return &file_openfga_v1_openfga_service_consistency_proto_enumTypes[0]
}

func (x ConsistencyPreference) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConsistencyPreference.Descriptor instead.
func (ConsistencyPreference) EnumDescriptor() ([]byte, []int) {
	return file_openfga_v1_openfga_service_consistency_proto_rawDescGZIP(), []int{0}
}

var File_openfga_v1_openfga_service_consistency_proto protoreflect.FileDescriptor

const file_openfga_v1_openfga_service_consistency_proto_rawDesc = "" +
	"\n" +
	",openfga/v1/openfga_service_consistency.proto\x12\n" +
	"openfga.v1*W\n" +
	"\x15ConsistencyPreference\x12\x0f\n" +
	"\vUNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10MINIMIZE_LATENCY\x10d\x12\x17\n" +
	"\x12HIGHER_CONSISTENCY\x10\xc8\x01B\xac\x01\n" +
	"\x0ecom.openfga.v1B\x1eOpenfgaServiceConsistencyProtoP\x01Z1github.com/openfga/api/proto/openfga/v1;openfgav1\xa2\x02\x03OXX\xaa\x02\n" +
	"Openfga.V1\xca\x02\n" +
	"Openfga\\V1\xe2\x02\x16Openfga\\V1\\GPBMetadata\xea\x02\vOpenfga::V1b\x06proto3"

var (
	file_openfga_v1_openfga_service_consistency_proto_rawDescOnce sync.Once
	file_openfga_v1_openfga_service_consistency_proto_rawDescData []byte
)

func file_openfga_v1_openfga_service_consistency_proto_rawDescGZIP() []byte {
	file_openfga_v1_openfga_service_consistency_proto_rawDescOnce.Do(func() {
		file_openfga_v1_openfga_service_consistency_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_openfga_v1_openfga_service_consistency_proto_rawDesc), len(file_openfga_v1_openfga_service_consistency_proto_rawDesc)))
	})
	return file_openfga_v1_openfga_service_consistency_proto_rawDescData
}

var file_openfga_v1_openfga_service_consistency_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_openfga_v1_openfga_service_consistency_proto_goTypes = []any{
	(ConsistencyPreference)(0), // 0: openfga.v1.ConsistencyPreference
}
var file_openfga_v1_openfga_service_consistency_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_openfga_v1_openfga_service_consistency_proto_init() }
func file_openfga_v1_openfga_service_consistency_proto_init() {
	if File_openfga_v1_openfga_service_consistency_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_openfga_v1_openfga_service_consistency_proto_rawDesc), len(file_openfga_v1_openfga_service_consistency_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_openfga_v1_openfga_service_consistency_proto_goTypes,
		DependencyIndexes: file_openfga_v1_openfga_service_consistency_proto_depIdxs,
		EnumInfos:         file_openfga_v1_openfga_service_consistency_proto_enumTypes,
	}.Build()
	File_openfga_v1_openfga_service_consistency_proto = out.File
	file_openfga_v1_openfga_service_consistency_proto_goTypes = nil
	file_openfga_v1_openfga_service_consistency_proto_depIdxs = nil
}
