// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: openfga/v1/openfga.proto

package openfgav1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// buf:lint:ignore ENUM_ZERO_VALUE_SUFFIX
type TupleOperation int32

const (
	TupleOperation_TUPLE_OPERATION_WRITE  TupleOperation = 0
	TupleOperation_TUPLE_OPERATION_DELETE TupleOperation = 1
)

// Enum value maps for TupleOperation.
var (
	TupleOperation_name = map[int32]string{
		0: "TUPLE_OPERATION_WRITE",
		1: "TUPLE_OPERATION_DELETE",
	}
	TupleOperation_value = map[string]int32{
		"TUPLE_OPERATION_WRITE":  0,
		"TUPLE_OPERATION_DELETE": 1,
	}
)

func (x TupleOperation) Enum() *TupleOperation {
	p := new(TupleOperation)
	*p = x
	return p
}

func (x TupleOperation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TupleOperation) Descriptor() protoreflect.EnumDescriptor {
	return file_openfga_v1_openfga_proto_enumTypes[0].Descriptor()
}

func (TupleOperation) Type() protoreflect.EnumType {
	return &file_openfga_v1_openfga_proto_enumTypes[0]
}

func (x TupleOperation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TupleOperation.Descriptor instead.
func (TupleOperation) EnumDescriptor() ([]byte, []int) {
	return file_openfga_v1_openfga_proto_rawDescGZIP(), []int{0}
}

// Object represents an OpenFGA Object.
//
// An Object is composed of a type and identifier (e.g. 'document:1')
//
// See https://openfga.dev/docs/concepts#what-is-an-object
type Object struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Object) Reset() {
	*x = Object{}
	mi := &file_openfga_v1_openfga_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Object) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Object) ProtoMessage() {}

func (x *Object) ProtoReflect() protoreflect.Message {
	mi := &file_openfga_v1_openfga_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Object.ProtoReflect.Descriptor instead.
func (*Object) Descriptor() ([]byte, []int) {
	return file_openfga_v1_openfga_proto_rawDescGZIP(), []int{0}
}

func (x *Object) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Object) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// User.
//
// Represents any possible value for a user (subject or principal). Can be a:
// - Specific user object e.g.: 'user:will', 'folder:marketing', 'org:contoso', ...)
// - Specific userset (e.g. 'group:engineering#member')
// - Public-typed wildcard (e.g. 'user:*')
//
// See https://openfga.dev/docs/concepts#what-is-a-user
type User struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to User:
	//
	//	*User_Object
	//	*User_Userset
	//	*User_Wildcard
	User          isUser_User `protobuf_oneof:"user"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_openfga_v1_openfga_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_openfga_v1_openfga_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_openfga_v1_openfga_proto_rawDescGZIP(), []int{1}
}

func (x *User) GetUser() isUser_User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *User) GetObject() *Object {
	if x != nil {
		if x, ok := x.User.(*User_Object); ok {
			return x.Object
		}
	}
	return nil
}

func (x *User) GetUserset() *UsersetUser {
	if x != nil {
		if x, ok := x.User.(*User_Userset); ok {
			return x.Userset
		}
	}
	return nil
}

func (x *User) GetWildcard() *TypedWildcard {
	if x != nil {
		if x, ok := x.User.(*User_Wildcard); ok {
			return x.Wildcard
		}
	}
	return nil
}

type isUser_User interface {
	isUser_User()
}

type User_Object struct {
	Object *Object `protobuf:"bytes,1,opt,name=object,proto3,oneof"`
}

type User_Userset struct {
	Userset *UsersetUser `protobuf:"bytes,2,opt,name=userset,proto3,oneof"`
}

type User_Wildcard struct {
	Wildcard *TypedWildcard `protobuf:"bytes,3,opt,name=wildcard,proto3,oneof"`
}

func (*User_Object) isUser_User() {}

func (*User_Userset) isUser_User() {}

func (*User_Wildcard) isUser_User() {}

// Userset.
//
// A set or group of users, represented in the `<type>:<id>#<relation>` format
//
// `group:fga#member` represents all members of group FGA, not to be confused by `group:fga` which represents the group itself as a specific object.
//
// See: https://openfga.dev/docs/modeling/building-blocks/usersets#what-is-a-userset
type UsersetUser struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Relation      string                 `protobuf:"bytes,3,opt,name=relation,proto3" json:"relation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsersetUser) Reset() {
	*x = UsersetUser{}
	mi := &file_openfga_v1_openfga_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsersetUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsersetUser) ProtoMessage() {}

func (x *UsersetUser) ProtoReflect() protoreflect.Message {
	mi := &file_openfga_v1_openfga_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsersetUser.ProtoReflect.Descriptor instead.
func (*UsersetUser) Descriptor() ([]byte, []int) {
	return file_openfga_v1_openfga_proto_rawDescGZIP(), []int{2}
}

func (x *UsersetUser) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *UsersetUser) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UsersetUser) GetRelation() string {
	if x != nil {
		return x.Relation
	}
	return ""
}

type RelationshipCondition struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A reference (by name) of the relationship condition defined in the authorization model.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Additional context/data to persist along with the condition.
	// The keys must match the parameters defined by the condition, and the value types must
	// match the parameter type definitions.
	Context       *structpb.Struct `protobuf:"bytes,2,opt,name=context,proto3" json:"context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelationshipCondition) Reset() {
	*x = RelationshipCondition{}
	mi := &file_openfga_v1_openfga_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelationshipCondition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelationshipCondition) ProtoMessage() {}

func (x *RelationshipCondition) ProtoReflect() protoreflect.Message {
	mi := &file_openfga_v1_openfga_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelationshipCondition.ProtoReflect.Descriptor instead.
func (*RelationshipCondition) Descriptor() ([]byte, []int) {
	return file_openfga_v1_openfga_proto_rawDescGZIP(), []int{3}
}

func (x *RelationshipCondition) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RelationshipCondition) GetContext() *structpb.Struct {
	if x != nil {
		return x.Context
	}
	return nil
}

type TupleKeyWithoutCondition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          string                 `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Relation      string                 `protobuf:"bytes,2,opt,name=relation,proto3" json:"relation,omitempty"`
	Object        string                 `protobuf:"bytes,3,opt,name=object,proto3" json:"object,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TupleKeyWithoutCondition) Reset() {
	*x = TupleKeyWithoutCondition{}
	mi := &file_openfga_v1_openfga_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TupleKeyWithoutCondition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TupleKeyWithoutCondition) ProtoMessage() {}

func (x *TupleKeyWithoutCondition) ProtoReflect() protoreflect.Message {
	mi := &file_openfga_v1_openfga_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TupleKeyWithoutCondition.ProtoReflect.Descriptor instead.
func (*TupleKeyWithoutCondition) Descriptor() ([]byte, []int) {
	return file_openfga_v1_openfga_proto_rawDescGZIP(), []int{4}
}

func (x *TupleKeyWithoutCondition) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *TupleKeyWithoutCondition) GetRelation() string {
	if x != nil {
		return x.Relation
	}
	return ""
}

func (x *TupleKeyWithoutCondition) GetObject() string {
	if x != nil {
		return x.Object
	}
	return ""
}

// Type bound public access.
//
// Normally represented using the `<type>:*` syntax
//
// `employee:*` represents every object of type `employee`, including those not currently present in the system
//
// See https://openfga.dev/docs/concepts#what-is-type-bound-public-access
type TypedWildcard struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TypedWildcard) Reset() {
	*x = TypedWildcard{}
	mi := &file_openfga_v1_openfga_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TypedWildcard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TypedWildcard) ProtoMessage() {}

func (x *TypedWildcard) ProtoReflect() protoreflect.Message {
	mi := &file_openfga_v1_openfga_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TypedWildcard.ProtoReflect.Descriptor instead.
func (*TypedWildcard) Descriptor() ([]byte, []int) {
	return file_openfga_v1_openfga_proto_rawDescGZIP(), []int{5}
}

func (x *TypedWildcard) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type TupleKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          string                 `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Relation      string                 `protobuf:"bytes,2,opt,name=relation,proto3" json:"relation,omitempty"`
	Object        string                 `protobuf:"bytes,3,opt,name=object,proto3" json:"object,omitempty"`
	Condition     *RelationshipCondition `protobuf:"bytes,4,opt,name=condition,proto3" json:"condition,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TupleKey) Reset() {
	*x = TupleKey{}
	mi := &file_openfga_v1_openfga_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TupleKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TupleKey) ProtoMessage() {}

func (x *TupleKey) ProtoReflect() protoreflect.Message {
	mi := &file_openfga_v1_openfga_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TupleKey.ProtoReflect.Descriptor instead.
func (*TupleKey) Descriptor() ([]byte, []int) {
	return file_openfga_v1_openfga_proto_rawDescGZIP(), []int{6}
}

func (x *TupleKey) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *TupleKey) GetRelation() string {
	if x != nil {
		return x.Relation
	}
	return ""
}

func (x *TupleKey) GetObject() string {
	if x != nil {
		return x.Object
	}
	return ""
}

func (x *TupleKey) GetCondition() *RelationshipCondition {
	if x != nil {
		return x.Condition
	}
	return nil
}

type Tuple struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           *TupleKey              `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tuple) Reset() {
	*x = Tuple{}
	mi := &file_openfga_v1_openfga_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tuple) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tuple) ProtoMessage() {}

func (x *Tuple) ProtoReflect() protoreflect.Message {
	mi := &file_openfga_v1_openfga_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tuple.ProtoReflect.Descriptor instead.
func (*Tuple) Descriptor() ([]byte, []int) {
	return file_openfga_v1_openfga_proto_rawDescGZIP(), []int{7}
}

func (x *Tuple) GetKey() *TupleKey {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *Tuple) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type TupleKeys struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TupleKeys     []*TupleKey            `protobuf:"bytes,1,rep,name=tuple_keys,proto3" json:"tuple_keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TupleKeys) Reset() {
	*x = TupleKeys{}
	mi := &file_openfga_v1_openfga_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TupleKeys) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TupleKeys) ProtoMessage() {}

func (x *TupleKeys) ProtoReflect() protoreflect.Message {
	mi := &file_openfga_v1_openfga_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TupleKeys.ProtoReflect.Descriptor instead.
func (*TupleKeys) Descriptor() ([]byte, []int) {
	return file_openfga_v1_openfga_proto_rawDescGZIP(), []int{8}
}

func (x *TupleKeys) GetTupleKeys() []*TupleKey {
	if x != nil {
		return x.TupleKeys
	}
	return nil
}

type ContextualTupleKeys struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TupleKeys     []*TupleKey            `protobuf:"bytes,1,rep,name=tuple_keys,proto3" json:"tuple_keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContextualTupleKeys) Reset() {
	*x = ContextualTupleKeys{}
	mi := &file_openfga_v1_openfga_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContextualTupleKeys) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContextualTupleKeys) ProtoMessage() {}

func (x *ContextualTupleKeys) ProtoReflect() protoreflect.Message {
	mi := &file_openfga_v1_openfga_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContextualTupleKeys.ProtoReflect.Descriptor instead.
func (*ContextualTupleKeys) Descriptor() ([]byte, []int) {
	return file_openfga_v1_openfga_proto_rawDescGZIP(), []int{9}
}

func (x *ContextualTupleKeys) GetTupleKeys() []*TupleKey {
	if x != nil {
		return x.TupleKeys
	}
	return nil
}

// A UsersetTree contains the result of an Expansion.
type UsersetTree struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Root          *UsersetTree_Node      `protobuf:"bytes,1,opt,name=root,proto3" json:"root,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsersetTree) Reset() {
	*x = UsersetTree{}
	mi := &file_openfga_v1_openfga_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsersetTree) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsersetTree) ProtoMessage() {}

func (x *UsersetTree) ProtoReflect() protoreflect.Message {
	mi := &file_openfga_v1_openfga_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsersetTree.ProtoReflect.Descriptor instead.
func (*UsersetTree) Descriptor() ([]byte, []int) {
	return file_openfga_v1_openfga_proto_rawDescGZIP(), []int{10}
}

func (x *UsersetTree) GetRoot() *UsersetTree_Node {
	if x != nil {
		return x.Root
	}
	return nil
}

type TupleChange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TupleKey      *TupleKey              `protobuf:"bytes,1,opt,name=tuple_key,proto3" json:"tuple_key,omitempty"`
	Operation     TupleOperation         `protobuf:"varint,2,opt,name=operation,proto3,enum=openfga.v1.TupleOperation" json:"operation,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TupleChange) Reset() {
	*x = TupleChange{}
	mi := &file_openfga_v1_openfga_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TupleChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TupleChange) ProtoMessage() {}

func (x *TupleChange) ProtoReflect() protoreflect.Message {
	mi := &file_openfga_v1_openfga_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TupleChange.ProtoReflect.Descriptor instead.
func (*TupleChange) Descriptor() ([]byte, []int) {
	return file_openfga_v1_openfga_proto_rawDescGZIP(), []int{11}
}

func (x *TupleChange) GetTupleKey() *TupleKey {
	if x != nil {
		return x.TupleKey
	}
	return nil
}

func (x *TupleChange) GetOperation() TupleOperation {
	if x != nil {
		return x.Operation
	}
	return TupleOperation_TUPLE_OPERATION_WRITE
}

func (x *TupleChange) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type Store struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=updated_at,proto3" json:"updated_at,omitempty"`
	DeletedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=deleted_at,proto3" json:"deleted_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Store) Reset() {
	*x = Store{}
	mi := &file_openfga_v1_openfga_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Store) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Store) ProtoMessage() {}

func (x *Store) ProtoReflect() protoreflect.Message {
	mi := &file_openfga_v1_openfga_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Store.ProtoReflect.Descriptor instead.
func (*Store) Descriptor() ([]byte, []int) {
	return file_openfga_v1_openfga_proto_rawDescGZIP(), []int{12}
}

func (x *Store) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Store) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Store) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Store) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Store) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

type UserTypeFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Relation      string                 `protobuf:"bytes,2,opt,name=relation,proto3" json:"relation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserTypeFilter) Reset() {
	*x = UserTypeFilter{}
	mi := &file_openfga_v1_openfga_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserTypeFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserTypeFilter) ProtoMessage() {}

func (x *UserTypeFilter) ProtoReflect() protoreflect.Message {
	mi := &file_openfga_v1_openfga_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserTypeFilter.ProtoReflect.Descriptor instead.
func (*UserTypeFilter) Descriptor() ([]byte, []int) {
	return file_openfga_v1_openfga_proto_rawDescGZIP(), []int{13}
}

func (x *UserTypeFilter) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *UserTypeFilter) GetRelation() string {
	if x != nil {
		return x.Relation
	}
	return ""
}

// A leaf node contains either
//   - a set of users (which may be individual users, or usersets
//     referencing other relations)
//   - a computed node, which is the result of a computed userset
//     value in the authorization model
//   - a tupleToUserset nodes, containing the result of expanding
//     a tupleToUserset value in a authorization model.
type UsersetTree_Leaf struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*UsersetTree_Leaf_Users
	//	*UsersetTree_Leaf_Computed
	//	*UsersetTree_Leaf_TupleToUserset
	Value         isUsersetTree_Leaf_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsersetTree_Leaf) Reset() {
	*x = UsersetTree_Leaf{}
	mi := &file_openfga_v1_openfga_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsersetTree_Leaf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsersetTree_Leaf) ProtoMessage() {}

func (x *UsersetTree_Leaf) ProtoReflect() protoreflect.Message {
	mi := &file_openfga_v1_openfga_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsersetTree_Leaf.ProtoReflect.Descriptor instead.
func (*UsersetTree_Leaf) Descriptor() ([]byte, []int) {
	return file_openfga_v1_openfga_proto_rawDescGZIP(), []int{10, 0}
}

func (x *UsersetTree_Leaf) GetValue() isUsersetTree_Leaf_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *UsersetTree_Leaf) GetUsers() *UsersetTree_Users {
	if x != nil {
		if x, ok := x.Value.(*UsersetTree_Leaf_Users); ok {
			return x.Users
		}
	}
	return nil
}

func (x *UsersetTree_Leaf) GetComputed() *UsersetTree_Computed {
	if x != nil {
		if x, ok := x.Value.(*UsersetTree_Leaf_Computed); ok {
			return x.Computed
		}
	}
	return nil
}

func (x *UsersetTree_Leaf) GetTupleToUserset() *UsersetTree_TupleToUserset {
	if x != nil {
		if x, ok := x.Value.(*UsersetTree_Leaf_TupleToUserset); ok {
			return x.TupleToUserset
		}
	}
	return nil
}

type isUsersetTree_Leaf_Value interface {
	isUsersetTree_Leaf_Value()
}

type UsersetTree_Leaf_Users struct {
	Users *UsersetTree_Users `protobuf:"bytes,1,opt,name=users,proto3,oneof"`
}

type UsersetTree_Leaf_Computed struct {
	Computed *UsersetTree_Computed `protobuf:"bytes,2,opt,name=computed,proto3,oneof"`
}

type UsersetTree_Leaf_TupleToUserset struct {
	TupleToUserset *UsersetTree_TupleToUserset `protobuf:"bytes,3,opt,name=tuple_to_userset,json=tupleToUserset,proto3,oneof"`
}

func (*UsersetTree_Leaf_Users) isUsersetTree_Leaf_Value() {}

func (*UsersetTree_Leaf_Computed) isUsersetTree_Leaf_Value() {}

func (*UsersetTree_Leaf_TupleToUserset) isUsersetTree_Leaf_Value() {}

type UsersetTree_Nodes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*UsersetTree_Node    `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsersetTree_Nodes) Reset() {
	*x = UsersetTree_Nodes{}
	mi := &file_openfga_v1_openfga_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsersetTree_Nodes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsersetTree_Nodes) ProtoMessage() {}

func (x *UsersetTree_Nodes) ProtoReflect() protoreflect.Message {
	mi := &file_openfga_v1_openfga_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsersetTree_Nodes.ProtoReflect.Descriptor instead.
func (*UsersetTree_Nodes) Descriptor() ([]byte, []int) {
	return file_openfga_v1_openfga_proto_rawDescGZIP(), []int{10, 1}
}

func (x *UsersetTree_Nodes) GetNodes() []*UsersetTree_Node {
	if x != nil {
		return x.Nodes
	}
	return nil
}

type UsersetTree_Users struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []string               `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsersetTree_Users) Reset() {
	*x = UsersetTree_Users{}
	mi := &file_openfga_v1_openfga_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsersetTree_Users) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsersetTree_Users) ProtoMessage() {}

func (x *UsersetTree_Users) ProtoReflect() protoreflect.Message {
	mi := &file_openfga_v1_openfga_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsersetTree_Users.ProtoReflect.Descriptor instead.
func (*UsersetTree_Users) Descriptor() ([]byte, []int) {
	return file_openfga_v1_openfga_proto_rawDescGZIP(), []int{10, 2}
}

func (x *UsersetTree_Users) GetUsers() []string {
	if x != nil {
		return x.Users
	}
	return nil
}

type UsersetTree_Computed struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Userset       string                 `protobuf:"bytes,1,opt,name=userset,proto3" json:"userset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsersetTree_Computed) Reset() {
	*x = UsersetTree_Computed{}
	mi := &file_openfga_v1_openfga_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsersetTree_Computed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsersetTree_Computed) ProtoMessage() {}

func (x *UsersetTree_Computed) ProtoReflect() protoreflect.Message {
	mi := &file_openfga_v1_openfga_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsersetTree_Computed.ProtoReflect.Descriptor instead.
func (*UsersetTree_Computed) Descriptor() ([]byte, []int) {
	return file_openfga_v1_openfga_proto_rawDescGZIP(), []int{10, 3}
}

func (x *UsersetTree_Computed) GetUserset() string {
	if x != nil {
		return x.Userset
	}
	return ""
}

type UsersetTree_TupleToUserset struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Tupleset      string                  `protobuf:"bytes,1,opt,name=tupleset,proto3" json:"tupleset,omitempty"`
	Computed      []*UsersetTree_Computed `protobuf:"bytes,2,rep,name=computed,proto3" json:"computed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsersetTree_TupleToUserset) Reset() {
	*x = UsersetTree_TupleToUserset{}
	mi := &file_openfga_v1_openfga_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsersetTree_TupleToUserset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsersetTree_TupleToUserset) ProtoMessage() {}

func (x *UsersetTree_TupleToUserset) ProtoReflect() protoreflect.Message {
	mi := &file_openfga_v1_openfga_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsersetTree_TupleToUserset.ProtoReflect.Descriptor instead.
func (*UsersetTree_TupleToUserset) Descriptor() ([]byte, []int) {
	return file_openfga_v1_openfga_proto_rawDescGZIP(), []int{10, 4}
}

func (x *UsersetTree_TupleToUserset) GetTupleset() string {
	if x != nil {
		return x.Tupleset
	}
	return ""
}

func (x *UsersetTree_TupleToUserset) GetComputed() []*UsersetTree_Computed {
	if x != nil {
		return x.Computed
	}
	return nil
}

type UsersetTree_Difference struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *UsersetTree_Node      `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Subtract      *UsersetTree_Node      `protobuf:"bytes,2,opt,name=subtract,proto3" json:"subtract,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsersetTree_Difference) Reset() {
	*x = UsersetTree_Difference{}
	mi := &file_openfga_v1_openfga_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsersetTree_Difference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsersetTree_Difference) ProtoMessage() {}

func (x *UsersetTree_Difference) ProtoReflect() protoreflect.Message {
	mi := &file_openfga_v1_openfga_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsersetTree_Difference.ProtoReflect.Descriptor instead.
func (*UsersetTree_Difference) Descriptor() ([]byte, []int) {
	return file_openfga_v1_openfga_proto_rawDescGZIP(), []int{10, 5}
}

func (x *UsersetTree_Difference) GetBase() *UsersetTree_Node {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *UsersetTree_Difference) GetSubtract() *UsersetTree_Node {
	if x != nil {
		return x.Subtract
	}
	return nil
}

type UsersetTree_Node struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Types that are valid to be assigned to Value:
	//
	//	*UsersetTree_Node_Leaf
	//	*UsersetTree_Node_Difference
	//	*UsersetTree_Node_Union
	//	*UsersetTree_Node_Intersection
	Value         isUsersetTree_Node_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsersetTree_Node) Reset() {
	*x = UsersetTree_Node{}
	mi := &file_openfga_v1_openfga_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsersetTree_Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsersetTree_Node) ProtoMessage() {}

func (x *UsersetTree_Node) ProtoReflect() protoreflect.Message {
	mi := &file_openfga_v1_openfga_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsersetTree_Node.ProtoReflect.Descriptor instead.
func (*UsersetTree_Node) Descriptor() ([]byte, []int) {
	return file_openfga_v1_openfga_proto_rawDescGZIP(), []int{10, 6}
}

func (x *UsersetTree_Node) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UsersetTree_Node) GetValue() isUsersetTree_Node_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *UsersetTree_Node) GetLeaf() *UsersetTree_Leaf {
	if x != nil {
		if x, ok := x.Value.(*UsersetTree_Node_Leaf); ok {
			return x.Leaf
		}
	}
	return nil
}

func (x *UsersetTree_Node) GetDifference() *UsersetTree_Difference {
	if x != nil {
		if x, ok := x.Value.(*UsersetTree_Node_Difference); ok {
			return x.Difference
		}
	}
	return nil
}

func (x *UsersetTree_Node) GetUnion() *UsersetTree_Nodes {
	if x != nil {
		if x, ok := x.Value.(*UsersetTree_Node_Union); ok {
			return x.Union
		}
	}
	return nil
}

func (x *UsersetTree_Node) GetIntersection() *UsersetTree_Nodes {
	if x != nil {
		if x, ok := x.Value.(*UsersetTree_Node_Intersection); ok {
			return x.Intersection
		}
	}
	return nil
}

type isUsersetTree_Node_Value interface {
	isUsersetTree_Node_Value()
}

type UsersetTree_Node_Leaf struct {
	Leaf *UsersetTree_Leaf `protobuf:"bytes,2,opt,name=leaf,proto3,oneof"`
}

type UsersetTree_Node_Difference struct {
	Difference *UsersetTree_Difference `protobuf:"bytes,5,opt,name=difference,proto3,oneof"`
}

type UsersetTree_Node_Union struct {
	Union *UsersetTree_Nodes `protobuf:"bytes,6,opt,name=union,proto3,oneof"`
}

type UsersetTree_Node_Intersection struct {
	Intersection *UsersetTree_Nodes `protobuf:"bytes,7,opt,name=intersection,proto3,oneof"`
}

func (*UsersetTree_Node_Leaf) isUsersetTree_Node_Value() {}

func (*UsersetTree_Node_Difference) isUsersetTree_Node_Value() {}

func (*UsersetTree_Node_Union) isUsersetTree_Node_Value() {}

func (*UsersetTree_Node_Intersection) isUsersetTree_Node_Value() {}

var File_openfga_v1_openfga_proto protoreflect.FileDescriptor

const file_openfga_v1_openfga_proto_rawDesc = "" +
	"\n" +
	"\x18openfga/v1/openfga.proto\x12\n" +
	"openfga.v1\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\x1a\x17validate/validate.proto\"\x9e\x01\n" +
	"\x06Object\x12A\n" +
	"\x04type\x18\x01 \x01(\tB-\x92A\fJ\n" +
	"\"document\"\xe0A\x02\xfaB\x18r\x162\x11^[^:#@\\s]{1,254}$\xd0\x01\x00R\x04type\x12Q\n" +
	"\x02id\x18\x02 \x01(\tBA\x92A(J&\"0bcdf6fa-a6aa-4730-a8eb-9cf172ff16d9\"\xe0A\x02\xfaB\x10r\x0e2\t[^#:\\s]+$\xd0\x01\x00R\x02id\"\xaa\x01\n" +
	"\x04User\x12,\n" +
	"\x06object\x18\x01 \x01(\v2\x12.openfga.v1.ObjectH\x00R\x06object\x123\n" +
	"\auserset\x18\x02 \x01(\v2\x17.openfga.v1.UsersetUserH\x00R\auserset\x127\n" +
	"\bwildcard\x18\x03 \x01(\v2\x19.openfga.v1.TypedWildcardH\x00R\bwildcardB\x06\n" +
	"\x04user\"\xc7\x01\n" +
	"\vUsersetUser\x12>\n" +
	"\x04type\x18\x01 \x01(\tB*\x92A\tJ\a\"group\"\xe0A\x02\xfaB\x18r\x162\x11^[^:#@\\s]{1,254}$\xd0\x01\x00R\x04type\x120\n" +
	"\x02id\x18\x02 \x01(\tB \x92A\aJ\x05\"fga\"\xe0A\x02\xfaB\x10r\x0e2\t[^#:\\s]+$\xd0\x01\x00R\x02id\x12F\n" +
	"\brelation\x18\x03 \x01(\tB*\x92A\n" +
	"J\b\"member\"\xe0A\x02\xfaB\x17r\x152\x10^[^:#@\\s]{1,50}$\xd0\x01\x01R\brelation\"\x8f\x01\n" +
	"\x15RelationshipCondition\x12C\n" +
	"\x04name\x18\x01 \x01(\tB/\x92A\x11J\f\"condition1\"x\x80\x02\xe0A\x02\xfaB\x15r\x132\x0e^[^\\s]{2,256}$\xd0\x01\x00R\x04name\x121\n" +
	"\acontext\x18\x02 \x01(\v2\x17.google.protobuf.StructR\acontext\"\xeb\x01\n" +
	"\x18TupleKeyWithoutCondition\x122\n" +
	"\x04user\x18\x01 \x01(\tB\x1e\x92A\x10J\v\"user:anne\"x\x80\x04\xe0A\x02\xfaB\x05r\x03(\x80\x04R\x04user\x12H\n" +
	"\brelation\x18\x02 \x01(\tB,\x92A\fJ\b\"reader\"x2\xe0A\x02\xfaB\x17r\x152\x10^[^:#@\\s]{1,50}$\xd0\x01\x01R\brelation\x12Q\n" +
	"\x06object\x18\x03 \x01(\tB9\x92A\x1bJ\x16\"document:2021-budget\"x\x80\x02\xe0A\x02\xfaB\x15r\x132\x0e^[^\\s]{2,256}$\xd0\x01\x01R\x06object\"R\n" +
	"\rTypedWildcard\x12A\n" +
	"\x04type\x18\x01 \x01(\tB-\x92A\fJ\n" +
	"\"employee\"\xe0A\x02\xfaB\x18r\x162\x11^[^:#@\\s]{1,254}$\xd0\x01\x00R\x04type\"\x9f\x02\n" +
	"\bTupleKey\x125\n" +
	"\x04user\x18\x01 \x01(\tB!\x92A\x10J\v\"user:anne\"x\x80\x04\xe0A\x02\xfaB\br\x06(\x80\x04\xd0\x01\x00R\x04user\x12H\n" +
	"\brelation\x18\x02 \x01(\tB,\x92A\fJ\b\"reader\"x2\xe0A\x02\xfaB\x17r\x152\x10^[^:#@\\s]{1,50}$\xd0\x01\x01R\brelation\x12Q\n" +
	"\x06object\x18\x03 \x01(\tB9\x92A\x1bJ\x16\"document:2021-budget\"x\x80\x02\xe0A\x02\xfaB\x15r\x132\x0e^[^\\s]{2,256}$\xd0\x01\x01R\x06object\x12?\n" +
	"\tcondition\x18\x04 \x01(\v2!.openfga.v1.RelationshipConditionR\tcondition\"{\n" +
	"\x05Tuple\x123\n" +
	"\x03key\x18\x01 \x01(\v2\x14.openfga.v1.TupleKeyB\v\xe0A\x02\xfaB\x05\x8a\x01\x02\x10\x01R\x03key\x12=\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampB\x03\xe0A\x02R\ttimestamp\"T\n" +
	"\tTupleKeys\x12G\n" +
	"\n" +
	"tuple_keys\x18\x01 \x03(\v2\x14.openfga.v1.TupleKeyB\x11\x92A\x03\xa8\x01\x01\xe0A\x02\xfaB\x05\x92\x01\x02\b\x01R\n" +
	"tuple_keys\"^\n" +
	"\x13ContextualTupleKeys\x12G\n" +
	"\n" +
	"tuple_keys\x18\x01 \x03(\v2\x14.openfga.v1.TupleKeyB\x11\x92A\x03\xa0\x01d\xe0A\x02\xfaB\x05\x92\x01\x02\x10dR\n" +
	"tuple_keys\"\xe9\a\n" +
	"\vUsersetTree\x120\n" +
	"\x04root\x18\x01 \x01(\v2\x1c.openfga.v1.UsersetTree.NodeR\x04root\x1a\xda\x01\n" +
	"\x04Leaf\x125\n" +
	"\x05users\x18\x01 \x01(\v2\x1d.openfga.v1.UsersetTree.UsersH\x00R\x05users\x12>\n" +
	"\bcomputed\x18\x02 \x01(\v2 .openfga.v1.UsersetTree.ComputedH\x00R\bcomputed\x12R\n" +
	"\x10tuple_to_userset\x18\x03 \x01(\v2&.openfga.v1.UsersetTree.TupleToUsersetH\x00R\x0etupleToUsersetB\a\n" +
	"\x05value\x1a@\n" +
	"\x05Nodes\x127\n" +
	"\x05nodes\x18\x01 \x03(\v2\x1c.openfga.v1.UsersetTree.NodeB\x03\xe0A\x02R\x05nodes\x1a\"\n" +
	"\x05Users\x12\x19\n" +
	"\x05users\x18\x01 \x03(\tB\x03\xe0A\x02R\x05users\x1a1\n" +
	"\bComputed\x12%\n" +
	"\auserset\x18\x01 \x01(\tB\v\xe0A\x02\xfaB\x05r\x03\xd0\x01\x00R\auserset\x1a|\n" +
	"\x0eTupleToUserset\x12'\n" +
	"\btupleset\x18\x01 \x01(\tB\v\xe0A\x02\xfaB\x05r\x03\xd0\x01\x00R\btupleset\x12A\n" +
	"\bcomputed\x18\x02 \x03(\v2 .openfga.v1.UsersetTree.ComputedB\x03\xe0A\x02R\bcomputed\x1a\x92\x01\n" +
	"\n" +
	"Difference\x12=\n" +
	"\x04base\x18\x01 \x01(\v2\x1c.openfga.v1.UsersetTree.NodeB\v\xe0A\x02\xfaB\x05\x8a\x01\x02\x10\x01R\x04base\x12E\n" +
	"\bsubtract\x18\x02 \x01(\v2\x1c.openfga.v1.UsersetTree.NodeB\v\xe0A\x02\xfaB\x05\x8a\x01\x02\x10\x01R\bsubtract\x1a\x9e\x02\n" +
	"\x04Node\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tB\x03\xe0A\x02R\x04name\x122\n" +
	"\x04leaf\x18\x02 \x01(\v2\x1c.openfga.v1.UsersetTree.LeafH\x00R\x04leaf\x12D\n" +
	"\n" +
	"difference\x18\x05 \x01(\v2\".openfga.v1.UsersetTree.DifferenceH\x00R\n" +
	"difference\x125\n" +
	"\x05union\x18\x06 \x01(\v2\x1d.openfga.v1.UsersetTree.NodesH\x00R\x05union\x12C\n" +
	"\fintersection\x18\a \x01(\v2\x1d.openfga.v1.UsersetTree.NodesH\x00R\fintersectionB\a\n" +
	"\x05value\"\xd4\x01\n" +
	"\vTupleChange\x12?\n" +
	"\ttuple_key\x18\x01 \x01(\v2\x14.openfga.v1.TupleKeyB\v\xe0A\x02\xfaB\x05\x8a\x01\x02\x10\x01R\ttuple_key\x12E\n" +
	"\toperation\x18\x02 \x01(\x0e2\x1a.openfga.v1.TupleOperationB\v\xe0A\x02\xfaB\x05\x82\x01\x02\x10\x01R\toperation\x12=\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampB\x03\xe0A\x02R\ttimestamp\"\x83\x02\n" +
	"\x05Store\x12\x1b\n" +
	"\x02id\x18\x01 \x01(\tB\v\xe0A\x02\xfaB\x05r\x03\xd0\x01\x00R\x02id\x12\x1f\n" +
	"\x04name\x18\x02 \x01(\tB\v\xe0A\x02\xfaB\x05r\x03\xd0\x01\x00R\x04name\x12?\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampB\x03\xe0A\x02R\n" +
	"created_at\x12?\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampB\x03\xe0A\x02R\n" +
	"updated_at\x12:\n" +
	"\n" +
	"deleted_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"deleted_at\"\x95\x01\n" +
	"\x0eUserTypeFilter\x12>\n" +
	"\x04type\x18\x01 \x01(\tB*\x92A\tJ\a\"group\"\xe0A\x02\xfaB\x18r\x162\x11^[^:#@\\s]{1,254}$\xd0\x01\x00R\x04type\x12C\n" +
	"\brelation\x18\x02 \x01(\tB'\x92A\n" +
	"J\b\"member\"\xfaB\x17r\x152\x10^[^:#@\\s]{1,50}$\xd0\x01\x01R\brelation*G\n" +
	"\x0eTupleOperation\x12\x19\n" +
	"\x15TUPLE_OPERATION_WRITE\x10\x00\x12\x1a\n" +
	"\x16TUPLE_OPERATION_DELETE\x10\x01B\x9a\x01\n" +
	"\x0ecom.openfga.v1B\fOpenfgaProtoP\x01Z1github.com/openfga/api/proto/openfga/v1;openfgav1\xa2\x02\x03OXX\xaa\x02\n" +
	"Openfga.V1\xca\x02\n" +
	"Openfga\\V1\xe2\x02\x16Openfga\\V1\\GPBMetadata\xea\x02\vOpenfga::V1b\x06proto3"

var (
	file_openfga_v1_openfga_proto_rawDescOnce sync.Once
	file_openfga_v1_openfga_proto_rawDescData []byte
)

func file_openfga_v1_openfga_proto_rawDescGZIP() []byte {
	file_openfga_v1_openfga_proto_rawDescOnce.Do(func() {
		file_openfga_v1_openfga_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_openfga_v1_openfga_proto_rawDesc), len(file_openfga_v1_openfga_proto_rawDesc)))
	})
	return file_openfga_v1_openfga_proto_rawDescData
}

var file_openfga_v1_openfga_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_openfga_v1_openfga_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_openfga_v1_openfga_proto_goTypes = []any{
	(TupleOperation)(0),                // 0: openfga.v1.TupleOperation
	(*Object)(nil),                     // 1: openfga.v1.Object
	(*User)(nil),                       // 2: openfga.v1.User
	(*UsersetUser)(nil),                // 3: openfga.v1.UsersetUser
	(*RelationshipCondition)(nil),      // 4: openfga.v1.RelationshipCondition
	(*TupleKeyWithoutCondition)(nil),   // 5: openfga.v1.TupleKeyWithoutCondition
	(*TypedWildcard)(nil),              // 6: openfga.v1.TypedWildcard
	(*TupleKey)(nil),                   // 7: openfga.v1.TupleKey
	(*Tuple)(nil),                      // 8: openfga.v1.Tuple
	(*TupleKeys)(nil),                  // 9: openfga.v1.TupleKeys
	(*ContextualTupleKeys)(nil),        // 10: openfga.v1.ContextualTupleKeys
	(*UsersetTree)(nil),                // 11: openfga.v1.UsersetTree
	(*TupleChange)(nil),                // 12: openfga.v1.TupleChange
	(*Store)(nil),                      // 13: openfga.v1.Store
	(*UserTypeFilter)(nil),             // 14: openfga.v1.UserTypeFilter
	(*UsersetTree_Leaf)(nil),           // 15: openfga.v1.UsersetTree.Leaf
	(*UsersetTree_Nodes)(nil),          // 16: openfga.v1.UsersetTree.Nodes
	(*UsersetTree_Users)(nil),          // 17: openfga.v1.UsersetTree.Users
	(*UsersetTree_Computed)(nil),       // 18: openfga.v1.UsersetTree.Computed
	(*UsersetTree_TupleToUserset)(nil), // 19: openfga.v1.UsersetTree.TupleToUserset
	(*UsersetTree_Difference)(nil),     // 20: openfga.v1.UsersetTree.Difference
	(*UsersetTree_Node)(nil),           // 21: openfga.v1.UsersetTree.Node
	(*structpb.Struct)(nil),            // 22: google.protobuf.Struct
	(*timestamppb.Timestamp)(nil),      // 23: google.protobuf.Timestamp
}
var file_openfga_v1_openfga_proto_depIdxs = []int32{
	1,  // 0: openfga.v1.User.object:type_name -> openfga.v1.Object
	3,  // 1: openfga.v1.User.userset:type_name -> openfga.v1.UsersetUser
	6,  // 2: openfga.v1.User.wildcard:type_name -> openfga.v1.TypedWildcard
	22, // 3: openfga.v1.RelationshipCondition.context:type_name -> google.protobuf.Struct
	4,  // 4: openfga.v1.TupleKey.condition:type_name -> openfga.v1.RelationshipCondition
	7,  // 5: openfga.v1.Tuple.key:type_name -> openfga.v1.TupleKey
	23, // 6: openfga.v1.Tuple.timestamp:type_name -> google.protobuf.Timestamp
	7,  // 7: openfga.v1.TupleKeys.tuple_keys:type_name -> openfga.v1.TupleKey
	7,  // 8: openfga.v1.ContextualTupleKeys.tuple_keys:type_name -> openfga.v1.TupleKey
	21, // 9: openfga.v1.UsersetTree.root:type_name -> openfga.v1.UsersetTree.Node
	7,  // 10: openfga.v1.TupleChange.tuple_key:type_name -> openfga.v1.TupleKey
	0,  // 11: openfga.v1.TupleChange.operation:type_name -> openfga.v1.TupleOperation
	23, // 12: openfga.v1.TupleChange.timestamp:type_name -> google.protobuf.Timestamp
	23, // 13: openfga.v1.Store.created_at:type_name -> google.protobuf.Timestamp
	23, // 14: openfga.v1.Store.updated_at:type_name -> google.protobuf.Timestamp
	23, // 15: openfga.v1.Store.deleted_at:type_name -> google.protobuf.Timestamp
	17, // 16: openfga.v1.UsersetTree.Leaf.users:type_name -> openfga.v1.UsersetTree.Users
	18, // 17: openfga.v1.UsersetTree.Leaf.computed:type_name -> openfga.v1.UsersetTree.Computed
	19, // 18: openfga.v1.UsersetTree.Leaf.tuple_to_userset:type_name -> openfga.v1.UsersetTree.TupleToUserset
	21, // 19: openfga.v1.UsersetTree.Nodes.nodes:type_name -> openfga.v1.UsersetTree.Node
	18, // 20: openfga.v1.UsersetTree.TupleToUserset.computed:type_name -> openfga.v1.UsersetTree.Computed
	21, // 21: openfga.v1.UsersetTree.Difference.base:type_name -> openfga.v1.UsersetTree.Node
	21, // 22: openfga.v1.UsersetTree.Difference.subtract:type_name -> openfga.v1.UsersetTree.Node
	15, // 23: openfga.v1.UsersetTree.Node.leaf:type_name -> openfga.v1.UsersetTree.Leaf
	20, // 24: openfga.v1.UsersetTree.Node.difference:type_name -> openfga.v1.UsersetTree.Difference
	16, // 25: openfga.v1.UsersetTree.Node.union:type_name -> openfga.v1.UsersetTree.Nodes
	16, // 26: openfga.v1.UsersetTree.Node.intersection:type_name -> openfga.v1.UsersetTree.Nodes
	27, // [27:27] is the sub-list for method output_type
	27, // [27:27] is the sub-list for method input_type
	27, // [27:27] is the sub-list for extension type_name
	27, // [27:27] is the sub-list for extension extendee
	0,  // [0:27] is the sub-list for field type_name
}

func init() { file_openfga_v1_openfga_proto_init() }
func file_openfga_v1_openfga_proto_init() {
	if File_openfga_v1_openfga_proto != nil {
		return
	}
	file_openfga_v1_openfga_proto_msgTypes[1].OneofWrappers = []any{
		(*User_Object)(nil),
		(*User_Userset)(nil),
		(*User_Wildcard)(nil),
	}
	file_openfga_v1_openfga_proto_msgTypes[14].OneofWrappers = []any{
		(*UsersetTree_Leaf_Users)(nil),
		(*UsersetTree_Leaf_Computed)(nil),
		(*UsersetTree_Leaf_TupleToUserset)(nil),
	}
	file_openfga_v1_openfga_proto_msgTypes[20].OneofWrappers = []any{
		(*UsersetTree_Node_Leaf)(nil),
		(*UsersetTree_Node_Difference)(nil),
		(*UsersetTree_Node_Union)(nil),
		(*UsersetTree_Node_Intersection)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_openfga_v1_openfga_proto_rawDesc), len(file_openfga_v1_openfga_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_openfga_v1_openfga_proto_goTypes,
		DependencyIndexes: file_openfga_v1_openfga_proto_depIdxs,
		EnumInfos:         file_openfga_v1_openfga_proto_enumTypes,
		MessageInfos:      file_openfga_v1_openfga_proto_msgTypes,
	}.Build()
	File_openfga_v1_openfga_proto = out.File
	file_openfga_v1_openfga_proto_goTypes = nil
	file_openfga_v1_openfga_proto_depIdxs = nil
}
