// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: openfga/v1/openapi.proto

package openfgav1

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_openfga_v1_openapi_proto protoreflect.FileDescriptor

const file_openfga_v1_openapi_proto_rawDesc = "" +
	"\n" +
	"\x18openfga/v1/openapi.proto\x12\n" +
	"openfga.v1\x1a.protoc-gen-openapiv2/options/annotations.protoB\xc3\b\x92A\xa5\a\x12\x80\x02\n" +
	"\aOpenFGA\x12uA high performance and flexible authorization/permission engine built for developers and inspired by Google Zanzibar.\"5\n" +
	"\aOpenFGA\x12\x13https://openfga.dev\x1a\x15community@openfga.dev*B\n" +
	"\n" +
	"Apache-2.0\x124https://github.com/openfga/openfga/blob/main/LICENSE2\x031.x*\x01\x022\x10application/json:\x10application/jsonR]\n" +
	"\x03400\x12V\n" +
	"$Request failed due to invalid input.\x12.\n" +
	",\x1a*.openfga.v1.ValidationErrorMessageResponseRD\n" +
	"\x03401\x12=\n" +
	"\x12Not authenticated.\x12'\n" +
	"%\x1a#.openfga.v1.UnauthenticatedResponseR6\n" +
	"\x03403\x12/\n" +
	"\n" +
	"Forbidden.\x12!\n" +
	"\x1f\x1a\x1d.openfga.v1.ForbiddenResponseR_\n" +
	"\x03404\x12X\n" +
	"%Request failed due to incorrect path.\x12/\n" +
	"-\x1a+.openfga.v1.PathUnknownErrorMessageResponseR`\n" +
	"\x03409\x12Y\n" +
	"/Request was aborted due a transaction conflict.\x12&\n" +
	"$\x1a\".openfga.v1.AbortedMessageResponseRt\n" +
	"\x03422\x12m\n" +
	"6Request timed out due to excessive request throttling.\x123\n" +
	"1\x1a/.openfga.v1.UnprocessableContentMessageResponseRc\n" +
	"\x03500\x12\\\n" +
	",Request failed due to internal server error.\x12,\n" +
	"*\x1a(.openfga.v1.InternalErrorMessageResponse\n" +
	"\x0ecom.openfga.v1B\fOpenapiProtoP\x01Z1github.com/openfga/api/proto/openfga/v1;openfgav1\xa2\x02\x03OXX\xaa\x02\n" +
	"Openfga.V1\xca\x02\n" +
	"Openfga\\V1\xe2\x02\x16Openfga\\V1\\GPBMetadata\xea\x02\vOpenfga::V1b\x06proto3"

var file_openfga_v1_openapi_proto_goTypes = []any{}
var file_openfga_v1_openapi_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_openfga_v1_openapi_proto_init() }
func file_openfga_v1_openapi_proto_init() {
	if File_openfga_v1_openapi_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_openfga_v1_openapi_proto_rawDesc), len(file_openfga_v1_openapi_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_openfga_v1_openapi_proto_goTypes,
		DependencyIndexes: file_openfga_v1_openapi_proto_depIdxs,
	}.Build()
	File_openfga_v1_openapi_proto = out.File
	file_openfga_v1_openapi_proto_goTypes = nil
	file_openfga_v1_openapi_proto_depIdxs = nil
}
