// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: authzen/v1/authzen_service.proto

package authzenv1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Enum for evaluation semantics
type EvaluationsSemantic int32

const (
	// Execute all evaluations (default behavior)
	EvaluationsSemantic_execute_all EvaluationsSemantic = 0
	// Stop on first deny decision
	EvaluationsSemantic_deny_on_first_deny EvaluationsSemantic = 1
	// Stop on first permit decision
	EvaluationsSemantic_permit_on_first_permit EvaluationsSemantic = 2
)

// Enum value maps for EvaluationsSemantic.
var (
	EvaluationsSemantic_name = map[int32]string{
		0: "execute_all",
		1: "deny_on_first_deny",
		2: "permit_on_first_permit",
	}
	EvaluationsSemantic_value = map[string]int32{
		"execute_all":            0,
		"deny_on_first_deny":     1,
		"permit_on_first_permit": 2,
	}
)

func (x EvaluationsSemantic) Enum() *EvaluationsSemantic {
	p := new(EvaluationsSemantic)
	*p = x
	return p
}

func (x EvaluationsSemantic) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EvaluationsSemantic) Descriptor() protoreflect.EnumDescriptor {
	return file_authzen_v1_authzen_service_proto_enumTypes[0].Descriptor()
}

func (EvaluationsSemantic) Type() protoreflect.EnumType {
	return &file_authzen_v1_authzen_service_proto_enumTypes[0]
}

func (x EvaluationsSemantic) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EvaluationsSemantic.Descriptor instead.
func (EvaluationsSemantic) EnumDescriptor() ([]byte, []int) {
	return file_authzen_v1_authzen_service_proto_rawDescGZIP(), []int{0}
}

type EvaluationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StoreId       string                 `protobuf:"bytes,1,opt,name=store_id,proto3" json:"store_id,omitempty"`
	Subject       *Subject               `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	Resource      *Resource              `protobuf:"bytes,3,opt,name=resource,proto3" json:"resource,omitempty"`
	Action        *Action                `protobuf:"bytes,4,opt,name=action,proto3" json:"action,omitempty"`
	Context       *structpb.Struct       `protobuf:"bytes,5,opt,name=context,proto3,oneof" json:"context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvaluationRequest) Reset() {
	*x = EvaluationRequest{}
	mi := &file_authzen_v1_authzen_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluationRequest) ProtoMessage() {}

func (x *EvaluationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authzen_v1_authzen_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluationRequest.ProtoReflect.Descriptor instead.
func (*EvaluationRequest) Descriptor() ([]byte, []int) {
	return file_authzen_v1_authzen_service_proto_rawDescGZIP(), []int{0}
}

func (x *EvaluationRequest) GetStoreId() string {
	if x != nil {
		return x.StoreId
	}
	return ""
}

func (x *EvaluationRequest) GetSubject() *Subject {
	if x != nil {
		return x.Subject
	}
	return nil
}

func (x *EvaluationRequest) GetResource() *Resource {
	if x != nil {
		return x.Resource
	}
	return nil
}

func (x *EvaluationRequest) GetAction() *Action {
	if x != nil {
		return x.Action
	}
	return nil
}

func (x *EvaluationRequest) GetContext() *structpb.Struct {
	if x != nil {
		return x.Context
	}
	return nil
}

type EvaluationsItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subject       *Subject               `protobuf:"bytes,1,opt,name=subject,proto3,oneof" json:"subject,omitempty"`
	Resource      *Resource              `protobuf:"bytes,2,opt,name=resource,proto3,oneof" json:"resource,omitempty"`
	Action        *Action                `protobuf:"bytes,3,opt,name=action,proto3,oneof" json:"action,omitempty"`
	Context       *structpb.Struct       `protobuf:"bytes,4,opt,name=context,proto3,oneof" json:"context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvaluationsItemRequest) Reset() {
	*x = EvaluationsItemRequest{}
	mi := &file_authzen_v1_authzen_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluationsItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluationsItemRequest) ProtoMessage() {}

func (x *EvaluationsItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authzen_v1_authzen_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluationsItemRequest.ProtoReflect.Descriptor instead.
func (*EvaluationsItemRequest) Descriptor() ([]byte, []int) {
	return file_authzen_v1_authzen_service_proto_rawDescGZIP(), []int{1}
}

func (x *EvaluationsItemRequest) GetSubject() *Subject {
	if x != nil {
		return x.Subject
	}
	return nil
}

func (x *EvaluationsItemRequest) GetResource() *Resource {
	if x != nil {
		return x.Resource
	}
	return nil
}

func (x *EvaluationsItemRequest) GetAction() *Action {
	if x != nil {
		return x.Action
	}
	return nil
}

func (x *EvaluationsItemRequest) GetContext() *structpb.Struct {
	if x != nil {
		return x.Context
	}
	return nil
}

type Subject struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Properties    *structpb.Struct       `protobuf:"bytes,3,opt,name=properties,proto3,oneof" json:"properties,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Subject) Reset() {
	*x = Subject{}
	mi := &file_authzen_v1_authzen_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Subject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Subject) ProtoMessage() {}

func (x *Subject) ProtoReflect() protoreflect.Message {
	mi := &file_authzen_v1_authzen_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Subject.ProtoReflect.Descriptor instead.
func (*Subject) Descriptor() ([]byte, []int) {
	return file_authzen_v1_authzen_service_proto_rawDescGZIP(), []int{2}
}

func (x *Subject) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Subject) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Subject) GetProperties() *structpb.Struct {
	if x != nil {
		return x.Properties
	}
	return nil
}

// SubjectFilter is used for search operations where only type is required
type SubjectFilter struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Type  string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// Optional subject id. If present in Subject Search, it is ignored per AuthZEN spec.
	Id            *string          `protobuf:"bytes,2,opt,name=id,proto3,oneof" json:"id,omitempty"`
	Properties    *structpb.Struct `protobuf:"bytes,3,opt,name=properties,proto3,oneof" json:"properties,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubjectFilter) Reset() {
	*x = SubjectFilter{}
	mi := &file_authzen_v1_authzen_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubjectFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubjectFilter) ProtoMessage() {}

func (x *SubjectFilter) ProtoReflect() protoreflect.Message {
	mi := &file_authzen_v1_authzen_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubjectFilter.ProtoReflect.Descriptor instead.
func (*SubjectFilter) Descriptor() ([]byte, []int) {
	return file_authzen_v1_authzen_service_proto_rawDescGZIP(), []int{3}
}

func (x *SubjectFilter) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *SubjectFilter) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *SubjectFilter) GetProperties() *structpb.Struct {
	if x != nil {
		return x.Properties
	}
	return nil
}

type Resource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Properties    *structpb.Struct       `protobuf:"bytes,3,opt,name=properties,proto3,oneof" json:"properties,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resource) Reset() {
	*x = Resource{}
	mi := &file_authzen_v1_authzen_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resource) ProtoMessage() {}

func (x *Resource) ProtoReflect() protoreflect.Message {
	mi := &file_authzen_v1_authzen_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resource.ProtoReflect.Descriptor instead.
func (*Resource) Descriptor() ([]byte, []int) {
	return file_authzen_v1_authzen_service_proto_rawDescGZIP(), []int{4}
}

func (x *Resource) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Resource) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Resource) GetProperties() *structpb.Struct {
	if x != nil {
		return x.Properties
	}
	return nil
}

// ResourceFilter is used for search operations where only type is required
type ResourceFilter struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Type  string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// Optional resource id. If present in Resource Search, it is ignored per AuthZEN spec.
	Id            *string          `protobuf:"bytes,2,opt,name=id,proto3,oneof" json:"id,omitempty"`
	Properties    *structpb.Struct `protobuf:"bytes,3,opt,name=properties,proto3,oneof" json:"properties,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceFilter) Reset() {
	*x = ResourceFilter{}
	mi := &file_authzen_v1_authzen_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceFilter) ProtoMessage() {}

func (x *ResourceFilter) ProtoReflect() protoreflect.Message {
	mi := &file_authzen_v1_authzen_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceFilter.ProtoReflect.Descriptor instead.
func (*ResourceFilter) Descriptor() ([]byte, []int) {
	return file_authzen_v1_authzen_service_proto_rawDescGZIP(), []int{5}
}

func (x *ResourceFilter) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ResourceFilter) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *ResourceFilter) GetProperties() *structpb.Struct {
	if x != nil {
		return x.Properties
	}
	return nil
}

type Action struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Properties    *structpb.Struct       `protobuf:"bytes,2,opt,name=properties,proto3,oneof" json:"properties,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Action) Reset() {
	*x = Action{}
	mi := &file_authzen_v1_authzen_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Action) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Action) ProtoMessage() {}

func (x *Action) ProtoReflect() protoreflect.Message {
	mi := &file_authzen_v1_authzen_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Action.ProtoReflect.Descriptor instead.
func (*Action) Descriptor() ([]byte, []int) {
	return file_authzen_v1_authzen_service_proto_rawDescGZIP(), []int{6}
}

func (x *Action) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Action) GetProperties() *structpb.Struct {
	if x != nil {
		return x.Properties
	}
	return nil
}

type EvaluationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Decision      bool                   `protobuf:"varint,1,opt,name=decision,proto3" json:"decision,omitempty"`
	Context       *structpb.Struct       `protobuf:"bytes,2,opt,name=context,proto3,oneof" json:"context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvaluationResponse) Reset() {
	*x = EvaluationResponse{}
	mi := &file_authzen_v1_authzen_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluationResponse) ProtoMessage() {}

func (x *EvaluationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authzen_v1_authzen_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluationResponse.ProtoReflect.Descriptor instead.
func (*EvaluationResponse) Descriptor() ([]byte, []int) {
	return file_authzen_v1_authzen_service_proto_rawDescGZIP(), []int{7}
}

func (x *EvaluationResponse) GetDecision() bool {
	if x != nil {
		return x.Decision
	}
	return false
}

func (x *EvaluationResponse) GetContext() *structpb.Struct {
	if x != nil {
		return x.Context
	}
	return nil
}

type EvaluationsRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	StoreId  string                 `protobuf:"bytes,1,opt,name=store_id,proto3" json:"store_id,omitempty"`
	Subject  *Subject               `protobuf:"bytes,2,opt,name=subject,proto3,oneof" json:"subject,omitempty"`
	Action   *Action                `protobuf:"bytes,3,opt,name=action,proto3,oneof" json:"action,omitempty"`
	Resource *Resource              `protobuf:"bytes,4,opt,name=resource,proto3,oneof" json:"resource,omitempty"`
	Context  *structpb.Struct       `protobuf:"bytes,5,opt,name=context,proto3,oneof" json:"context,omitempty"`
	// Optional. If omitted or empty, behaves like a single Access Evaluation request.
	Evaluations []*EvaluationsItemRequest `protobuf:"bytes,6,rep,name=evaluations,proto3" json:"evaluations,omitempty"`
	// Options for batch evaluation semantics
	Options       *EvaluationsOptions `protobuf:"bytes,7,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvaluationsRequest) Reset() {
	*x = EvaluationsRequest{}
	mi := &file_authzen_v1_authzen_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluationsRequest) ProtoMessage() {}

func (x *EvaluationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authzen_v1_authzen_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluationsRequest.ProtoReflect.Descriptor instead.
func (*EvaluationsRequest) Descriptor() ([]byte, []int) {
	return file_authzen_v1_authzen_service_proto_rawDescGZIP(), []int{8}
}

func (x *EvaluationsRequest) GetStoreId() string {
	if x != nil {
		return x.StoreId
	}
	return ""
}

func (x *EvaluationsRequest) GetSubject() *Subject {
	if x != nil {
		return x.Subject
	}
	return nil
}

func (x *EvaluationsRequest) GetAction() *Action {
	if x != nil {
		return x.Action
	}
	return nil
}

func (x *EvaluationsRequest) GetResource() *Resource {
	if x != nil {
		return x.Resource
	}
	return nil
}

func (x *EvaluationsRequest) GetContext() *structpb.Struct {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *EvaluationsRequest) GetEvaluations() []*EvaluationsItemRequest {
	if x != nil {
		return x.Evaluations
	}
	return nil
}

func (x *EvaluationsRequest) GetOptions() *EvaluationsOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

type EvaluationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Evaluations   []*EvaluationResponse  `protobuf:"bytes,1,rep,name=evaluations,proto3" json:"evaluations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvaluationsResponse) Reset() {
	*x = EvaluationsResponse{}
	mi := &file_authzen_v1_authzen_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluationsResponse) ProtoMessage() {}

func (x *EvaluationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authzen_v1_authzen_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluationsResponse.ProtoReflect.Descriptor instead.
func (*EvaluationsResponse) Descriptor() ([]byte, []int) {
	return file_authzen_v1_authzen_service_proto_rawDescGZIP(), []int{9}
}

func (x *EvaluationsResponse) GetEvaluations() []*EvaluationResponse {
	if x != nil {
		return x.Evaluations
	}
	return nil
}

// Options for batch evaluations
type EvaluationsOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Controls how batch evaluations are processed
	EvaluationsSemantic EvaluationsSemantic `protobuf:"varint,1,opt,name=evaluations_semantic,proto3,enum=authzen.v1.EvaluationsSemantic" json:"evaluations_semantic,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *EvaluationsOptions) Reset() {
	*x = EvaluationsOptions{}
	mi := &file_authzen_v1_authzen_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluationsOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluationsOptions) ProtoMessage() {}

func (x *EvaluationsOptions) ProtoReflect() protoreflect.Message {
	mi := &file_authzen_v1_authzen_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluationsOptions.ProtoReflect.Descriptor instead.
func (*EvaluationsOptions) Descriptor() ([]byte, []int) {
	return file_authzen_v1_authzen_service_proto_rawDescGZIP(), []int{10}
}

func (x *EvaluationsOptions) GetEvaluationsSemantic() EvaluationsSemantic {
	if x != nil {
		return x.EvaluationsSemantic
	}
	return EvaluationsSemantic_execute_all
}

// Pagination request parameters for search operations
type PageRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Continuation token from previous response
	Token *string `protobuf:"bytes,1,opt,name=token,proto3,oneof" json:"token,omitempty"`
	// Maximum number of results to return (default: 50, max: 1000)
	Limit         *uint32 `protobuf:"varint,2,opt,name=limit,proto3,oneof" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageRequest) Reset() {
	*x = PageRequest{}
	mi := &file_authzen_v1_authzen_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageRequest) ProtoMessage() {}

func (x *PageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authzen_v1_authzen_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageRequest.ProtoReflect.Descriptor instead.
func (*PageRequest) Descriptor() ([]byte, []int) {
	return file_authzen_v1_authzen_service_proto_rawDescGZIP(), []int{11}
}

func (x *PageRequest) GetToken() string {
	if x != nil && x.Token != nil {
		return *x.Token
	}
	return ""
}

func (x *PageRequest) GetLimit() uint32 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

// Pagination response parameters
type PageResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Token to retrieve next page (empty if no more results)
	NextToken string `protobuf:"bytes,1,opt,name=next_token,proto3" json:"next_token,omitempty"`
	// Number of results in this page
	Count uint32 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	// Total number of results (if known, otherwise 0)
	Total         *uint32 `protobuf:"varint,3,opt,name=total,proto3,oneof" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageResponse) Reset() {
	*x = PageResponse{}
	mi := &file_authzen_v1_authzen_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageResponse) ProtoMessage() {}

func (x *PageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authzen_v1_authzen_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageResponse.ProtoReflect.Descriptor instead.
func (*PageResponse) Descriptor() ([]byte, []int) {
	return file_authzen_v1_authzen_service_proto_rawDescGZIP(), []int{12}
}

func (x *PageResponse) GetNextToken() string {
	if x != nil {
		return x.NextToken
	}
	return ""
}

func (x *PageResponse) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *PageResponse) GetTotal() uint32 {
	if x != nil && x.Total != nil {
		return *x.Total
	}
	return 0
}

// SubjectSearch request
type SubjectSearchRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	StoreId  string                 `protobuf:"bytes,1,opt,name=store_id,proto3" json:"store_id,omitempty"`
	Resource *Resource              `protobuf:"bytes,2,opt,name=resource,proto3" json:"resource,omitempty"`
	Action   *Action                `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	// REQUIRED by AuthZEN Subject Search. Subject `id` may be provided but is ignored.
	Subject       *SubjectFilter   `protobuf:"bytes,4,opt,name=subject,proto3" json:"subject,omitempty"`
	Context       *structpb.Struct `protobuf:"bytes,5,opt,name=context,proto3,oneof" json:"context,omitempty"`
	Page          *PageRequest     `protobuf:"bytes,6,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubjectSearchRequest) Reset() {
	*x = SubjectSearchRequest{}
	mi := &file_authzen_v1_authzen_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubjectSearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubjectSearchRequest) ProtoMessage() {}

func (x *SubjectSearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authzen_v1_authzen_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubjectSearchRequest.ProtoReflect.Descriptor instead.
func (*SubjectSearchRequest) Descriptor() ([]byte, []int) {
	return file_authzen_v1_authzen_service_proto_rawDescGZIP(), []int{13}
}

func (x *SubjectSearchRequest) GetStoreId() string {
	if x != nil {
		return x.StoreId
	}
	return ""
}

func (x *SubjectSearchRequest) GetResource() *Resource {
	if x != nil {
		return x.Resource
	}
	return nil
}

func (x *SubjectSearchRequest) GetAction() *Action {
	if x != nil {
		return x.Action
	}
	return nil
}

func (x *SubjectSearchRequest) GetSubject() *SubjectFilter {
	if x != nil {
		return x.Subject
	}
	return nil
}

func (x *SubjectSearchRequest) GetContext() *structpb.Struct {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *SubjectSearchRequest) GetPage() *PageRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

type SubjectSearchResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Results []*Subject             `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	// Optional per AuthZEN spec - omit if pagination not supported
	Page          *PageResponse `protobuf:"bytes,2,opt,name=page,proto3,oneof" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubjectSearchResponse) Reset() {
	*x = SubjectSearchResponse{}
	mi := &file_authzen_v1_authzen_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubjectSearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubjectSearchResponse) ProtoMessage() {}

func (x *SubjectSearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authzen_v1_authzen_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubjectSearchResponse.ProtoReflect.Descriptor instead.
func (*SubjectSearchResponse) Descriptor() ([]byte, []int) {
	return file_authzen_v1_authzen_service_proto_rawDescGZIP(), []int{14}
}

func (x *SubjectSearchResponse) GetResults() []*Subject {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *SubjectSearchResponse) GetPage() *PageResponse {
	if x != nil {
		return x.Page
	}
	return nil
}

// ResourceSearch request
type ResourceSearchRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	StoreId string                 `protobuf:"bytes,1,opt,name=store_id,proto3" json:"store_id,omitempty"`
	Subject *Subject               `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	Action  *Action                `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	// Filter by resource type
	Resource      *ResourceFilter  `protobuf:"bytes,4,opt,name=resource,proto3" json:"resource,omitempty"`
	Context       *structpb.Struct `protobuf:"bytes,5,opt,name=context,proto3,oneof" json:"context,omitempty"`
	Page          *PageRequest     `protobuf:"bytes,6,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceSearchRequest) Reset() {
	*x = ResourceSearchRequest{}
	mi := &file_authzen_v1_authzen_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceSearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceSearchRequest) ProtoMessage() {}

func (x *ResourceSearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authzen_v1_authzen_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceSearchRequest.ProtoReflect.Descriptor instead.
func (*ResourceSearchRequest) Descriptor() ([]byte, []int) {
	return file_authzen_v1_authzen_service_proto_rawDescGZIP(), []int{15}
}

func (x *ResourceSearchRequest) GetStoreId() string {
	if x != nil {
		return x.StoreId
	}
	return ""
}

func (x *ResourceSearchRequest) GetSubject() *Subject {
	if x != nil {
		return x.Subject
	}
	return nil
}

func (x *ResourceSearchRequest) GetAction() *Action {
	if x != nil {
		return x.Action
	}
	return nil
}

func (x *ResourceSearchRequest) GetResource() *ResourceFilter {
	if x != nil {
		return x.Resource
	}
	return nil
}

func (x *ResourceSearchRequest) GetContext() *structpb.Struct {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *ResourceSearchRequest) GetPage() *PageRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

type ResourceSearchResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Results []*Resource            `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	// Optional per AuthZEN spec - omit if pagination not supported
	Page          *PageResponse `protobuf:"bytes,2,opt,name=page,proto3,oneof" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceSearchResponse) Reset() {
	*x = ResourceSearchResponse{}
	mi := &file_authzen_v1_authzen_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceSearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceSearchResponse) ProtoMessage() {}

func (x *ResourceSearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authzen_v1_authzen_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceSearchResponse.ProtoReflect.Descriptor instead.
func (*ResourceSearchResponse) Descriptor() ([]byte, []int) {
	return file_authzen_v1_authzen_service_proto_rawDescGZIP(), []int{16}
}

func (x *ResourceSearchResponse) GetResults() []*Resource {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *ResourceSearchResponse) GetPage() *PageResponse {
	if x != nil {
		return x.Page
	}
	return nil
}

// ActionSearch request
type ActionSearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StoreId       string                 `protobuf:"bytes,1,opt,name=store_id,proto3" json:"store_id,omitempty"`
	Subject       *Subject               `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	Resource      *Resource              `protobuf:"bytes,3,opt,name=resource,proto3" json:"resource,omitempty"`
	Context       *structpb.Struct       `protobuf:"bytes,4,opt,name=context,proto3,oneof" json:"context,omitempty"`
	Page          *PageRequest           `protobuf:"bytes,5,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionSearchRequest) Reset() {
	*x = ActionSearchRequest{}
	mi := &file_authzen_v1_authzen_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionSearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionSearchRequest) ProtoMessage() {}

func (x *ActionSearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authzen_v1_authzen_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionSearchRequest.ProtoReflect.Descriptor instead.
func (*ActionSearchRequest) Descriptor() ([]byte, []int) {
	return file_authzen_v1_authzen_service_proto_rawDescGZIP(), []int{17}
}

func (x *ActionSearchRequest) GetStoreId() string {
	if x != nil {
		return x.StoreId
	}
	return ""
}

func (x *ActionSearchRequest) GetSubject() *Subject {
	if x != nil {
		return x.Subject
	}
	return nil
}

func (x *ActionSearchRequest) GetResource() *Resource {
	if x != nil {
		return x.Resource
	}
	return nil
}

func (x *ActionSearchRequest) GetContext() *structpb.Struct {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *ActionSearchRequest) GetPage() *PageRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

type ActionSearchResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Results []*Action              `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	// Optional per AuthZEN spec - omit if pagination not supported
	Page          *PageResponse `protobuf:"bytes,2,opt,name=page,proto3,oneof" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionSearchResponse) Reset() {
	*x = ActionSearchResponse{}
	mi := &file_authzen_v1_authzen_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionSearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionSearchResponse) ProtoMessage() {}

func (x *ActionSearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authzen_v1_authzen_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionSearchResponse.ProtoReflect.Descriptor instead.
func (*ActionSearchResponse) Descriptor() ([]byte, []int) {
	return file_authzen_v1_authzen_service_proto_rawDescGZIP(), []int{18}
}

func (x *ActionSearchResponse) GetResults() []*Action {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *ActionSearchResponse) GetPage() *PageResponse {
	if x != nil {
		return x.Page
	}
	return nil
}

// GetConfiguration request
type GetConfigurationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The store ID for which to retrieve configuration.
	// Following the AuthZEN spec's multi-tenant pattern, each store has its own discovery endpoint.
	StoreId       string `protobuf:"bytes,1,opt,name=store_id,proto3" json:"store_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigurationRequest) Reset() {
	*x = GetConfigurationRequest{}
	mi := &file_authzen_v1_authzen_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigurationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigurationRequest) ProtoMessage() {}

func (x *GetConfigurationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authzen_v1_authzen_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigurationRequest.ProtoReflect.Descriptor instead.
func (*GetConfigurationRequest) Descriptor() ([]byte, []int) {
	return file_authzen_v1_authzen_service_proto_rawDescGZIP(), []int{19}
}

func (x *GetConfigurationRequest) GetStoreId() string {
	if x != nil {
		return x.StoreId
	}
	return ""
}

// GetConfiguration response - PDP metadata per AuthZEN spec
type GetConfigurationResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// REQUIRED. The PDP identifier URL (HTTPS, no query or fragment).
	PolicyDecisionPoint string `protobuf:"bytes,1,opt,name=policy_decision_point,proto3" json:"policy_decision_point,omitempty"`
	// REQUIRED. The access evaluation endpoint URL.
	AccessEvaluationEndpoint string `protobuf:"bytes,2,opt,name=access_evaluation_endpoint,proto3" json:"access_evaluation_endpoint,omitempty"`
	// OPTIONAL. The batch evaluations endpoint URL.
	AccessEvaluationsEndpoint string `protobuf:"bytes,3,opt,name=access_evaluations_endpoint,proto3" json:"access_evaluations_endpoint,omitempty"`
	// OPTIONAL. The subject search endpoint URL.
	SearchSubjectEndpoint string `protobuf:"bytes,4,opt,name=search_subject_endpoint,proto3" json:"search_subject_endpoint,omitempty"`
	// OPTIONAL. The resource search endpoint URL.
	SearchResourceEndpoint string `protobuf:"bytes,5,opt,name=search_resource_endpoint,proto3" json:"search_resource_endpoint,omitempty"`
	// OPTIONAL. The action search endpoint URL.
	SearchActionEndpoint string `protobuf:"bytes,6,opt,name=search_action_endpoint,proto3" json:"search_action_endpoint,omitempty"`
	// OPTIONAL. Supported capabilities as URN strings.
	Capabilities []string `protobuf:"bytes,7,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	// OPTIONAL. Signed metadata JWT per AuthZEN metadata specification.
	SignedMetadata *string `protobuf:"bytes,8,opt,name=signed_metadata,proto3,oneof" json:"signed_metadata,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetConfigurationResponse) Reset() {
	*x = GetConfigurationResponse{}
	mi := &file_authzen_v1_authzen_service_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigurationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigurationResponse) ProtoMessage() {}

func (x *GetConfigurationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authzen_v1_authzen_service_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigurationResponse.ProtoReflect.Descriptor instead.
func (*GetConfigurationResponse) Descriptor() ([]byte, []int) {
	return file_authzen_v1_authzen_service_proto_rawDescGZIP(), []int{20}
}

func (x *GetConfigurationResponse) GetPolicyDecisionPoint() string {
	if x != nil {
		return x.PolicyDecisionPoint
	}
	return ""
}

func (x *GetConfigurationResponse) GetAccessEvaluationEndpoint() string {
	if x != nil {
		return x.AccessEvaluationEndpoint
	}
	return ""
}

func (x *GetConfigurationResponse) GetAccessEvaluationsEndpoint() string {
	if x != nil {
		return x.AccessEvaluationsEndpoint
	}
	return ""
}

func (x *GetConfigurationResponse) GetSearchSubjectEndpoint() string {
	if x != nil {
		return x.SearchSubjectEndpoint
	}
	return ""
}

func (x *GetConfigurationResponse) GetSearchResourceEndpoint() string {
	if x != nil {
		return x.SearchResourceEndpoint
	}
	return ""
}

func (x *GetConfigurationResponse) GetSearchActionEndpoint() string {
	if x != nil {
		return x.SearchActionEndpoint
	}
	return ""
}

func (x *GetConfigurationResponse) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *GetConfigurationResponse) GetSignedMetadata() string {
	if x != nil && x.SignedMetadata != nil {
		return *x.SignedMetadata
	}
	return ""
}

var File_authzen_v1_authzen_service_proto protoreflect.FileDescriptor

const file_authzen_v1_authzen_service_proto_rawDesc = "" +
	"\n" +
	" authzen/v1/authzen_service.proto\x12\n" +
	"authzen.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\x1a\x17validate/validate.proto\"\xf5\x02\n" +
	"\x11EvaluationRequest\x12h\n" +
	"\bstore_id\x18\x01 \x01(\tBL\x92A\x1eJ\x1c\"01G5JAVJ41T49E9TT3SKVS7X1J\"\xe0A\x02\xfaB%r#2!^[ABCDEFGHJKMNPQRSTVWXYZ0-9]{26}$R\bstore_id\x12:\n" +
	"\asubject\x18\x02 \x01(\v2\x13.authzen.v1.SubjectB\v\xe0A\x02\xfaB\x05\x8a\x01\x02\x10\x01R\asubject\x12=\n" +
	"\bresource\x18\x03 \x01(\v2\x14.authzen.v1.ResourceB\v\xe0A\x02\xfaB\x05\x8a\x01\x02\x10\x01R\bresource\x127\n" +
	"\x06action\x18\x04 \x01(\v2\x12.authzen.v1.ActionB\v\xe0A\x02\xfaB\x05\x8a\x01\x02\x10\x01R\x06action\x126\n" +
	"\acontext\x18\x05 \x01(\v2\x17.google.protobuf.StructH\x00R\acontext\x88\x01\x01B\n" +
	"\n" +
	"\b_context\"\x9c\x02\n" +
	"\x16EvaluationsItemRequest\x122\n" +
	"\asubject\x18\x01 \x01(\v2\x13.authzen.v1.SubjectH\x00R\asubject\x88\x01\x01\x125\n" +
	"\bresource\x18\x02 \x01(\v2\x14.authzen.v1.ResourceH\x01R\bresource\x88\x01\x01\x12/\n" +
	"\x06action\x18\x03 \x01(\v2\x12.authzen.v1.ActionH\x02R\x06action\x88\x01\x01\x126\n" +
	"\acontext\x18\x04 \x01(\v2\x17.google.protobuf.StructH\x03R\acontext\x88\x01\x01B\n" +
	"\n" +
	"\b_subjectB\v\n" +
	"\t_resourceB\t\n" +
	"\a_actionB\n" +
	"\n" +
	"\b_context\"\xcf\x01\n" +
	"\aSubject\x12<\n" +
	"\x04type\x18\x01 \x01(\tB(\x92A\bJ\x06\"user\"\xe0A\x02\xfaB\x17r\x152\x10^[^:#@\\s]{1,50}$\xd0\x01\x00R\x04type\x129\n" +
	"\x02id\x18\x02 \x01(\tB)\x92A\bJ\x06\"anne\"\xe0A\x02\xfaB\x18r\x162\x11^[^:#@\\s]{1,500}$\xd0\x01\x00R\x02id\x12<\n" +
	"\n" +
	"properties\x18\x03 \x01(\v2\x17.google.protobuf.StructH\x00R\n" +
	"properties\x88\x01\x01B\r\n" +
	"\v_properties\"\xb6\x01\n" +
	"\rSubjectFilter\x12<\n" +
	"\x04type\x18\x01 \x01(\tB(\x92A\bJ\x06\"user\"\xe0A\x02\xfaB\x17r\x152\x10^[^:#@\\s]{1,50}$\xd0\x01\x00R\x04type\x12\x13\n" +
	"\x02id\x18\x02 \x01(\tH\x00R\x02id\x88\x01\x01\x12<\n" +
	"\n" +
	"properties\x18\x03 \x01(\v2\x17.google.protobuf.StructH\x01R\n" +
	"properties\x88\x01\x01B\x05\n" +
	"\x03_idB\r\n" +
	"\v_properties\"\xd7\x01\n" +
	"\bResource\x12@\n" +
	"\x04type\x18\x01 \x01(\tB,\x92A\fJ\n" +
	"\"document\"\xe0A\x02\xfaB\x17r\x152\x10^[^:#@\\s]{1,50}$\xd0\x01\x00R\x04type\x12<\n" +
	"\x02id\x18\x02 \x01(\tB,\x92A\vJ\t\"roadmap\"\xe0A\x02\xfaB\x18r\x162\x11^[^:#@\\s]{1,256}$\xd0\x01\x00R\x02id\x12<\n" +
	"\n" +
	"properties\x18\x03 \x01(\v2\x17.google.protobuf.StructH\x00R\n" +
	"properties\x88\x01\x01B\r\n" +
	"\v_properties\"\xbb\x01\n" +
	"\x0eResourceFilter\x12@\n" +
	"\x04type\x18\x01 \x01(\tB,\x92A\fJ\n" +
	"\"document\"\xe0A\x02\xfaB\x17r\x152\x10^[^:#@\\s]{1,50}$\xd0\x01\x00R\x04type\x12\x13\n" +
	"\x02id\x18\x02 \x01(\tH\x00R\x02id\x88\x01\x01\x12<\n" +
	"\n" +
	"properties\x18\x03 \x01(\v2\x17.google.protobuf.StructH\x01R\n" +
	"properties\x88\x01\x01B\x05\n" +
	"\x03_idB\r\n" +
	"\v_properties\"\x97\x01\n" +
	"\x06Action\x12@\n" +
	"\x04name\x18\x01 \x01(\tB,\x92A\fJ\n" +
	"\"can_read\"\xe0A\x02\xfaB\x17r\x152\x10^[^:#@\\s]{1,50}$\xd0\x01\x00R\x04name\x12<\n" +
	"\n" +
	"properties\x18\x02 \x01(\v2\x17.google.protobuf.StructH\x00R\n" +
	"properties\x88\x01\x01B\r\n" +
	"\v_properties\"t\n" +
	"\x12EvaluationResponse\x12\x1a\n" +
	"\bdecision\x18\x01 \x01(\bR\bdecision\x126\n" +
	"\acontext\x18\x02 \x01(\v2\x17.google.protobuf.StructH\x00R\acontext\x88\x01\x01B\n" +
	"\n" +
	"\b_context\"\x82\x04\n" +
	"\x12EvaluationsRequest\x12h\n" +
	"\bstore_id\x18\x01 \x01(\tBL\x92A\x1eJ\x1c\"01G5JAVJ41T49E9TT3SKVS7X1J\"\xe0A\x02\xfaB%r#2!^[ABCDEFGHJKMNPQRSTVWXYZ0-9]{26}$R\bstore_id\x122\n" +
	"\asubject\x18\x02 \x01(\v2\x13.authzen.v1.SubjectH\x00R\asubject\x88\x01\x01\x12/\n" +
	"\x06action\x18\x03 \x01(\v2\x12.authzen.v1.ActionH\x01R\x06action\x88\x01\x01\x125\n" +
	"\bresource\x18\x04 \x01(\v2\x14.authzen.v1.ResourceH\x02R\bresource\x88\x01\x01\x126\n" +
	"\acontext\x18\x05 \x01(\v2\x17.google.protobuf.StructH\x03R\acontext\x88\x01\x01\x12D\n" +
	"\vevaluations\x18\x06 \x03(\v2\".authzen.v1.EvaluationsItemRequestR\vevaluations\x128\n" +
	"\aoptions\x18\a \x01(\v2\x1e.authzen.v1.EvaluationsOptionsR\aoptionsB\n" +
	"\n" +
	"\b_subjectB\t\n" +
	"\a_actionB\v\n" +
	"\t_resourceB\n" +
	"\n" +
	"\b_context\"W\n" +
	"\x13EvaluationsResponse\x12@\n" +
	"\vevaluations\x18\x01 \x03(\v2\x1e.authzen.v1.EvaluationResponseR\vevaluations\"s\n" +
	"\x12EvaluationsOptions\x12]\n" +
	"\x14evaluations_semantic\x18\x01 \x01(\x0e2\x1f.authzen.v1.EvaluationsSemanticB\b\xfaB\x05\x82\x01\x02\x10\x01R\x14evaluations_semantic\"a\n" +
	"\vPageRequest\x12\x19\n" +
	"\x05token\x18\x01 \x01(\tH\x00R\x05token\x88\x01\x01\x12#\n" +
	"\x05limit\x18\x02 \x01(\rB\b\xfaB\x05*\x03\x18\xe8\aH\x01R\x05limit\x88\x01\x01B\b\n" +
	"\x06_tokenB\b\n" +
	"\x06_limit\"i\n" +
	"\fPageResponse\x12\x1e\n" +
	"\n" +
	"next_token\x18\x01 \x01(\tR\n" +
	"next_token\x12\x14\n" +
	"\x05count\x18\x02 \x01(\rR\x05count\x12\x19\n" +
	"\x05total\x18\x03 \x01(\rH\x00R\x05total\x88\x01\x01B\b\n" +
	"\x06_total\"\x8a\x03\n" +
	"\x14SubjectSearchRequest\x12G\n" +
	"\bstore_id\x18\x01 \x01(\tB+\xe0A\x02\xfaB%r#2!^[ABCDEFGHJKMNPQRSTVWXYZ0-9]{26}$R\bstore_id\x12=\n" +
	"\bresource\x18\x02 \x01(\v2\x14.authzen.v1.ResourceB\v\xe0A\x02\xfaB\x05\x8a\x01\x02\x10\x01R\bresource\x127\n" +
	"\x06action\x18\x03 \x01(\v2\x12.authzen.v1.ActionB\v\xe0A\x02\xfaB\x05\x8a\x01\x02\x10\x01R\x06action\x12@\n" +
	"\asubject\x18\x04 \x01(\v2\x19.authzen.v1.SubjectFilterB\v\xe0A\x02\xfaB\x05\x8a\x01\x02\x10\x01R\asubject\x126\n" +
	"\acontext\x18\x05 \x01(\v2\x17.google.protobuf.StructH\x00R\acontext\x88\x01\x01\x12+\n" +
	"\x04page\x18\x06 \x01(\v2\x17.authzen.v1.PageRequestR\x04pageB\n" +
	"\n" +
	"\b_context\"\x82\x01\n" +
	"\x15SubjectSearchResponse\x12-\n" +
	"\aresults\x18\x01 \x03(\v2\x13.authzen.v1.SubjectR\aresults\x121\n" +
	"\x04page\x18\x02 \x01(\v2\x18.authzen.v1.PageResponseH\x00R\x04page\x88\x01\x01B\a\n" +
	"\x05_page\"\x8b\x03\n" +
	"\x15ResourceSearchRequest\x12G\n" +
	"\bstore_id\x18\x01 \x01(\tB+\xe0A\x02\xfaB%r#2!^[ABCDEFGHJKMNPQRSTVWXYZ0-9]{26}$R\bstore_id\x12:\n" +
	"\asubject\x18\x02 \x01(\v2\x13.authzen.v1.SubjectB\v\xe0A\x02\xfaB\x05\x8a\x01\x02\x10\x01R\asubject\x127\n" +
	"\x06action\x18\x03 \x01(\v2\x12.authzen.v1.ActionB\v\xe0A\x02\xfaB\x05\x8a\x01\x02\x10\x01R\x06action\x12C\n" +
	"\bresource\x18\x04 \x01(\v2\x1a.authzen.v1.ResourceFilterB\v\xe0A\x02\xfaB\x05\x8a\x01\x02\x10\x01R\bresource\x126\n" +
	"\acontext\x18\x05 \x01(\v2\x17.google.protobuf.StructH\x00R\acontext\x88\x01\x01\x12+\n" +
	"\x04page\x18\x06 \x01(\v2\x17.authzen.v1.PageRequestR\x04pageB\n" +
	"\n" +
	"\b_context\"\x84\x01\n" +
	"\x16ResourceSearchResponse\x12.\n" +
	"\aresults\x18\x01 \x03(\v2\x14.authzen.v1.ResourceR\aresults\x121\n" +
	"\x04page\x18\x02 \x01(\v2\x18.authzen.v1.PageResponseH\x00R\x04page\x88\x01\x01B\a\n" +
	"\x05_page\"\xca\x02\n" +
	"\x13ActionSearchRequest\x12G\n" +
	"\bstore_id\x18\x01 \x01(\tB+\xe0A\x02\xfaB%r#2!^[ABCDEFGHJKMNPQRSTVWXYZ0-9]{26}$R\bstore_id\x12:\n" +
	"\asubject\x18\x02 \x01(\v2\x13.authzen.v1.SubjectB\v\xe0A\x02\xfaB\x05\x8a\x01\x02\x10\x01R\asubject\x12=\n" +
	"\bresource\x18\x03 \x01(\v2\x14.authzen.v1.ResourceB\v\xe0A\x02\xfaB\x05\x8a\x01\x02\x10\x01R\bresource\x126\n" +
	"\acontext\x18\x04 \x01(\v2\x17.google.protobuf.StructH\x00R\acontext\x88\x01\x01\x12+\n" +
	"\x04page\x18\x05 \x01(\v2\x17.authzen.v1.PageRequestR\x04pageB\n" +
	"\n" +
	"\b_context\"\x80\x01\n" +
	"\x14ActionSearchResponse\x12,\n" +
	"\aresults\x18\x01 \x03(\v2\x12.authzen.v1.ActionR\aresults\x121\n" +
	"\x04page\x18\x02 \x01(\v2\x18.authzen.v1.PageResponseH\x00R\x04page\x88\x01\x01B\a\n" +
	"\x05_page\"\x83\x01\n" +
	"\x17GetConfigurationRequest\x12h\n" +
	"\bstore_id\x18\x01 \x01(\tBL\x92A\x1eJ\x1c\"01G5JAVJ41T49E9TT3SKVS7X1J\"\xe0A\x02\xfaB%r#2!^[ABCDEFGHJKMNPQRSTVWXYZ0-9]{26}$R\bstore_id\"\x8f\x04\n" +
	"\x18GetConfigurationResponse\x129\n" +
	"\x15policy_decision_point\x18\x01 \x01(\tB\x03\xe0A\x02R\x15policy_decision_point\x12C\n" +
	"\x1aaccess_evaluation_endpoint\x18\x02 \x01(\tB\x03\xe0A\x02R\x1aaccess_evaluation_endpoint\x12E\n" +
	"\x1baccess_evaluations_endpoint\x18\x03 \x01(\tB\x03\xe0A\x01R\x1baccess_evaluations_endpoint\x12=\n" +
	"\x17search_subject_endpoint\x18\x04 \x01(\tB\x03\xe0A\x01R\x17search_subject_endpoint\x12?\n" +
	"\x18search_resource_endpoint\x18\x05 \x01(\tB\x03\xe0A\x01R\x18search_resource_endpoint\x12;\n" +
	"\x16search_action_endpoint\x18\x06 \x01(\tB\x03\xe0A\x01R\x16search_action_endpoint\x12'\n" +
	"\fcapabilities\x18\a \x03(\tB\x03\xe0A\x01R\fcapabilities\x122\n" +
	"\x0fsigned_metadata\x18\b \x01(\tB\x03\xe0A\x01H\x00R\x0fsigned_metadata\x88\x01\x01B\x12\n" +
	"\x10_signed_metadata*Z\n" +
	"\x13EvaluationsSemantic\x12\x0f\n" +
	"\vexecute_all\x10\x00\x12\x16\n" +
	"\x12deny_on_first_deny\x10\x01\x12\x1a\n" +
	"\x16permit_on_first_permit\x10\x022\x99R\n" +
	"\x0eAuthZenService\x12\xab\x16\n" +
	"\n" +
	"Evaluation\x12\x1d.authzen.v1.EvaluationRequest\x1a\x1e.authzen.v1.EvaluationResponse\"\xdd\x15\x92A\xa7\x15\x12M[Experimental] Evaluate whether a subject can perform an action on a resource\x1a\xc9\x14[Experimental] The Evaluation API determines whether a subject is authorized to perform an action on a resource. This endpoint implements the AuthZEN Access Evaluation API specification.\n" +
	"\n" +
	"## Request Structure\n" +
	"The request requires three components:\n" +
	"- **subject**: The entity requesting access (e.g., a user or service)\n" +
	"- **action**: The operation being performed (maps to a relation in the authorization model)\n" +
	"- **resource**: The object being accessed\n" +
	"\n" +
	"Each component has a `type` and `id` field, and may include optional `properties` for ABAC (Attribute-Based Access Control) conditions.\n" +
	"\n" +
	"## Response\n" +
	"The response contains a `decision` field (boolean) indicating whether access is permitted, and an optional `context` object with additional information such as the evaluation ID or error details.\n" +
	"\n" +
	"## ABAC Support\n" +
	"Properties on subject, action, and resource are automatically merged into the evaluation context with prefixes:\n" +
	"- Subject properties: `subject_<property_name>`\n" +
	"- Resource properties: `resource_<property_name>`\n" +
	"- Action properties: `action_<property_name>`\n" +
	"\n" +
	"These merged properties can be used in conditions defined in your authorization model.\n" +
	"\n" +
	"## Examples\n" +
	"### Basic authorization check\n" +
	"Check if user Anne can read a document:\n" +
	"```json\n" +
	"{\n" +
	"  \"subject\": {\"type\": \"user\", \"id\": \"anne\"},\n" +
	"  \"action\": {\"name\": \"can_read\"},\n" +
	"  \"resource\": {\"type\": \"document\", \"id\": \"roadmap\"}\n" +
	"}\n" +
	"```\n" +
	"Response when authorized:\n" +
	"```json\n" +
	"{\n" +
	"  \"decision\": true\n" +
	"}\n" +
	"```\n" +
	"### Using properties for ABAC\n" +
	"Check access with subject and resource attributes:\n" +
	"```json\n" +
	"{\n" +
	"  \"subject\": {\n" +
	"    \"type\": \"user\",\n" +
	"    \"id\": \"anne\",\n" +
	"    \"properties\": {\"department\": \"engineering\", \"clearance_level\": 3}\n" +
	"  },\n" +
	"  \"action\": {\"name\": \"can_read\"},\n" +
	"  \"resource\": {\n" +
	"    \"type\": \"document\",\n" +
	"    \"id\": \"secret-project\",\n" +
	"    \"properties\": {\"classification\": \"confidential\", \"required_clearance\": 2}\n" +
	"  }\n" +
	"}\n" +
	"```\n" +
	"### Using request context\n" +
	"Provide additional context for time-based or environmental conditions:\n" +
	"```json\n" +
	"{\n" +
	"  \"subject\": {\"type\": \"user\", \"id\": \"bob\"},\n" +
	"  \"action\": {\"name\": \"can_access\"},\n" +
	"  \"resource\": {\"type\": \"system\", \"id\": \"production\"},\n" +
	"  \"context\": {\n" +
	"    \"current_time\": \"2024-01-15T14:30:00Z\",\n" +
	"    \"ip_address\": \"192.168.1.100\",\n" +
	"    \"is_vpn_connected\": true\n" +
	"  }\n" +
	"}\n" +
	"```\n" +
	"### Specifying authorization model\n" +
	"Pin the evaluation to a specific authorization model version using the `Openfga-Authorization-Model-Id` header:\n" +
	"```\n" +
	"POST /stores/{store_id}/access/v1/evaluation\n" +
	"Openfga-Authorization-Model-Id: 01G50QVV17PECNVAHX1GG4Y5NC\n" +
	"\n" +
	"{\n" +
	"  \"subject\": {\"type\": \"user\", \"id\": \"anne\"},\n" +
	"  \"action\": {\"name\": \"can_write\"},\n" +
	"  \"resource\": {\"type\": \"document\", \"id\": \"budget-2024\"}\n" +
	"}\n" +
	"```\n" +
	"*\n" +
	"Evaluation\x82\xd3\xe4\x93\x02,:\x01*\"'/stores/{store_id}/access/v1/evaluation\x12\xc7\x11\n" +
	"\vEvaluations\x12\x1e.authzen.v1.EvaluationsRequest\x1a\x1f.authzen.v1.EvaluationsResponse\"\xf6\x10\x92A\xbf\x10\x12Q[Experimental] Check whether one or more users are authorized to access resources\x1a\xdc\x0f[Experimental] The Evaluations API allows batch authorization checks in a single request. It supports request-level defaults for subject, action, resource, and context that can be overridden per evaluation item.\n" +
	"\n" +
	"## Evaluation Semantics\n" +
	"The `options.evaluations_semantic` field controls how evaluations are processed:\n" +
	"- `execute_all` (default): Execute all evaluations and return all results\n" +
	"- `deny_on_first_deny`: Stop processing on first deny decision\n" +
	"- `permit_on_first_permit`: Stop processing on first permit decision\n" +
	"\n" +
	"When using `deny_on_first_deny` or `permit_on_first_permit`, the response may include fewer items than the request because processing short-circuits when the condition is met.\n" +
	"\n" +
	"## Authorization Model Selection\n" +
	"To pin evaluations to a specific authorization model version, send the `Openfga-Authorization-Model-Id` header. If the header is not provided, the latest model is used.\n" +
	"\n" +
	"## Examples\n" +
	"### Basic batch evaluation\n" +
	"Check if a user can perform multiple actions on a document:\n" +
	"```json\n" +
	"{\n" +
	"  \"subject\": {\"type\": \"user\", \"id\": \"anne\"},\n" +
	"  \"resource\": {\"type\": \"document\", \"id\": \"roadmap\"},\n" +
	"  \"evaluations\": [\n" +
	"    {\"action\": {\"name\": \"can_read\"}},\n" +
	"    {\"action\": {\"name\": \"can_write\"}},\n" +
	"    {\"action\": {\"name\": \"can_delete\"}}\n" +
	"  ]\n" +
	"}\n" +
	"```\n" +
	"### Using evaluation semantics\n" +
	"Stop on first permitted action (useful for finding any valid permission):\n" +
	"```json\n" +
	"{\n" +
	"  \"subject\": {\"type\": \"user\", \"id\": \"anne\"},\n" +
	"  \"resource\": {\"type\": \"document\", \"id\": \"roadmap\"},\n" +
	"  \"evaluations\": [\n" +
	"    {\"action\": {\"name\": \"can_read\"}},\n" +
	"    {\"action\": {\"name\": \"can_write\"}}\n" +
	"  ],\n" +
	"  \"options\": {\n" +
	"    \"evaluations_semantic\": \"permit_on_first_permit\"\n" +
	"  }\n" +
	"}\n" +
	"```\n" +
	"### Overriding defaults per evaluation\n" +
	"Check permissions across multiple resources:\n" +
	"```json\n" +
	"{\n" +
	"  \"subject\": {\"type\": \"user\", \"id\": \"anne\"},\n" +
	"  \"action\": {\"name\": \"can_read\"},\n" +
	"  \"evaluations\": [\n" +
	"    {\"resource\": {\"type\": \"document\", \"id\": \"doc1\"}},\n" +
	"    {\"resource\": {\"type\": \"document\", \"id\": \"doc2\"}},\n" +
	"    {\"resource\": {\"type\": \"folder\", \"id\": \"folder1\"}}\n" +
	"  ]\n" +
	"}\n" +
	"```\n" +
	"*\vEvaluations\x82\xd3\xe4\x93\x02-:\x01*\"(/stores/{store_id}/access/v1/evaluations\x12\xb1\n" +
	"\n" +
	"\rSubjectSearch\x12 .authzen.v1.SubjectSearchRequest\x1a!.authzen.v1.SubjectSearchResponse\"\xda\t\x92A\xa0\t\x12<[Experimental] Search for subjects with access to a resource\x1a\xd0\b[Experimental] The SubjectSearch API returns all subjects that have a specific action (relation) on a given resource. This is useful for answering questions like \"Who can read this document?\" or \"Who can administer this folder?\"\n" +
	"\n" +
	"Results can be filtered by subject type and support pagination for large result sets.\n" +
	"\n" +
	"## Examples\n" +
	"### Find all users who can read a document\n" +
	"```json\n" +
	"{\n" +
	"  \"resource\": {\"type\": \"document\", \"id\": \"roadmap\"},\n" +
	"  \"action\": {\"name\": \"can_read\"},\n" +
	"  \"subject\": {\"type\": \"user\"}\n" +
	"}\n" +
	"```\n" +
	"Response:\n" +
	"```json\n" +
	"{\n" +
	"  \"results\": [\n" +
	"    {\"type\": \"user\", \"id\": \"anne\"},\n" +
	"    {\"type\": \"user\", \"id\": \"bob\"},\n" +
	"    {\"type\": \"user\", \"id\": \"charlie\"}\n" +
	"  ],\n" +
	"  \"page\": {\"count\": 3}\n" +
	"}\n" +
	"```\n" +
	"### Paginated search with limit\n" +
	"```json\n" +
	"{\n" +
	"  \"resource\": {\"type\": \"folder\", \"id\": \"engineering\"},\n" +
	"  \"action\": {\"name\": \"can_view\"},\n" +
	"  \"subject\": {\"type\": \"user\"},\n" +
	"  \"page\": {\"limit\": 10}\n" +
	"}\n" +
	"```\n" +
	"### Continue from previous page\n" +
	"```json\n" +
	"{\n" +
	"  \"resource\": {\"type\": \"folder\", \"id\": \"engineering\"},\n" +
	"  \"action\": {\"name\": \"can_view\"},\n" +
	"  \"subject\": {\"type\": \"user\"},\n" +
	"  \"page\": {\"token\": \"eyJsYXN0X2lkIjoiMTAwIn0=\", \"limit\": 10}\n" +
	"}\n" +
	"```\n" +
	"*\rSubjectSearch\x82\xd3\xe4\x93\x020:\x01*\"+/stores/{store_id}/access/v1/search/subject\x12\x84\v\n" +
	"\x0eResourceSearch\x12!.authzen.v1.ResourceSearchRequest\x1a\".authzen.v1.ResourceSearchResponse\"\xaa\n" +
	"\x92A\xef\t\x12;[Experimental] Search for resources a subject has access to\x1a\x9f\t[Experimental] The ResourceSearch API returns all resources of a given type that a subject has a specific action (relation) on. This is useful for answering questions like \"What documents can Anne read?\" or \"What folders can Bob administer?\"\n" +
	"\n" +
	"The resource type filter is required. Results support pagination for large result sets.\n" +
	"\n" +
	"## Examples\n" +
	"### Find all documents a user can read\n" +
	"```json\n" +
	"{\n" +
	"  \"subject\": {\"type\": \"user\", \"id\": \"anne\"},\n" +
	"  \"action\": {\"name\": \"can_read\"},\n" +
	"  \"resource\": {\"type\": \"document\"}\n" +
	"}\n" +
	"```\n" +
	"Response:\n" +
	"```json\n" +
	"{\n" +
	"  \"results\": [\n" +
	"    {\"type\": \"document\", \"id\": \"roadmap\"},\n" +
	"    {\"type\": \"document\", \"id\": \"budget-2024\"},\n" +
	"    {\"type\": \"document\", \"id\": \"team-roster\"}\n" +
	"  ],\n" +
	"  \"page\": {\"count\": 3}\n" +
	"}\n" +
	"```\n" +
	"### Find folders a user can administer with pagination\n" +
	"```json\n" +
	"{\n" +
	"  \"subject\": {\"type\": \"user\", \"id\": \"bob\"},\n" +
	"  \"action\": {\"name\": \"can_admin\"},\n" +
	"  \"resource\": {\"type\": \"folder\"},\n" +
	"  \"page\": {\"limit\": 25}\n" +
	"}\n" +
	"```\n" +
	"### Search with ABAC context\n" +
	"```json\n" +
	"{\n" +
	"  \"subject\": {\"type\": \"user\", \"id\": \"anne\"},\n" +
	"  \"action\": {\"name\": \"can_read\"},\n" +
	"  \"resource\": {\"type\": \"document\"},\n" +
	"  \"context\": {\n" +
	"    \"current_time\": \"2024-01-15T10:00:00Z\",\n" +
	"    \"ip_address\": \"192.168.1.100\"\n" +
	"  }\n" +
	"}\n" +
	"```\n" +
	"*\x0eResourceSearch\x82\xd3\xe4\x93\x021:\x01*\",/stores/{store_id}/access/v1/search/resource\x12\x86\n" +
	"\n" +
	"\fActionSearch\x12\x1f.authzen.v1.ActionSearchRequest\x1a .authzen.v1.ActionSearchResponse\"\xb2\t\x92A\xf9\b\x12E[Experimental] Search for actions a subject can perform on a resource\x1a\xa1\b[Experimental] The ActionSearch API returns all actions (relations) that a subject can perform on a specific resource. This is useful for answering questions like \"What can Anne do with this document?\" or building dynamic UIs that show only the actions a user is permitted to perform.\n" +
	"\n" +
	"## Examples\n" +
	"### Find all actions a user can perform on a document\n" +
	"```json\n" +
	"{\n" +
	"  \"subject\": {\"type\": \"user\", \"id\": \"anne\"},\n" +
	"  \"resource\": {\"type\": \"document\", \"id\": \"roadmap\"}\n" +
	"}\n" +
	"```\n" +
	"Response:\n" +
	"```json\n" +
	"{\n" +
	"  \"results\": [\n" +
	"    {\"name\": \"can_read\"},\n" +
	"    {\"name\": \"can_write\"},\n" +
	"    {\"name\": \"can_share\"}\n" +
	"  ],\n" +
	"  \"page\": {\"count\": 3}\n" +
	"}\n" +
	"```\n" +
	"### Search with ABAC context for time-based permissions\n" +
	"```json\n" +
	"{\n" +
	"  \"subject\": {\"type\": \"user\", \"id\": \"bob\"},\n" +
	"  \"resource\": {\"type\": \"report\", \"id\": \"quarterly-financials\"},\n" +
	"  \"context\": {\n" +
	"    \"current_time\": \"2024-01-15T14:30:00Z\",\n" +
	"    \"user_department\": \"finance\"\n" +
	"  }\n" +
	"}\n" +
	"```\n" +
	"### Paginated action search\n" +
	"```json\n" +
	"{\n" +
	"  \"subject\": {\"type\": \"user\", \"id\": \"admin\"},\n" +
	"  \"resource\": {\"type\": \"system\", \"id\": \"production\"},\n" +
	"  \"page\": {\"limit\": 50}\n" +
	"}\n" +
	"```\n" +
	"*\fActionSearch\x82\xd3\xe4\x93\x02/:\x01*\"*/stores/{store_id}/access/v1/search/action\x12\xca\n" +
	"\n" +
	"\x10GetConfiguration\x12#.authzen.v1.GetConfigurationRequest\x1a$.authzen.v1.GetConfigurationResponse\"\xea\t\x92A\xb1\t\x12=[Experimental] Get AuthZEN PDP configuration and capabilities\x1a\xdd\b[Experimental] The GetConfiguration API returns metadata about the Policy Decision Point (PDP) including its name, version, supported endpoints, and capabilities. This endpoint follows the AuthZEN specification for PDP discovery.\n" +
	"\n" +
	"Following the AuthZEN spec's multi-tenant pattern, OpenFGA provides a per-store discovery endpoint at `/.well-known/authzen-configuration/{store_id}`. This returns absolute endpoint URLs specific to that store.\n" +
	"\n" +
	"## Example Response\n" +
	"```json\n" +
	"{\n" +
	"  \"policy_decision_point\": \"https://example.com/stores/01ARZ3NDEKTSV4RRFFQ69G5FAV\",\n" +
	"  \"access_evaluation_endpoint\": \"https://example.com/stores/01ARZ3NDEKTSV4RRFFQ69G5FAV/access/v1/evaluation\",\n" +
	"  \"access_evaluations_endpoint\": \"https://example.com/stores/01ARZ3NDEKTSV4RRFFQ69G5FAV/access/v1/evaluations\",\n" +
	"  \"search_subject_endpoint\": \"https://example.com/stores/01ARZ3NDEKTSV4RRFFQ69G5FAV/access/v1/search/subject\",\n" +
	"  \"search_resource_endpoint\": \"https://example.com/stores/01ARZ3NDEKTSV4RRFFQ69G5FAV/access/v1/search/resource\",\n" +
	"  \"search_action_endpoint\": \"https://example.com/stores/01ARZ3NDEKTSV4RRFFQ69G5FAV/access/v1/search/action\"\n" +
	"}\n" +
	"```\n" +
	"*\x10GetConfiguration\x82\xd3\xe4\x93\x02/\x12-/.well-known/authzen-configuration/{store_id}B\xa1\x01\n" +
	"\x0ecom.authzen.v1B\x13AuthzenServiceProtoP\x01Z1github.com/openfga/api/proto/authzen/v1;authzenv1\xa2\x02\x03AXX\xaa\x02\n" +
	"Authzen.V1\xca\x02\n" +
	"Authzen\\V1\xe2\x02\x16Authzen\\V1\\GPBMetadata\xea\x02\vAuthzen::V1b\x06proto3"

var (
	file_authzen_v1_authzen_service_proto_rawDescOnce sync.Once
	file_authzen_v1_authzen_service_proto_rawDescData []byte
)

func file_authzen_v1_authzen_service_proto_rawDescGZIP() []byte {
	file_authzen_v1_authzen_service_proto_rawDescOnce.Do(func() {
		file_authzen_v1_authzen_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_authzen_v1_authzen_service_proto_rawDesc), len(file_authzen_v1_authzen_service_proto_rawDesc)))
	})
	return file_authzen_v1_authzen_service_proto_rawDescData
}

var file_authzen_v1_authzen_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_authzen_v1_authzen_service_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_authzen_v1_authzen_service_proto_goTypes = []any{
	(EvaluationsSemantic)(0),         // 0: authzen.v1.EvaluationsSemantic
	(*EvaluationRequest)(nil),        // 1: authzen.v1.EvaluationRequest
	(*EvaluationsItemRequest)(nil),   // 2: authzen.v1.EvaluationsItemRequest
	(*Subject)(nil),                  // 3: authzen.v1.Subject
	(*SubjectFilter)(nil),            // 4: authzen.v1.SubjectFilter
	(*Resource)(nil),                 // 5: authzen.v1.Resource
	(*ResourceFilter)(nil),           // 6: authzen.v1.ResourceFilter
	(*Action)(nil),                   // 7: authzen.v1.Action
	(*EvaluationResponse)(nil),       // 8: authzen.v1.EvaluationResponse
	(*EvaluationsRequest)(nil),       // 9: authzen.v1.EvaluationsRequest
	(*EvaluationsResponse)(nil),      // 10: authzen.v1.EvaluationsResponse
	(*EvaluationsOptions)(nil),       // 11: authzen.v1.EvaluationsOptions
	(*PageRequest)(nil),              // 12: authzen.v1.PageRequest
	(*PageResponse)(nil),             // 13: authzen.v1.PageResponse
	(*SubjectSearchRequest)(nil),     // 14: authzen.v1.SubjectSearchRequest
	(*SubjectSearchResponse)(nil),    // 15: authzen.v1.SubjectSearchResponse
	(*ResourceSearchRequest)(nil),    // 16: authzen.v1.ResourceSearchRequest
	(*ResourceSearchResponse)(nil),   // 17: authzen.v1.ResourceSearchResponse
	(*ActionSearchRequest)(nil),      // 18: authzen.v1.ActionSearchRequest
	(*ActionSearchResponse)(nil),     // 19: authzen.v1.ActionSearchResponse
	(*GetConfigurationRequest)(nil),  // 20: authzen.v1.GetConfigurationRequest
	(*GetConfigurationResponse)(nil), // 21: authzen.v1.GetConfigurationResponse
	(*structpb.Struct)(nil),          // 22: google.protobuf.Struct
}
var file_authzen_v1_authzen_service_proto_depIdxs = []int32{
	3,  // 0: authzen.v1.EvaluationRequest.subject:type_name -> authzen.v1.Subject
	5,  // 1: authzen.v1.EvaluationRequest.resource:type_name -> authzen.v1.Resource
	7,  // 2: authzen.v1.EvaluationRequest.action:type_name -> authzen.v1.Action
	22, // 3: authzen.v1.EvaluationRequest.context:type_name -> google.protobuf.Struct
	3,  // 4: authzen.v1.EvaluationsItemRequest.subject:type_name -> authzen.v1.Subject
	5,  // 5: authzen.v1.EvaluationsItemRequest.resource:type_name -> authzen.v1.Resource
	7,  // 6: authzen.v1.EvaluationsItemRequest.action:type_name -> authzen.v1.Action
	22, // 7: authzen.v1.EvaluationsItemRequest.context:type_name -> google.protobuf.Struct
	22, // 8: authzen.v1.Subject.properties:type_name -> google.protobuf.Struct
	22, // 9: authzen.v1.SubjectFilter.properties:type_name -> google.protobuf.Struct
	22, // 10: authzen.v1.Resource.properties:type_name -> google.protobuf.Struct
	22, // 11: authzen.v1.ResourceFilter.properties:type_name -> google.protobuf.Struct
	22, // 12: authzen.v1.Action.properties:type_name -> google.protobuf.Struct
	22, // 13: authzen.v1.EvaluationResponse.context:type_name -> google.protobuf.Struct
	3,  // 14: authzen.v1.EvaluationsRequest.subject:type_name -> authzen.v1.Subject
	7,  // 15: authzen.v1.EvaluationsRequest.action:type_name -> authzen.v1.Action
	5,  // 16: authzen.v1.EvaluationsRequest.resource:type_name -> authzen.v1.Resource
	22, // 17: authzen.v1.EvaluationsRequest.context:type_name -> google.protobuf.Struct
	2,  // 18: authzen.v1.EvaluationsRequest.evaluations:type_name -> authzen.v1.EvaluationsItemRequest
	11, // 19: authzen.v1.EvaluationsRequest.options:type_name -> authzen.v1.EvaluationsOptions
	8,  // 20: authzen.v1.EvaluationsResponse.evaluations:type_name -> authzen.v1.EvaluationResponse
	0,  // 21: authzen.v1.EvaluationsOptions.evaluations_semantic:type_name -> authzen.v1.EvaluationsSemantic
	5,  // 22: authzen.v1.SubjectSearchRequest.resource:type_name -> authzen.v1.Resource
	7,  // 23: authzen.v1.SubjectSearchRequest.action:type_name -> authzen.v1.Action
	4,  // 24: authzen.v1.SubjectSearchRequest.subject:type_name -> authzen.v1.SubjectFilter
	22, // 25: authzen.v1.SubjectSearchRequest.context:type_name -> google.protobuf.Struct
	12, // 26: authzen.v1.SubjectSearchRequest.page:type_name -> authzen.v1.PageRequest
	3,  // 27: authzen.v1.SubjectSearchResponse.results:type_name -> authzen.v1.Subject
	13, // 28: authzen.v1.SubjectSearchResponse.page:type_name -> authzen.v1.PageResponse
	3,  // 29: authzen.v1.ResourceSearchRequest.subject:type_name -> authzen.v1.Subject
	7,  // 30: authzen.v1.ResourceSearchRequest.action:type_name -> authzen.v1.Action
	6,  // 31: authzen.v1.ResourceSearchRequest.resource:type_name -> authzen.v1.ResourceFilter
	22, // 32: authzen.v1.ResourceSearchRequest.context:type_name -> google.protobuf.Struct
	12, // 33: authzen.v1.ResourceSearchRequest.page:type_name -> authzen.v1.PageRequest
	5,  // 34: authzen.v1.ResourceSearchResponse.results:type_name -> authzen.v1.Resource
	13, // 35: authzen.v1.ResourceSearchResponse.page:type_name -> authzen.v1.PageResponse
	3,  // 36: authzen.v1.ActionSearchRequest.subject:type_name -> authzen.v1.Subject
	5,  // 37: authzen.v1.ActionSearchRequest.resource:type_name -> authzen.v1.Resource
	22, // 38: authzen.v1.ActionSearchRequest.context:type_name -> google.protobuf.Struct
	12, // 39: authzen.v1.ActionSearchRequest.page:type_name -> authzen.v1.PageRequest
	7,  // 40: authzen.v1.ActionSearchResponse.results:type_name -> authzen.v1.Action
	13, // 41: authzen.v1.ActionSearchResponse.page:type_name -> authzen.v1.PageResponse
	1,  // 42: authzen.v1.AuthZenService.Evaluation:input_type -> authzen.v1.EvaluationRequest
	9,  // 43: authzen.v1.AuthZenService.Evaluations:input_type -> authzen.v1.EvaluationsRequest
	14, // 44: authzen.v1.AuthZenService.SubjectSearch:input_type -> authzen.v1.SubjectSearchRequest
	16, // 45: authzen.v1.AuthZenService.ResourceSearch:input_type -> authzen.v1.ResourceSearchRequest
	18, // 46: authzen.v1.AuthZenService.ActionSearch:input_type -> authzen.v1.ActionSearchRequest
	20, // 47: authzen.v1.AuthZenService.GetConfiguration:input_type -> authzen.v1.GetConfigurationRequest
	8,  // 48: authzen.v1.AuthZenService.Evaluation:output_type -> authzen.v1.EvaluationResponse
	10, // 49: authzen.v1.AuthZenService.Evaluations:output_type -> authzen.v1.EvaluationsResponse
	15, // 50: authzen.v1.AuthZenService.SubjectSearch:output_type -> authzen.v1.SubjectSearchResponse
	17, // 51: authzen.v1.AuthZenService.ResourceSearch:output_type -> authzen.v1.ResourceSearchResponse
	19, // 52: authzen.v1.AuthZenService.ActionSearch:output_type -> authzen.v1.ActionSearchResponse
	21, // 53: authzen.v1.AuthZenService.GetConfiguration:output_type -> authzen.v1.GetConfigurationResponse
	48, // [48:54] is the sub-list for method output_type
	42, // [42:48] is the sub-list for method input_type
	42, // [42:42] is the sub-list for extension type_name
	42, // [42:42] is the sub-list for extension extendee
	0,  // [0:42] is the sub-list for field type_name
}

func init() { file_authzen_v1_authzen_service_proto_init() }
func file_authzen_v1_authzen_service_proto_init() {
	if File_authzen_v1_authzen_service_proto != nil {
		return
	}
	file_authzen_v1_authzen_service_proto_msgTypes[0].OneofWrappers = []any{}
	file_authzen_v1_authzen_service_proto_msgTypes[1].OneofWrappers = []any{}
	file_authzen_v1_authzen_service_proto_msgTypes[2].OneofWrappers = []any{}
	file_authzen_v1_authzen_service_proto_msgTypes[3].OneofWrappers = []any{}
	file_authzen_v1_authzen_service_proto_msgTypes[4].OneofWrappers = []any{}
	file_authzen_v1_authzen_service_proto_msgTypes[5].OneofWrappers = []any{}
	file_authzen_v1_authzen_service_proto_msgTypes[6].OneofWrappers = []any{}
	file_authzen_v1_authzen_service_proto_msgTypes[7].OneofWrappers = []any{}
	file_authzen_v1_authzen_service_proto_msgTypes[8].OneofWrappers = []any{}
	file_authzen_v1_authzen_service_proto_msgTypes[11].OneofWrappers = []any{}
	file_authzen_v1_authzen_service_proto_msgTypes[12].OneofWrappers = []any{}
	file_authzen_v1_authzen_service_proto_msgTypes[13].OneofWrappers = []any{}
	file_authzen_v1_authzen_service_proto_msgTypes[14].OneofWrappers = []any{}
	file_authzen_v1_authzen_service_proto_msgTypes[15].OneofWrappers = []any{}
	file_authzen_v1_authzen_service_proto_msgTypes[16].OneofWrappers = []any{}
	file_authzen_v1_authzen_service_proto_msgTypes[17].OneofWrappers = []any{}
	file_authzen_v1_authzen_service_proto_msgTypes[18].OneofWrappers = []any{}
	file_authzen_v1_authzen_service_proto_msgTypes[20].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_authzen_v1_authzen_service_proto_rawDesc), len(file_authzen_v1_authzen_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_authzen_v1_authzen_service_proto_goTypes,
		DependencyIndexes: file_authzen_v1_authzen_service_proto_depIdxs,
		EnumInfos:         file_authzen_v1_authzen_service_proto_enumTypes,
		MessageInfos:      file_authzen_v1_authzen_service_proto_msgTypes,
	}.Build()
	File_authzen_v1_authzen_service_proto = out.File
	file_authzen_v1_authzen_service_proto_goTypes = nil
	file_authzen_v1_authzen_service_proto_depIdxs = nil
}
