name: push
on:
  push:
    branches:
      - main
    paths:
      - openfga/**/*.proto
      - buf.md
      - buf.lock
      - README.md
  workflow_dispatch:

permissions:
  contents: read

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.5.4
        with:
          fetch-depth: 0

      - uses: bufbuild/buf-setup-action@a9cf7d0e410e4e9166fd3ffacd119a2cf0d50f2b # v1.27.1-1
        with:
          version: "1.15.1"
      - uses: bufbuild/buf-push-action@1c45f6a21ec277ee4c1fa2772e49b9541ea17f38 # v1.1.1
        with:
          buf_token: ${{ secrets.BUF_TOKEN }}
      - name: Send PagerDuty alert on failure
        if: ${{ failure() }}
        uses: miparnisari/action-pagerduty-alert@0.3.2
        with:
          pagerduty-integration-key: ${{ secrets.PAGERDUTY_INTEGRATION_KEY }}
          incident-summary: "Problem pushing OpenFGA Buf module to Buf Registry"
