name: push
on:
  push:
    branches:
      - main
    paths:
      - openfga/**/*.proto
      - buf.md
      - buf.lock
      - README.md
  workflow_dispatch:

permissions:
  contents: read

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4.1.3
        with:
          fetch-depth: 0

      - uses: bufbuild/buf-action@d4b43256b3a511e94e6c0d38d478e1bd39f8690e # v1.0.1
        with:
          push: true
          buf_token: ${{ secrets.BUF_TOKEN }}
      - name: Send PagerDuty alert on failure
        if: ${{ failure() }}
        uses: miparnisari/action-pagerduty-alert@a6a738b712efa0e1a45b1b796c62f60fc30b5d99 # v0.3.2
        with:
          pagerduty-integration-key: ${{ secrets.PAGERDUTY_INTEGRATION_KEY }}
          incident-summary: "Problem pushing OpenFGA Buf module to Buf Registry"
