name: push
on:
  push:
    branches:
      - main
    paths:
      - openfga/**/*.proto
      - buf.md
      - buf.lock
      - README.md

jobs:
  build:
    needs: buf-fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bufbuild/buf-setup-action@v1
        with:
          version: "1.4.0"
      - uses: bufbuild/buf-push-action@v1
        with:
          buf_token: ${{ secrets.BUF_TOKEN }}
